### ISSUE TITLE
conceptualStructure output font size too small

### ISSUE THREAD

**Issue by DRManager** [massimoaria/bibliometrix#1]
Hi, I  experiment with your bibliometrix package immediately after coming across it through a search engine. I like it very much so far. Most of the functions work great. However, I have an issue with the output of conceptualStructure. The font size within each cluster is too small to be readable. One example is shown in [link](https://github.com/DRManager/graphene/blob/master/conceptual_structure.png).

The function is using the default setting. 
CS <- conceptualStructure(M,field="ID", minDegree=4, k.max=5, stemming=FALSE)

Your example file shows clear image. I am wondering is it related to system setting or there are more keywords in my search file? If it is later, is there an option to increase font size of the keywords within the plot?

Thanks,
Rick

**Comment by massimoaria** [comment]
Dear Rick,

The function conceptualStructure has an additional argument "labelsize" to change the font size.

Please look at the help help(conceptualStructure) for complete information about arguments of the function.

Regards
Massimo 

⁣Inviato da BlueMail ​

Il giorno 21 mar 2017, 06:53, alle ore 06:53, DRManager <notifications@github.com> ha scritto:

**Comment by DRManager** [comment]
Thank you very much Massimo. This issue is closed. 

One related question for the networkPlot. I have specified vos.path. But it seems to have no effect on the output. Is vos.path parameter intend to call Vosviewer to visualize the output? I later look at VOSviewer folder, there is no "VOSviewer.jar" file as shown in your document. 

`vospath <- "C:/VOSviewer"
# plot authors' similarity (first 10 authors)
net=networkPlot(S, n = 5, Title = "Authors' Coupling", type = "fruchterman", size=TRUE,remove.multiple=TRUE, vos.path = vospath)`

**Comment by massimoaria** [comment]
As clarified in the vignettes, you have to download vosviewer from its website and place the file in a folder.


⁣Inviato da BlueMail ​

Il giorno 22 mar 2017, 06:30, alle ore 06:30, DRManager <notifications@github.com> ha scritto:
