### ISSUE TITLE
Can I modify the database?

### ISSUE THREAD

**Issue by matbarcelo** [massimoaria/bibliometrix#103]
Hello!

Very useful bibliometrix package with very interesting results.

Now my question is about whether it is possible to use it after I want to modify my search. 

That is, after screening the papers, where I can exclude the ones that are out of the focus of study.

The easiest way I know to edit the database after downloading it is in excel, but it seems that the package does not support the conversion of this file. So I would like to know if there is another way to modify the database and then use the bibliometrix package?

Greetings and thank you very much.

**Comment by massimoaria** [comment]
You can remove papers from the bibliographic data frame just using classical R commands to drop rows from a data frame.
i.e. Image you want to remove the documents at the rows 3, 9, 23 and 56 and your data frame is M.
ind <- c(3,9,23,56)
M <- M[ind,]

Another possibility is to use the "rio" package to export in excel your bibliographic data frame, remove the excel rows you don't need and re-load it in R.
i.e.
rio::export(M, file = "yourfile.xlsx")
# remove rows in excel and then
M <- rio::import("yourfile.xlsx")
row.names(M) <- M$SR

Alternatively, you could use biblioshiny() to import and convert the collection and then export it in excel. After removing not useful documents deleting some excel rows, you can read it in biblioshiny() and eventually export it as R data.

NB. changing the column names, deleting some columns or changing the column formats could make the file no longer compatible with the excel standard codify used by bibliometrix.

**Comment by matbarcelo** [comment]
Very clear! 

It's working

Thanks!
