### ISSUE TITLE
Authors with non English characters are wrongly represented in the top authors graph

### ISSUE THREAD

**Issue by loxavia** [massimoaria/bibliometrix#104]
Authors whom have some characters of their names that has a dot or so, has problem in the top authors over time graph, it is very obvious in Spanish names. I had to fix the names myself so that it shows up, the problem  happened in two projects.

**Comment by massimoaria** [comment]
Please, attach an example to show us the issue (code and data)

**Comment by loxavia** [comment]
Nothing special about he code, here it is,
topAU <- authorProdOverTime(M, k = 20, graph = TRUE)
I was able to get more by looking back at my data, the problem is perfectly reproducible when the author has - or a special character in his name.
Here is an example of the graph with the third author who has 29 publications has only points listed, after deleting the  - from all names and his, the chart works perfectly well.
[Presentation1.pptx](https://github.com/massimoaria/bibliometrix/files/4564814/Presentation1.pptx)

**Comment by massimoaria** [comment]
I need you to attach your bibliographic file to identify and eventually solve the issue.

**Comment by loxavia** [comment]
Here is a link as I could not attach it here, the issue also affects the HIndex function as it reports only 3 citations for that author and wring number of articles too,  he has 495  and 40 articles, 
My workaround was to do something like this    M$AU->M$AUz; M$AU <- gsub("-", "" ,M$AU)
Try the reproduce the author productivity graph with and without the gsub.

https://1drv.ms/u/s!AkmxjR89BYNags9uI6yvubxmmfszEQ?e=JMdLe4

And of course, I am big fan of the library, and grateful for your work.

**Comment by massimoaria** [comment]
I solved the issue by modifying the function tableTag.

**Comment by loxavia** [comment]
Thank you, I appreciate it so much
