### ISSUE TITLE
Possible issue regarding the summation of total citations per country

### ISSUE THREAD

**Issue by CarlosML** [massimoaria/bibliometrix#106]
My colleague @andreaolmos90 and I are using bibliometrix to perform bibliometric analysis, we have observed that when importing data from Scopus using `convert2df()` and then running `summary()` on the object returned by `biblioAnalysis()`, the result of "Total Citations per Country" seems to be inconsistent with, for example, "Corresponding Author's Countries" or "Country collaboration network". 
I have no experience with the R language, so this is my amateur attempt to debug the problem:

The object returned by `biblioAnalysis()` has a column 'totalCitation' which is a copy ([biblioAnalysis.R @ 194](https://github.com/massimoaria/bibliometrix/blob/63c166f6e217732027b10453307e1eed9cd802e8/R/biblioAnalysis.R#L194)) of the 'TC' column of the dataframe generated by `convert2df()`. When running `summary()`, a sum is calculated using all 'totalCitation' values grouped by country ([summary.bibliometrix.R @ 178](https://github.com/massimoaria/bibliometrix/blob/63c166f6e217732027b10453307e1eed9cd802e8/R/summary.bibliometrix.R#L178)). However, we have noticed that sometimes the 'totalCitation' column has as value NA, and when R adds NA to an integer, the result is NA. Therefore, any country that in the object returned by `biblioAnalysis()` has any row with an NA value will have NA as the total number of citations. In convert2df.R, [line 142](https://github.com/massimoaria/bibliometrix/blob/63c166f6e217732027b10453307e1eed9cd802e8/R/convert2df.R#L142) converts TC to numeric:

`if ("TC" %in% names(M)){M$TC=as.numeric(M$TC)} else {M$TC <- 0}
`
(in [csvScopus2df.R](https://github.com/massimoaria/bibliometrix/blob/63c166f6e217732027b10453307e1eed9cd802e8/R/csvScopus2df.R#L56), 'Cited by' is renamed to 'TC')

In the CSVs exported by Scopus, the column "Cited by" always seems to be present, but in some rows it has no value. So, presumably, if 'Cited by' is empty its coercion to numeric returns NA, thus ruining the sum of total citations.

**Comment by massimoaria** [comment]
I tried to solve the issue by modifying line 142 in convert2df.R. But I need an example file to check if the issue has been fixed.

**Comment by CarlosML** [comment]
[This one](https://drive.google.com/open?id=1-ff3_7EUlJy-lDRY4zhOWDUAjdWsa7hA) has this issue with the country 'USA'.

**Comment by massimoaria** [comment]
I tried to upload and analyze your file, and summary function seems to work correctly now.
