### ISSUE TITLE
How to convert an edlist to bibliometrix formats

### ISSUE THREAD

**Issue by rafetirmak** [massimoaria/bibliometrix#107]
I have a data set of in edgelist format.

each ID represents a document. 
Relation is from citing document to cited document.

How can I convert this edgelist format to bibliometrix format and calculate cocitation similarities ?

How can I convert my edgelist to Metada M in concentional syntax ? Is there a functiin convert2df for edgelist files?

e.g.
biblioNetwork(
  M,
  analysis = "co-citation",
  network = "references",
  n = NULL,
  sep = ";",
  shortlabel = TRUE
)

**Comment by massimoaria** [comment]
No, I am sorry but it is not possible. Edgelist format contains info about single metadata (in your case, references) when M is a data frame containing all metadata (authors, keywords, abstract, affiliations, etc.) about each document. 
You should try to use igraph package to convert an edgelist to an adjacency matrix and then to use it as input for networkPlot function.

**Comment by rafetirmak** [comment]
Many Thanks 

Pubmed do not support citation lists. I have meta data from pubmed and I have PMC citations in edge list format. 

Currently I have performed cocitation analysis with igraph.

I want to combine citation data in edgelist format and Pubmed metadata format and perform future analysis in biblimetrix.

Is it possible by function or scripts.
