### ISSUE TITLE
convert2df undefined columns selected

### ISSUE THREAD

**Issue by jmfulvio** [massimoaria/bibliometrix#109]
Hello-

I have installed the latest bibliometrix from Github and have exported plain text files from Web of Science with all fields selected upon export as per the vignette and all appears to my naive eye to be in line.

However, when I attempt to use convert2df, I am receiving the error message:
Error in [.data.frame (df, tagsComma) : undefined columns selected

The .txt file is attached. Any advice would be much appreciated. Thank you and take care!

[savedrecs.txt](https://github.com/massimoaria/bibliometrix/files/4616099/savedrecs.txt)

**Comment by massimoaria** [comment]
In your file, author's keywords are missing.
However, last developer version overcomes this issue providing a warning without stopping the conversion process.
Please, update bibliometrix.
