### ISSUE TITLE
histNetwork for scopus?

### ISSUE THREAD

**Issue by cownr10r** [massimoaria/bibliometrix#11]
When I try and perform histNetwork function on M, i get the following message:

"Sorry, but for the moment histNetwork works only with WoS collections". Can you provide histNetwork for Spopus as well?

**Comment by massimoaria** [comment]
This is not an issue but a limitation due to the non-standard codify used by Scopus in collecting references.
I am already working to find a solution.

**Comment by cownr10r** [comment]
Thank you very much for your help! :-)

**Comment by massimoaria** [comment]
I have just update histNetwork function to work with Scopus collections.
The function identifies direct citation using document titles. 
This is the first attempt, please let me know if you find bugs.

**Comment by cownr10r** [comment]
Thank you very much! I appreciate your help. :-)
