### ISSUE TITLE
reading in bibfile or MyBibliography

### ISSUE THREAD

**Issue by andreashandel** [massimoaria/bibliometrix#111]
Hi,
Thanks for a great package! 
I'm trying to perform some analysis of my own papers.
I previously was able to read in a bib file (that I manage with Zotero) with readFiles and then convert with convert2df. Since readFiles is gone in the new version, I tried to load the file directly with convert2df("myrefs.bib", dbsource = "isi", format = "bibtex") (those settings worked previously).

That didn't work, neither did a number of variations I tried. How can I get my own bib file read in? Or alternatively, is there a way I can download my Pubmed mybibliography (https://www.ncbi.nlm.nih.gov/myncbi/1lO-aqCZWgr5F/bibliography/public/) in a format that can be read in? (I can't use pubmedR query since it's close to impossible to capture all of my papers but nobody else's). Mybibliography is curated by me, so I know it's right.
Thanks!

**Comment by massimoaria** [comment]
From version 3.0, bibliometrix supports export files downloaded from PubMed.
Export your bibliography as "medline" export file and then read it with convert2df:
M <- convert2df("medline.txt", dbsource="pubmed",format="pubmed")

**Comment by andreashandel** [comment]
Thanks for the quick reply. I tried it but it doesn't work. I get the following error message:

Error: Names must be unique.
x These names are duplicated:
  * "IS" at locations 19 and 20.

Looking into the text file, I notice that each entry has 2 IS fields, which are sometimes showing the same number, sometimes different ones. Here is an example:
IS  - 2041-1723 (Electronic)
IS  - 2041-1723 (Linking)

My guess is that this is causing the error?

For reproduciblity, here's my medline.txt file causing the error: 
https://github.com/andreashandel/andreashandelwebsite/blob/master/content/post/2020-02-02-publications-analysis-2/medline.txt

Thanks!

**Comment by massimoaria** [comment]
Please, update bibliometrix from GitHub.

devtools::install_github("massimoaria/bibliometrix")

**Comment by andreashandel** [comment]
That worked, thanks!
