### ISSUE TITLE
Country

### ISSUE THREAD

**Issue by adrielmagalhaes** [massimoaria/bibliometrix#112]
I'm doing a bibliometric analysis for my PhD thesis and I'm using biblimetrix. After my analysis, I've checked the results and saw there is something wrong about the countries.

There is a difference between the number of Country Scientific Production (CSP), Most Cited Countries (MCC) and Corresponding Author's Country (CAC). For CSP the total of countries was 34, but for MCC and CAC was only 29. What could be happening?

In addition, the number of articles on CSP and CAC is different from the total number of articles analyzed. (CSP = 1419, CAC = 1002 and total documents = 1445).

One suggestion: you could add a legend on the country scientific production world map, correlating the color intensity with the production.

P.S.: Congratulations for your work. The software is very well done.

Thank you

**Comment by massimoaria** [comment]
Please, attach your file so I can check your issue.

**Comment by adrielmagalhaes** [comment]
I am attaching the original dataset (Databasefinalmaf.xlsx). The other 3 files are the outputs of bibliometrix. You can see that the number of articles is different between files (which shouldn't be)...

[Databasefinalmaf.xlsx](https://github.com/massimoaria/bibliometrix/files/4726073/Databasefinalmaf.xlsx)

[Most_Relevant_Countries_By_Corresponding_Author.xlsx](https://github.com/massimoaria/bibliometrix/files/4726091/Most_Relevant_Countries_By_Corresponding_Author.xlsx)

[Most_Cited_Countries.xlsx](https://github.com/massimoaria/bibliometrix/files/4726087/Most_Cited_Countries.xlsx)

[Country_Production.xlsx](https://github.com/massimoaria/bibliometrix/files/4726080/Country_Production.xlsx)

**Comment by massimoaria** [comment]
I am looking at your files. Some differences are due to missing data in some fields (in particular in the corresponding author's affiliation column "RP") and maybe there is a little bug in RP country extraction. Please, send me the raw export files downloaded from WOS.
Thanks

**Comment by adrielmagalhaes** [comment]
I attached the raw files (WOS and Scopus). After the extraction from both databases, I removed the duplicates (Databasefinalmaf.xlsx) with an R code. I think the problem is RP column... and I will have to fill manually.

[wos-0-499.txt](https://github.com/massimoaria/bibliometrix/files/4730668/wos-0-499.txt) 
[wos-500-962.txt](https://github.com/massimoaria/bibliometrix/files/4730669/wos-500-962.txt)


[scopus-1460.txt](https://github.com/massimoaria/bibliometrix/files/4730667/scopus-1460.txt)
