### ISSUE TITLE
conceptualStructure ERROR incorrect number of dimensions

### ISSUE THREAD

**Issue by lizhouf** [massimoaria/bibliometrix#113]
Hi, when I use this code:

`CS <- conceptualStructure(M,field="ID", method="CA", minDegree=4, clust=5, stemming=FALSE, labelsize=10, documents=10)`

I got this error:

> Error in CW[, !(colnames(CW) %in% "NA")] : incorrect number of dimensions

Could you help me fix this? Thanks

P.S. Here is the data I use: 
[WOS_DHQ_new.txt](https://github.com/massimoaria/bibliometrix/files/4654648/WOS_DHQ_new.txt)

**Comment by massimoaria** [comment]
The error means that the output matrix is empty because minDegree is too high for your data.
Try, for example, minDegree = 2 and it works fine.

**Comment by lizhouf** [comment]
This works, thanks!

> minDegree = 2
