### ISSUE TITLE
Historical Direct Citation Network ERROR  replacement has 1 row, data has 0

### ISSUE THREAD

**Issue by lizhouf** [massimoaria/bibliometrix#114]
Hi, here is another issue I have:

when I use this code:
`# Create a historical citation network
options(width=130)
histResults <- histNetwork(M, min.citations = 1, sep = ";")
# Plot a historical co-citation network
net <- histPlot(histResults, n=15, size = 10, labelsize=5)`

I got this error:

> Error in `$<-.data.frame`(`*tmp*`, "cluster", value = 0) : replacement has 1 row, data has 0

Could you also help me look at this? Thanks.

And here is the data I use: 
[WOS_DHQ_new.txt](https://github.com/massimoaria/bibliometrix/files/4654661/WOS_DHQ_new.txt)

**Comment by massimoaria** [comment]
In your collection, there are not local citations.
In fact, running your code:
```
histResults <- histNetwork(M, min.citations = 1, sep = ";")
```
the output is:
WOS DB:
Searching local citations (LCS) by reference items (SR) and DOIs...

Analyzing 12603 reference items...

**Found 0 documents with no empty Local Citations (LCS)**

So, if you have 0 documents with no empty Local Citations, it does not make sense trying to perform a plot using histPlot!
