### ISSUE TITLE
Co-citation analysis

### ISSUE THREAD

**Issue by rar103** [massimoaria/bibliometrix#116]
Hi there, I'm trying to do a bibliometric analysis with your tool and found out a weird error that happens when I try to do a co-citation analysis, from the example provided.

As soon as I use biblioNetwork with network="authors"
`
data(scientometrics)

NetMatrix <- biblioNetwork(scientometrics, analysis = "co-citation", 
network = "references", sep = ";")

net <- networkPlot(NetMatrix, n = 30, type = "kamada", Title = "Co-Citation",labelsize=0.5) 
`
Says

 Error in crossprod(x, y) : 
  requires numeric/complex matrix/vector arguments 

And happens with anything but references

**Comment by massimoaria** [comment]
The error says:
"Field CR_AU is not a column name of input data frame"

When you perform a co-citation analysis of authors, the biblioNetwork function needs to analyze a field "CR_AU" containing the list of authors extracted from references (CR).
This column field is not standard so it has to be extracted from Cited References (CR) using the function metaTagExtraction:
scientometrics <- metaTagExtraction(scientometrics, Field="CR_AU")

and then you can perform an author co-citation analysis
NetMatrix <- biblioNetwork(scientometrics, analysis = "co-citation",
                           network = "authors", sep = ";")

net <- networkPlot(NetMatrix, n = 30, type = "kamada", Title = "Co-Citation",labelsize=0.5)
