### ISSUE TITLE
Labels in Lower case

### ISSUE THREAD

**Issue by loxavia** [massimoaria/bibliometrix#117]
While this may be an issue, but It is really important to have the names of authors , countries and journals with first letter/s capitalized or at lease the option to have the name in upper case, I traced the code and I can see that each function forces for lower case. In our last project, we had to extract all networks to Gephi to re-draw them or use a PDF editor for fixing the author plot.

**Comment by massimoaria** [comment]
I understand your point but we chose to follow a "text mining" approach standardizing all text fields in upper case (data frame and tables) and lower case in plots.
