### ISSUE TITLE
Reduced data frame produces error message

### ISSUE THREAD

**Issue by andreashandel** [massimoaria/bibliometrix#118]
Hi,
I'm importing a Medline file with this:
pubs <- bibliometrix::convert2df("medline.txt", dbsource="pubmed",format="pubmed")

Then if I want to analyze, this works:
res <- bibliometrix::biblioAnalysis(pubs)

But if I only want to analyze some of the data, e.g. only recent papers, this fails:
res <- bibliometrix::biblioAnalysis(pubs[pubs$PY>2015,])

Error in df$Country[i] <- co : replacement has length zero

Since both times I feed the same data frame into biblioAnalysis, only once a smaller one, I don't understand what's going on. Any suggestion how to get this to work? 
I'm using 3.0.2 and all my other packages are updated. R 4.0 on Windows.
Thanks!

**Comment by massimoaria** [comment]
Please upload your file.

**Comment by andreashandel** [comment]
[medline.txt](https://github.com/massimoaria/bibliometrix/files/4787565/medline.txt)
