### ISSUE TITLE
Regarding Cleaning datasets for Bibliometrix

### ISSUE THREAD

**Issue by shail847** [massimoaria/bibliometrix#119]
I have merged two datasets one from web of science and another from Scopus for bibliometric analysis. I want to clean this merged Master_Sheet. In the first Variable "AU" , there are 2 observations with anonymous author and given "[ANONYMOUS]". I am deleting these two rows, from A <- subset(Master_Sheet, AU != "[ANONYMOUS]"). it is running successfully but not deleting any rows from datasets. Kindly help me to solve this.

**Comment by massimoaria** [comment]
Try to use:
A <- subset(Master_Sheet, regexpr("ANONYMOUS",Master_Sheet$AU)==-1)

**Comment by shail847** [comment]
Thanks Massimo....Now its working.
