### ISSUE TITLE
metaTagExtraction bug

### ISSUE THREAD

**Issue by jmunoz298** [massimoaria/bibliometrix#12]
metaTagExtraction fails with AU1_CO field extraction

It returns "GEORGIA"  for first authors with "GEORGIA INST TECHNOL" in C1 field 

I attach an example data frame

(see rows  28 42 52 116 150 186)

[wos_test.RData.zip](https://github.com/massimoaria/bibliometrix/files/2106720/wos_test.RData.zip)

**Comment by massimoaria** [comment]
Solved.

**Comment by ashimog** [comment]
This does not fix the problem. In case you didn't notice, there is a country in the Caucasus region which happens to have the name of 'Georgia'. Simply gsub all 'Georgia' to 'USA' solves nothing.
