### ISSUE TITLE
histNetwork issue

### ISSUE THREAD

**Issue by guillermo-orjuela** [massimoaria/bibliometrix#120]
Hello Dr. Aria.
When I am running the histNetwork function, the following error message appears: 
Error: `x` must be a vector, not a `data.frame/bibliometrixDB` object.
Run `rlang::last_error()` to see where the error occurred.
I try with data frames from Scopus and WoS, after converting with the convert2df function, but in both cases the error is the same.

**Comment by massimoaria** [comment]
The issue is due to a bug in R 4.0 and dplyr. However, I have overcome the issue. Please update bibliometrix from GitHub.
