### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by tersigeek** [massimoaria/bibliometrix#121]
Hello, 
I have a problem with instalation of package bibliometrix.
I always get this error. 

> devtools::install_github("massimoaria/bibliometrix")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: NULL
  error: package ‘backports’ does not have a namespace

Could you help me please?
Thanks! :)

**Comment by massimoaria** [comment]
Please have a look at our FAQ (Q21) section on www.bibliometrix.org
