### ISSUE TITLE
Warning: Error in tag: argument is missing, with no default

### ISSUE THREAD

**Issue by mkaur977** [massimoaria/bibliometrix#123]
Warning: Error in tag: argument is missing, with no default
  65: tag
  64: tags$div
  63: div
  62: conditionalPanel
Warning: Error in tag: argument is missing, with no default
  65: tag
  64: tags$div
  63: div
  62: conditionalPanel

**Comment by massimoaria** [comment]
Error in which function? What data?

**Comment by shahmad789** [comment]
![Biblioshiny Error](https://user-images.githubusercontent.com/62034982/86629333-ed644e80-bfd3-11ea-9594-619007caf3cf.JPG)

**Comment by shahmad789** [comment]
Dear Prof Massimo, please check above error.

**Comment by massimoaria** [comment]
The error is due to a crash in R environment. It does not depend on bibliometrix.
Try to update R to the last version (4.0.2)

**Comment by Biabiatiz** [comment]
I have the same error by trying to open biblioshiny (even while using the last version of R)

>     library(bibliometrix)
>     biblioshiny() 

_Listening on http://127.0.0.1:6364
Warning: Error in tag: argumento ausente, sem padrão
  65: tag
  64: tags$div
  63: div
  62: conditionalPanel
Warning: Error in tag: argumento ausente, sem padrão
  65: tag
  64: tags$div
  63: div
  62: conditionalPane_
