### ISSUE TITLE
the function "left_join" could not be found

### ISSUE THREAD

**Issue by thallescard** [massimoaria/bibliometrix#124]
Hello,

Thanks fo such great tool.

When using biblioshiny interface and trying to generate the most relevant authors report,  it throws the following error:

**Error: the function "left_join" could not be found** 

(ps: this is a translated text from my default language)

On R studio console the following errors appears:

```
Warning: `group_by_()` is deprecated as of dplyr 0.7.0.
Please use `group_by()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
Warning: Error in left_join: não foi possível encontrar a função "left_join"
  146: descriptive [C:\Users\Thalles\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#3302]
  145: eventReactiveHandler [C:\Users\Thalles\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#1213]
  101: MRAuthors
  100: renderPlotly [C:\Users\Thalles\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#1254]
   99: func
   96: func
   83: origRenderFunc
   82: output$MostRelAuthorsPlot
    2: runApp
    1: biblioshiny
```

My R version is 4.0.2 and the R studio version is 1.3.959  and bibliometrix version is 3.0.2

The desired report works fine from bibliometrix summary function on console

Looking forward for your reply

Thanks again !

![Screenshot(2)](https://user-images.githubusercontent.com/68288746/87443829-62371a00-c5cc-11ea-854f-1176bb9e4dd4.png)

**Comment by ReneFGJr** [comment]
I'm having the same problem in the list of authors
![image](https://user-images.githubusercontent.com/7451759/87883038-e9c0c680-c9da-11ea-9ac6-21b29c08b446.png)

**Comment by massimoaria** [comment]
You can overcome the issue loading dplyr library before launch biblioshiny:
library(dplyr)

However, I have just fixed the issue. So alternatively, You can update bibliometrix from GitHub:

install.packages("devtools")
devtools::install_github("massimoaria/bibliometrix")
