### ISSUE TITLE
metaTagExtraction: AU_CO

### ISSUE THREAD

**Issue by embruna** [massimoaria/bibliometrix#125]
In the arguments for ```metaTagExtraction```, the definition given for ```AU_CO``` is "Country of afﬁliation for each co-author". I suggest this be changed to "countries of affiliation for co-authors"   

"each" implies you are giving all of the affiliations - one for each of the co-authors.. But in the case of an article whose 4 authors are affiliated as follows (1) Mexico, (2) USA, (3) USA, and (4) Canada 

the result of ```metaTagExtraction$AU_CO``` is ```"MEXICO  USA  CANADA"```
the output for "Country of afﬁliation for each co-author". would be ```MEXICO USA USA CANADA``` (each coauthors affiliation). What is actually being returned is the collection of affiliations for all coauthors, some of which might be in the same country. This is quite confusing, and suggests one can calculate, for example, the total number of authors from different countries.

**Comment by massimoaria** [comment]
The function metaTagExtraction should work in this way: "each" implies you are giving all of the affiliations - one for each of the co-authors. But in the case of an article whose 4 authors are affiliated as follows (1) Mexico, (2) USA, (3) USA, and (4) Canada"
The result is different when it is not possible to derive the country info from the affiliation items of one or more co-authors.

**Comment by embruna** [comment]
Oh, yes - I understood that. I was just suggesting a minor word to make that clearer.

**Comment by massimoaria** [comment]
Thanks.
I corrected the function description.
