### ISSUE TITLE
histNetwork for scopus ! Error: `x` must be a vector, not a `data.frame/bibliometrixDB` object.

### ISSUE THREAD

**Issue by ManikandanThiagarajan** [massimoaria/bibliometrix#127]
When I try and perform histNetwork function on M, i get the following message:

> histResults <- histNetwork(M, min.citations = 1, sep = ";", network = TRUE, verbose = TRUE)

SCOPUS DB: Searching local citations (LCS) by document titles (TI) and DOIs...
Error: `x` must be a vector, not a `data.frame/bibliometrixDB` object.

**Comment by massimoaria** [comment]
The issue seems due to missing reference metadata in your collection.
Please, attach your collection so I could check the problem.

**Comment by ManikandanThiagarajan** [comment]
@massimoaria : I have downloaded the collection of bibtex from scopus. This is my downloaded data from scopus
[scopus.zip](https://github.com/massimoaria/bibliometrix/files/4947914/scopus.zip)

**Comment by massimoaria** [comment]
The error is due to a bug in dplyr package. I have just fixed it.
Please, update bibliometrix from github and try it.
