### ISSUE TITLE
Installation/loading error: there is no package called ‘XML’

### ISSUE THREAD

**Issue by xhan85** [massimoaria/bibliometrix#128]
I installed bibliometrix through CRAN along with all of its dependencies and it says that everything was unpacked successfully.

When I try to load bibliometrix, I get the following error:
 library(bibliometrix)
Error: package or namespace load failed for ‘bibliometrix’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘XML’

Not sure what to do as there is no package called XML. I have xlm2 but that didn't solve anything...

Please advise.

**Comment by massimoaria** [comment]
Please update R and read the FAQ (Q21) on our website www.bibliometrix.org
