### ISSUE TITLE
Extract authors' first names

### ISSUE THREAD

**Issue by lhehnke** [massimoaria/bibliometrix#13]
Dear all,

I'm currently working with bibliometrix (thanks for providing this awesome package!) and was wondering whether it's possible to extract information on the respective authors' first names (i.e., not only the first letter but the full name)?

Thanks in advance!

**Comment by massimoaria** [comment]
Authors' full names are stored in the "AF" field. 
If you want analyze it instead of short names, you can try to overwrite AU data with AF data:
ie.
M$AU <- M$AF
