### ISSUE TITLE
Erro: Unknown colour name: transparent

### ISSUE THREAD

**Issue by jacksonraniel** [massimoaria/bibliometrix#132]
First of all, the Bibliometrix project is just amazing. Congratulations!

When I run the function conceptualStructure(), no matter with what parameters, after plot the conceptual structure map and before plot the topic dendrogram, the error "Erro: Unknown colour name: transparent" is shown and the function finishes its execution.

How can we fix it? Is it a problem with the package's versions? 

I'm using R version 3.6.3, Bibliometrix version 3.0.1, ggplot2 version 3.3.2, and RColorBrewer version 1.1-2, on top of a Ubuntu 18.04 OS.

Regards.

**Comment by massimoaria** [comment]
Please, attach your code and your data here.

**Comment by jacksonraniel** [comment]
Hi @massimoaria,

That problem happens every time, even when I'm using the bibliometrix-vignette code example.

```
## ----bibliometrix loading-----------------------------------------------------
library(bibliometrix)   ### load bibliometrix package

## ----Data converting----------------------------------------------------------
file <- "https://www.bibliometrix.org/datasets/savedrecs.bib"

M <- convert2df(file = file, dbsource = "isi", format = "bibtex")

## ----Co-Word Analysis, fig.height=9, fig.width=9, warning=FALSE-------------------------------------------------------

# Conceptual Structure using keywords (method="CA")

CS <- conceptualStructure(M,field="ID", method="CA", minDegree=4, clust=5, stemming=FALSE, labelsize=10, documents=10)

```

Thanks for minding it

**Comment by massimoaria** [comment]
Unfortunately,
I cannot able to replicate your error.

If I try to run your code all works well!

![image](https://user-images.githubusercontent.com/16023543/94360325-a787c580-00ac-11eb-942d-74aaeff74c7a.png)

**Comment by jacksonraniel** [comment]
I will have to do this analysis in a few months, with my real data. So, I'll spend some more time doing a deeper investigation about that error and I'll come back here to report if a find something.

**Comment by jacksonraniel** [comment]
Hi,

I've just updated everything on my machine for other reasons, and there is no more issue.

Now I'm using R version 4.0.3, Bibliometrix version 3.0.3, on top of a Ubuntu 18.04 OS.

So, the case is closed.

Thank you for your support!
