### ISSUE TITLE
How to filter out missing values from data?

### ISSUE THREAD

**Issue by ricber** [massimoaria/bibliometrix#136]
Hi,
I see that biblioshiny exposes a Filter feature. I suppose it is to filter out missing values. Indeed, I was trying to test the function `authorProdOverTime` that, however, gave me the error
```
 Error in seq.default(min(df2$year), max(df2$year), by = 2) : 
  'from' must be a finite number
```
I've discovered that this is due to the presence of `NA` in `df2$year`. Do you provide a filter function also in the R bibliometrix package? Thank you.

**Comment by massimoaria** [comment]
Hi, 
filter menu in Biblioshiny allows applying some filter rules to the collection to identify a subset.
You need a data cleaning procedure to remove missing values, NaN, etc.
You can do that using some R base functions.
Ex.
# df2 is your bibliographic data frame

## identify rows with missing PY
ind <- which(is.na(df2$PY))

## remove rows with missing PY
df2 <- df2[-ind,]
