### ISSUE TITLE
Suggestion: replace ggplot by ggplotly

### ISSUE THREAD

**Issue by frajuegies** [massimoaria/bibliometrix#139]
Hi,

I just learn that the package has been further improved.... biblioshiny is a great new feature... congrats.

By playing around I have seen that sometime ggplot and sometimes plotly is used. It would be great if all ggplot-graphs would be a plotly graph to use its interactivity.

Perhaps, you might consider this suggestion.

Best regards,

Jürgen

**Comment by massimoaria** [comment]
"By playing around I have seen that sometime ggplot and sometimes plotly is used. It would be great if all ggplot-graphs would be a plotly graph to use its interactivity."

Unfortunately, the plotly R package does not support ggplot graphs using functions from package ggrepel (i.e. geom_repel_text or geom_repel_label, useful to avoid label overlaps).
So, some few plots need this functionality and then I cannot switch to plotly format.
I prefer to have two different plot formats instead to have some unreadable maps with overlapped labels.

**Comment by frajuegies** [comment]
Hi,

Thank you very much for your explanation. I was not aware about this limitation.

Best regards,
Jürgen
