### ISSUE TITLE
Thematic Evolution and Thematic Map with Time Slices

### ISSUE THREAD

**Issue by MohamedaliS** [massimoaria/bibliometrix#140]
Dear Professor,
Thank you for this wonderful package. 
I used the Bibliometrix version 2.3.1 and 3.0.0 (Biblioshiny) in my research article to analyse the Thematic Evolution and Thematic map with a 20 years (2000-2019) data. Used 4 cutting points of 2003, 2007, 2011 & 2015. The article is accepted in a Journal and in the final page proof stage. 
Now, the journal asked me to provide the figures in an editable format (jpg/png) in 300 DPI resolution or above. But, the outputs from biblioshiny is too low in DPI. 
I tried to do it in Rstudio, but unable to find the codes/examples for plotting thematic maps for each time slice. 
So, please provide me the R code for Word Dynamics - Word Growth (author's Keywords), thematic evolution, and thematic map for each time slice and saving them in 300 DPI or above.

With Thanks & Regards
Dr Ali

**Comment by massimoaria** [comment]
Considering the function example:

```
library(bibliometrix)
data(scientometrics)
years=c(2000)
nexus <- thematicEvolution(scientometrics,field="ID", years=years, n=100,minFreq=2)
```

the object nexus contains the plots (one for each period in ggplot2 format)
i.e.
the first map is:
nexus$TM[[1]]$map

you can use R commands to export the plot with the desired dpi.

The function for word dynamics is keywordGrowth()
Please, have a look at the function help and examples 
?keywordGrowth

**Comment by MohamedaliS** [comment]
Thanks a Lot.
