### ISSUE TITLE
Problem with biblioNetwork() with analysis "co-occurences"

### ISSUE THREAD

**Issue by hwallen** [massimoaria/bibliometrix#141]
I'm having issues with the biblioNetwork -function using analysis = "co-occurences" with Scopus -data.  I have downloaded several datasets in bibtex-format from Scopus with all information exported. Using the function with co-occurences like

biblioNetwork(df1,
                                       analysis = "co-occurences",
                                       network = "author_keywords",
                                       sep = ";")

always produces error 

Error in NetMatrix[nchar(colnames(NetMatrix)) != 0, nchar(colnames(NetMatrix)) !=  : 
  incorrect number of dimensions.

I have tried it with four different datasets from Scopus, but the result is always the same. The function works nicely with other analysis -options though.

**Comment by massimoaria** [comment]
> I'm having issues with the biblioNetwork -function using analysis = "co-occurences" with Scopus -data. I have downloaded several datasets in bibtex-format from Scopus with all information exported. Using the function with co-occurences like
> 
> biblioNetwork(df1,
> analysis = "co-occurences",
> network = "author_keywords",
> sep = ";")
> 
> always produces error
> 
> Error in NetMatrix[nchar(colnames(NetMatrix)) != 0, nchar(colnames(NetMatrix)) != :
> incorrect number of dimensions.
> 
> I have tried it with four different datasets from Scopus, but the result is always the same. The function works nicely with other analysis -options though.

Please, attach your scopus file.

**Comment by hwallen** [comment]
Ah, right. File here.
[02_scopus.zip](https://github.com/massimoaria/bibliometrix/files/5450229/02_scopus.zip)

**Comment by massimoaria** [comment]
> biblioNetwork(df1,
> analysis = "co-occurences",
> network = "author_keywords",
> sep = ";")

There is a typo in your code.
You wrote **analysis = "co-occurences"** while the correct argument is **analysis = "co-occurrences"**

NetMatrix <- biblioNetwork(df1,
      analysis = "co-occurrences", 
      network = "author_keywords", 
      sep = ";")

dim(NetMatrix)
[1] 959 959
