### ISSUE TITLE
Error: arguments imply differing number of rows: 400, 600

### ISSUE THREAD

**Issue by ricber** [massimoaria/bibliometrix#145]
Hi,
I'm obtaining an error with Biblioshiny when I look for the Three-Fields Plot with settings: 
- Middle field: Authors (Number of items: 20)
- Left field: References (Number of items: 20)
- Right field: Keywords **(Number of items: 30)**

The error is:
`Error: arguments imply differing number of rows: 400, 600`

**Comment by massimoaria** [comment]
Hi,

please, upload your code and data.

**Comment by ricber** [comment]
I'm not using any code, I got that error on Biblioshiny. 
[savedrecs.zip](https://github.com/massimoaria/bibliometrix/files/5573068/savedrecs.zip)

**Comment by massimoaria** [comment]
Hi, 
I have just fixed the issue.

***************
Help us to keep Bibliometrix free to download and use by contributing with a small donation to support our research team.
https://bibliometrix.org/donate.html
