### ISSUE TITLE
Error: oggetto "M" non trovato

### ISSUE THREAD

**Issue by ricber** [massimoaria/bibliometrix#148]
Hi,
**[FIRST ISSUE]**
When I try to upload Scopus raw files on Biblioshiny it says `Error: oggetto "M" non trovato`. They are in CSV format.

**[SECOND ISSUE]**
Also, I noted another strange thing... Biblioshiny retrieves the same error when I want to upload a bibliometrix file obtained with the function ` biblioAnalysis` and dataframe name different than "M".
Thus, if I produce a bibliometrix file with the following instruction all works fine:
```results_wos <- biblioAnalysis(M, sep = ";")```

However, for example, if I use this other instruction, it gives the error `Error: oggetto "M" non trovato` when I upload the bibliometrix file `results_wos` on Biblioshiny:
```results_wos <- biblioAnalysis(df_wos, sep = ";")```

I suppose there is hardcoded somewhere the name of the bibliometrix file... Probably by removing the hardcoded name will solve the second issue but I'm not sure about the first one.

**Comment by ricber** [comment]
Ok, I've understood what's going on in the [SECOND ISSUE]. It seems that biblioshiny searches for an object called "M" in the RStudio environment. Thus, for example, if I remove the object M and try to upload a bibliometrif file it gives the same error even if the bibliometrix file has been built with the function:
```results_wos <- biblioAnalysis(M, sep = ";")```

This is a problem because, for example, if I first produce an object M with the R functions and dataset A and then I open Biblioshiny and I want to upload dataset B, then on Biblioshiny what I actually see is object M produced with the dataset A.

**Comment by massimoaria** [comment]
I have solved both the issue:
- Now, biblioshiny automatically recognizes export file formats. Then I removed the file format choice box in the Data menu (FIRST ISSUE)
- Now, at starting, biblioshiny checks for existing of an M object and, if true, removes it.

**Comment by ricber** [comment]
Thank you Massimo and congratulations on this project.

**Comment by ricber** [comment]
Hi, I've tried the new version but just after opening Biblioshiny it retrieves the following warning:
```
> biblioshiny()

Listening on http://127.0.0.1:3708
Warning in rm(M) : oggetto "M" non trovato
```
However, I currently have an object M in my **Global Environment** and if I open Biblioshiny that is exactly what I see. So the problem of the [SECOND ISSUE] is still not solved. I suppose that Biblioshiny checks for an object M in its local environment **package:bibliometrix**. But I'm not sure... I'm not an expert on R and RStudio. I'm just making a hypothesis.

**Comment by massimoaria** [comment]
Solved

**Comment by ricber** [comment]
Ok, now the instruction `rm(M)` effectively remove the object M but still Biblioshiny retrieves `Error: oggetto "M" non trovato` if you try to `Load bibliometrix file(s)`. This feature is really important because I made a preprocessing to my data so I cannot upload the original plaintext files.

**Comment by ricber** [comment]
Also, I do not think that removing the M object from the Global Environment is the right strategy. 

Uploading raw file(s) was working even if there's was an M object in the Global Environment. I suppose that when you upload raw files, biblioshiny creates a new M object somewhere else, not in the Global Environment. So there is no reason to delete the M object in Global Environment.

Also, if you upload a bibliometrix file, you should not search for any M object, you should just take that file as it is, I suppose. A bibliometrix file already has the M object in it...

**Comment by ricber** [comment]
Could be that problem is here?
https://github.com/massimoaria/bibliometrix/blob/4675f9e577218413c7eb74256465ddcffef94478/inst/biblioshiny/server.R#L253

Because I see that you create an M object only in the case of raw files uploaded. However, in the case of upload of rData it correctly seems that you do not create any M object.

**Comment by massimoaria** [comment]
> Ok, now the instruction `rm(M)` effectively removes the object M but still Biblioshiny retrieves `Error: oggetto "M" non trovato` if I try to `Load bibliometrix file(s)`. This feature is really important because I made a preprocessing to my data so I cannot upload the original plaintext files.
> 
> I don't know if it's my fault in saving the bibliometrix file, this is what I do:
> 
> ```
> results_wos <- biblioAnalysis(df_wos, sep = ";")
> save(results_wos, file = paste0(getwd(),"/data/wos/results_wos.RData"))
> ```
> 
> Then I upload `results_wos.RData` on Biblioshiny and I get the error.

Biblioshiny load function is able to read a bibliographic data frame obtained using convert2df function and saved in this way:
save(M, file="mycollection.RData")

You are trying to upload an R object containing a list of results and not a collection of articles.

**Comment by ricber** [comment]
> 
> 
> > Ok, now the instruction `rm(M)` effectively removes the object M but still Biblioshiny retrieves `Error: oggetto "M" non trovato` if I try to `Load bibliometrix file(s)`. This feature is really important because I made a preprocessing to my data so I cannot upload the original plaintext files.
> > I don't know if it's my fault in saving the bibliometrix file, this is what I do:
> > ```
> > results_wos <- biblioAnalysis(df_wos, sep = ";")
> > save(results_wos, file = paste0(getwd(),"/data/wos/results_wos.RData"))
> > ```
> > 
> > 
> > Then I upload `results_wos.RData` on Biblioshiny and I get the error.
> 
> Biblioshiny load function is able to read a bibliographic data frame obtained using convert2df function and saved in this way:
> save(M, file="mycollection.RData")
> 
> You are trying to upload an R object containing a list of results and not a collection of articles.

Actually, it gives the same error... This why I alternatively tried to upload a bibliometrix file (also because "Load bibliometrix file(s)" is a bit misleading. Maybe "Load dataframe file" is better).

**Comment by ricber** [comment]
> 
> 
> Could be this instruction the problem?
> 
> https://github.com/massimoaria/bibliometrix/blob/4675f9e577218413c7eb74256465ddcffef94478/inst/biblioshiny/server.R#L253
> 
> Because I see that you create an M object only in the case of raw files uploaded. However, in the case of upload of rData it correctly seems that you do not create any M object.

I do not see that you create the M object in the case of RData...
https://github.com/massimoaria/bibliometrix/blob/4675f9e577218413c7eb74256465ddcffef94478/inst/biblioshiny/server.R#L240-L249

**Comment by massimoaria** [comment]
> Also, I do not think that removing the M object from the Global Environment is the right strategy.
> 
> Uploading raw file(s) was working even if there's was an M object in the Global Environment. I suppose that when you upload raw files, biblioshiny creates a new M object somewhere else, not in the Global Environment, and that it is what it shows. So there is no reason to delete the M object in the Global Environment.
> 
> Also, if you upload a bibliometrix file, you should not search for any M object, you should just take that file as it is, I suppose. A bibliometrix file already has the M object in it...



> > Could be this instruction the problem?
> > https://github.com/massimoaria/bibliometrix/blob/4675f9e577218413c7eb74256465ddcffef94478/inst/biblioshiny/server.R#L253
> > 
> > Because I see that you create an M object only in the case of raw files uploaded. However, in the case of upload of rData it correctly seems that you do not create any M object.
> 
> I do not see that you create the M object in the case of RData...
> https://github.com/massimoaria/bibliometrix/blob/4675f9e577218413c7eb74256465ddcffef94478/inst/biblioshiny/server.R#L240-L249

When you use the save function to export an R object, it saves also the original object name. This means that when you will re-load it into R (using "load") you are not able to impose a name but it will inherit the original one.

So the strategy I adopted consists of setting a fixed name, "M", for the bibliographic data frame.

**Comment by ricber** [comment]
Oh, ok... Now it finally works 👍 Maybe write this notice somewhere, like in the FAQ on the website. Thank you for the help :)

**Comment by ricber** [comment]
> 
> 
> Also, I do not think that removing the M object from the Global Environment is the right strategy.
> 
> Uploading raw file(s) was working even if there's was an M object in the Global Environment. I suppose that when you upload raw files, biblioshiny creates a new M object somewhere else, not in the Global Environment, and that it is what it shows. So there is no reason to delete the M object in the Global Environment.
> 
> Also, if you upload a bibliometrix file, you should not search for any M object, you should just take that file as it is, I suppose. A bibliometrix file already has the M object in it...

I retract the first affirmation of this comment. Being that the program works in this way, removing the M object it's a safe preventive measure to avoid messing around with a previously created M object 👍

**Comment by mzu0009** [comment]
Hello All,
The following procedure has worked for me.
1. Download your source data from WOS in *.txt
2. Download your source data from Scopus in *.bib
3. Open biblioshiny from RStudio
4. Upload the WOS and Scopus files from import Raw Files and select the appropriate database.
5. Once uploaded, export the data via biblioshiny in excel format. Do this for both WOS and Scopus. Name each export file as WOS and Scopus
6. Open R and one by one import the WOS and Scopus data via Excel import.
7. Use this code to merge both dataframes and also remove duplicates:
combined <- mergeDbSources(SCOPUS, WOS, remove.duplicated = T)
8. Finally, export the merged data frame to an Excel file.
write.xlsx(combined, file = "biblioconsimport.xlsx")
9. Now run biblioshiny again.
10. Import the file that was exported in step 8 above. It works okay for me.
Happy bibliographic analysis folks!!!
