### ISSUE TITLE
Read .doc previously worked in Bibexcel

### ISSUE THREAD

**Issue by storopoli** [massimoaria/bibliometrix#15]
I have PhD students that need to import their clean citation data from the Bibexcel in order to Bibliometrix package to read it. I can provide a sample of text to illustrate what the Bibexcel outputs.

**Comment by massimoaria** [comment]
Please, send me the bibexcel output file.

**Comment by storopoli** [comment]
[BRUTO.txt](https://github.com/massimoaria/bibliometrix/files/2498037/BRUTO.txt)
Dear Massimo, here it is.

Its UNICODE UTF-8

This was the search expression (Scopus):

TITLE-ABS-KEY ( knowledg* )  AND  TITLE-ABS-KEY ( universit* )  AND  TITLE-ABS-KEY ( industr* )  AND  TITLE-ABS-KEY ( entrepreneur* )  AND  ( LIMIT-TO ( DOCTYPE ,  "ar " )  OR  LIMIT-TO ( DOCTYPE ,  "re " ) )  AND  ( LIMIT-TO ( PUBYEAR ,  2017 )  OR  LIMIT-TO ( PUBYEAR ,  2016 )  OR  LIMIT-TO ( PUBYEAR ,  2015 )  OR  LIMIT-TO ( PUBYEAR ,  2014 )  OR  LIMIT-TO ( PUBYEAR ,  2013 )  OR  LIMIT-TO ( PUBYEAR ,  2012 )  OR  LIMIT-TO ( PUBYEAR ,  2011 )  OR  LIMIT-TO ( PUBYEAR ,  2010 )  OR  LIMIT-TO ( PUBYEAR ,  2009 ) )  AND  ( LIMIT-TO ( LANGUAGE ,  "English " ) ) 


249 articles is the sample
Thank you!

**Comment by massimoaria** [comment]
The bibexcel codify is quite different from WoS plaintext format.
So at the moment, it is not possible to automatically import this collection into bibliometrix.
