### ISSUE TITLE
Export plot: text size is too big

### ISSUE THREAD

**Issue by ricber** [massimoaria/bibliometrix#151]
Hi, I tried the **Export plot** feature on Biblioshiny but the text size is really big and different to what is shown on Biblioshiny. I tried to export the **Annual Scientific Production** at 300 dpi.
![AnnualScientificProduction-2020-12-09(2)](https://user-images.githubusercontent.com/18362950/101651525-76792900-3a3d-11eb-84a5-70fee9bfac9e.png)

**Comment by ricber** [comment]
Does the saved image depend on the screen resolution?

**Comment by massimoaria** [comment]
Yes, it does. Unfortunately, the size of text contents in ggplot graphs depends on dpi. So I could reduce the plot title but it will be too small when exporting graphs at 75 or 150 dpi.
Anyway, I will try to find a compromise.

**Comment by ricber** [comment]
Hi Massimo,
Actually, the problem is caused by the fact that now image dimensions are not set in ggsave. Try to fix the number of dpi and save a plot with different image dimensions. Then, fix the image dimensions and save the plot with different dpi values. You'll see that in this last case, the plot elements will maintain the proportions. Indeed, if you do not specify image dimensions, ggsave defaults to those of the user's current plotting window. Thus, they are different from each user.

In my opinion, the best solution is to allow the user to modify the dpi but to set proper width and height dimensions for each plot. If users want particular width and height dimensions, they will have to build their plots through the code.

**Comment by massimoaria** [comment]
Hi Riccardo,
following your remark, I have added the user selection of plot height. Now, changing the dpi value doesn't affect the text element size.
