### ISSUE TITLE
Importing Dimensions

### ISSUE THREAD

**Issue by sdspieg** [massimoaria/bibliometrix#154]
I have a number of CSV files I exported from Dimensions for bibliometric mapping. If I feed them one by one into bibliometrics, they convert/work just fine. But if I zip them up, and try to load them as a bunch, I get a "object 'DATA' not found" error. Any thoughts on how to fix this? Thanks!

**Comment by massimoaria** [comment]
Dear Stephan,
please upload a zip file so I can try to identify the issue.
Thanks
Massimo

**Comment by sdspieg** [comment]
I shared it with you on aria@unina.it. Is that the wrong email address?

**Comment by massimoaria** [comment]
Yes, my email address is right.
I received your email with lens.org export files (CSV, ris, json) attached, but I don't find any message containing a zip file from dimensions. 
Please, send me it again.

**Comment by sdspieg** [comment]
Well I sent you an email with links to the dropbox folder with the files. 
![image](https://user-images.githubusercontent.com/691472/102217807-6948b800-3edd-11eb-898b-9a432d06eb8d.png)
Did you not receive that? I'm a bit reluctant to post the link publicly because of its size...

**Comment by massimoaria** [comment]
I have just solved the issue.

**Comment by sdspieg** [comment]
Sounds great! Should we update sthg then? The CRAN repository doesn't show any updates...

**Comment by massimoaria** [comment]
CRAN updates are scheduled quarterly.
You should install last developer version of bibliometrix from GitHub.
For more info about bibliometrix download and installation, please have a look at www.bibliometrix.org, section download.

**Comment by sdspieg** [comment]
Sorry to still add sthg here, but is it possible that the Abstract field is mismapped? It is clearly in the data as shown here 
![image](https://user-images.githubusercontent.com/691472/102422228-90e76f80-4006-11eb-8ec2-740c4962a9a3.png). But any attempt to run anything with abstracts gives an "undefined columns selected" error. 
![image](https://user-images.githubusercontent.com/691472/102422177-77debe80-4006-11eb-844b-de050eee66c3.png)

**Comment by massimoaria** [comment]
Abstract metadata has been recently added to the Dimensions CSV export file.
So when you try to import CSV Abstract data are not correctly codified.

I have solved the issue.
Please, re-install bibliometrix from GitHub and try to import your CSV one more time again.
