### ISSUE TITLE
Installing developers' version

### ISSUE THREAD

**Issue by sdspieg** [massimoaria/bibliometrix#158]
I get this problem - any ideas what went wrong? 
![image](https://user-images.githubusercontent.com/691472/102387809-21a35880-3fd1-11eb-98c7-826cab00e960.png)

**Comment by massimoaria** [comment]
It seems an issue in your R environment setting.
Try to type the command:

Sys.unsetenv("GITHUB_PAT")

**Comment by sdspieg** [comment]
That did the trick. Thanks again, Massimo!
