### ISSUE TITLE
Ideas? 

### ISSUE THREAD

**Issue by sdspieg** [massimoaria/bibliometrix#159]
Would it be possible to have a spot where users could list (and vote for?) suggestions? 
One functionality I'd like to see (and should be easy, I'd guess) is an overview of authors' collaboration over time. So the metrics you already compute for the entire set (Single-authored documents, Authors per Document, Co-Authors per Documents, and Collaboration Index), but then visualized over time in line graphs.

**Comment by massimoaria** [comment]
Please, have a look at issue #161
