### ISSUE TITLE
A spot to list suggestions, ideas, etc.  

### ISSUE THREAD

**Issue by massimoaria** [massimoaria/bibliometrix#161]
Use this post to list your suggestions, to ask for new features, to propose your ideas about how to improve bibliometrix in the feature.

There are 2 RULES you need to know before writing in this post:
1. Don't ask for ETA, it's not nice...
2. Check rule number One

Ps. ETA = "estimated time of accomplishment"

**Comment by loxavia** [comment]
I think supporting lens.org will be great,
Adding temporal trends will be great, I do them manually, and I think they can be easily implanted,

**Comment by ricber** [comment]
Here are my suggestions/ideas:
 - Implement a matching algorithm for words (especially for keywords) to solve for synonyms, acronyms, and in general, the different ways of writing the same concept
 - Implement a matching algorithm for sources' names in cited references 
 - Words by country. It would be interesting to see how topics are geographically distributed

**Comment by sdspieg** [comment]
Adding to the plot exports recommendation (which I would certainly second) - it would also be nice it it could be exported with a transparent background and as a vector (svg?) image.

**Comment by sdspieg** [comment]
Is there any way we would be able to export the 'thematic evolution' plot 

- statically (like some of the other vizzes, whereby we can specify the dpi - AND it would also be great to be able to do that in vector format AND with a transparent background); OR
- (even better) dynamically in html format?

Thanks!

**Comment by massimoaria** [comment]
> Adding to the plot exports recommendation (which I would certainly second) - it would also be nice if vizzes could be exported with a transparent background and as a vector (svg?) images.

I will think about it.

**Comment by massimoaria** [comment]
> Is there any way we would be able to export the 'thematic evolution' plot
> 
> * statically (like some of the other vizzes, whereby we can specify the dpi - AND it would also be great to be able to do that in vector format AND with a transparent background); OR
> * (even better) interactively in html format?
> 
> Thanks!

Unfortunately, Network and Sankey plots use a D3Network javascript library and it does not provide an export routine and I am not an expert in JS. At the moment it is only possible to save it through a print screen or by the export button (but with a very low resolution).

**Comment by gilienv** [comment]
Any mechanism to make Network Labels appear as Upper case words? 
The current biblioNetwork function automatically converts all my upper case terms to lower case!
Labels are often nouns and thus lower case defeats the purpose of presentation!
Thanks!

**Comment by gilienv** [comment]
I've converted the biblioNetwork output to a graph edgelist. 
 If it helps anyone else, I'm happy to share the small code

**Comment by massimoaria** [comment]
> Any mechanism to make Network Labels appear as Upper case words?
> The current biblioNetwork function automatically converts all my upper case terms to lower case!
> Labels are often nouns and thus lower case defeats the purpose of presentation!
> Thanks!

You should convert labels to upper case applying the function toupper to the node labels.
Here a short example:

# EXAMPLE 

data(scientometrics, package = "bibliometrixData")

NetMatrix <- biblioNetwork(scientometrics, analysis = "co-occurrences", 
 network = "keywords", sep = ";")

net <- networkPlot(NetMatrix, n = 30, type = "kamada", Title = "Collaboration",labelsize=0.5, verbose=FALSE) 

library(igraph)

V(net$graph)$label <- toupper(V(net$graph)$label)

plot(net$graph)

**Comment by sjgknight** [comment]
Thanks for all the work on the biblioverse. As I'm getting going and identifying issues (in my data) one thing I wonder is if it'd be possible to have a "bibcheck" function, to parse a given df for issues and identify which analyses will/not be possible.
 
At present users can run analyses with different sources, but sometimes they may be able to augment one source with parts of another, or may simple have errors they don't understand when they use bibshiny. 
A bibcheck function could help make visible what a well formed file should look like, and users could omit, amend, or adend till it is. (Understand this isn't likely to be top priority)
