### ISSUE TITLE
Parsing of multi-language names of Sources is faulted

### ISSUE THREAD

**Issue by ricber** [massimoaria/bibliometrix#162]
Hi Massimo,
There is a problem in parsing the multi-language names of sources, like journals with Chinese and English names. I noted this problem with data exported from WoS.

When you look at the data converted into a df, the problem seems of a wrong positioned comma in cited references lists. For example, I report a cited reference from the study that I've attached at the end of this issue:
> [ WU CAICONG], 2013, [, TRANSACTIONS OF THE CHINESE SOCIETY OF AGRICULTURAL MACHINERY], V44, P237

You see that the comma preceding the Source name is positioned after the square parenthesis. Thus, the bibliometric analysis algorithms read the square parenthesis as the Source name. This could seem like a problem with the exported data from WoS.

However, if you look at the raw data that I've attached below, you see the following cited reference:
> [吴才聪 Wu Caicong], 2013, [农业机械学报, Transactions of the Chinese Society of Agricultural Machinery], V44, P237

So, now it's clear what's happening. WoS has adopted the convention of reporting both the Chinese and English names of journals by writing them in square parentheses. Thus, at least when reading data exported from WoS, this should be considered since the problem is pervasive and of a great entity.
[savedrecs.txt](https://github.com/massimoaria/bibliometrix/files/5757746/savedrecs.txt)

**Comment by massimoaria** [comment]
The issue has been solved.
