### ISSUE TITLE
Most Local Cited (First) Authors

### ISSUE THREAD

**Issue by ricber** [massimoaria/bibliometrix#163]
Hi Massimo,
Why are you using the function `citations` for computing authors' local citations? I think the function `localCitations` computes more reliable counts since it considers all the documents in which an author appeared. Instead, the function `citations` considers only the documents where an author appeared as the first author. Am I right?
I propose to substitute the function `citations` with `localCitations` or change the name on Biblioshiny from **Most Local Cited Authors** to **Most Local Cited First Authors**, otherwise it is misleading.

https://github.com/massimoaria/bibliometrix/blob/597933db51a4029e5cfe30dfd11e3efdf946af8d/inst/biblioshiny/server.R#L4010-L4012

**Comment by massimoaria** [comment]
Dear Riccardo, 
following your remark, I substituted the function citations with localCitations in server.R to calculate Most Local Cited Authors
