### ISSUE TITLE
Networks plots on Biblioshiny do not update number of nodes

### ISSUE THREAD

**Issue by ricber** [massimoaria/bibliometrix#164]
Hi Massimo,
There is a problem with the networks plots on Biblioshiny. Try to plot a Collaboration Network with a certain number of nodes N1. Then try to change just the number of nodes (N2) and click again on "Apply". If N2 < N1, then the plot will actually show again N1 nodes. If N2 > N1, then the plot will show N2 nodes but N1 labels.

**Comment by massimoaria** [comment]
The issue comes from your commit added to solve issue #149. Moving the argument n from networkPlot to cocMatrix produces that issue.
I have just solved it.

**Comment by ricber** [comment]
Is it solved or not? Maybe you can try to give the parameter `n` again to the `networkPlot` function. It would be redundant, but maybe it solves the problem.

**Comment by massimoaria** [comment]
It is solved

**Comment by massimoaria** [comment]
@
