### ISSUE TITLE
error in convert2df introduced in version 3.0

### ISSUE THREAD

**Issue by jimiadams** [massimoaria/bibliometrix#165]
I have a data processing error that is new in the latest version that I have not encountered before (on the same datafiles), and the error message is not detailed enough to know how to fix it. In a convert2df call, for wos plaintext data, I am getting the following (which halts processing of the file):
Generating affiliation field tag AU_UN from C1:  Error in AFF[indna] <- M$RP[indna] : replacement has length zero

Any help appreciated.

**Comment by massimoaria** [comment]
Please upload your code and file.

**Comment by jimiadams** [comment]
df <- convert2df("savedrecs.txt", dbsource = "wos", format = "plaintext")

[savedrecs.txt](https://github.com/massimoaria/bibliometrix/files/5821997/savedrecs.txt)

**Comment by massimoaria** [comment]
The error is related to missing some mandatory metadata fields in your file (i.e. CR, C1, RP).
From version 3.0, bibliometrix checks for missing fields and returns a warning. 

When you download an export file from WoS, please select "Full Record and Citation Info" in "Record Content" menu

![image](https://user-images.githubusercontent.com/16023543/104921891-4016be00-599a-11eb-9fe6-d4396a0ecedc.png)

**Comment by jimiadams** [comment]
I am exporting the full record and CR. Some records just don't have some fields. C1 in particular is missing quite often. You're requiring fields that ISI does not.

**Comment by takan13** [comment]
Sir,
Using this file I am trying to perform bibliometrix analysis. This is a bib file. but showing error "Converting your isi collection into a bibliographic dataframe

Error in file(con, "r") : cannot open the connection
> 

pls help me to overcome the issue.

[marissmo.docx](https://github.com/massimoaria/bibliometrix/files/6449811/marissmo.docx)

**Comment by massimoaria** [comment]
Please, read carefully our tutorials and FAQs.
Your bib entries miss some mandatory metadata such as Author's affiliations, Countries, etc.

**Comment by takan13** [comment]
![bibshiny](https://user-images.githubusercontent.com/83940540/117614745-6600e200-b186-11eb-9daf-f2344ea62ecd.jpg)

Sir/Madam
in Biblioshiny getting this kind of image. So not able to read. Please help

**Comment by takan13** [comment]
> Please, read carefully our tutorials and FAQs.
> Your bib entries miss some mandatory metadata such as Author's affiliations, Countries, etc.

I followed http://web.mit.edu/rsi/www/pdfs/bibtex-format.pdf

**Comment by massimoaria** [comment]
> ![bibshiny](https://user-images.githubusercontent.com/83940540/117614745-6600e200-b186-11eb-9daf-f2344ea62ecd.jpg)
> 
> Sir/Madam
> in Biblioshiny getting this kind of image. So not able to read. Please help

Please read Faq Q15 at https://bibliometrix.org/faq.html
