### ISSUE TITLE
version 3.0 is checking for fields that aren't mandatory.

### ISSUE THREAD

**Issue by jimiadams** [massimoaria/bibliometrix#167]
In your response to my previous issue (pasted below), you noted that version 3.0 and greater is checking for "mandatory" fields. Unfortunately, some of those fields are not mandatory (C1/RP in particular), even when downloading the full record from ISI.  By putting in this constraint, it's making some complete records not able to be processed.

Response:
The error is related to missing some mandatory metadata fields in your file (i.e. CR, C1, RP).
From version 3.0, bibliometrix checks for missing fields and returns a warning. 

When you download an export file from WoS, please select "Full Record and Citation Info" in "Record Content" menu

![image](https://user-images.githubusercontent.com/16023543/104921891-4016be00-599a-11eb-9fe6-d4396a0ecedc.png)

_Originally posted by @massimoaria in https://github.com/massimoaria/bibliometrix/issues/165#issuecomment-762254508_

**Comment by massimoaria** [comment]
C1/Rp are mandatory filed because they are necessary to perform many analyses (i.e. affiliation, country descriptive analyses, and social structures).
However, convert2df returns a warning about missing fields and not an error. You can also import your file and use bibliometrix/biblioshiny and perform all the analyses not requiring that fields.

**Comment by jimiadams** [comment]
There are also many analyses (both those available in the package, and ones that are self code-able with these data) for which those fields are not necessary. Placing a hard-check on those fields seems overly restrictive.

As noted in the other thread, it throws an error (not a warning) and halts any further processing. I've tried it in both the standard package and the shiny version. The suggestion that it's only a warning is not consistent with the actual behavior.

I've gotten things to read by reverting to an old version of the package that doesn't have this restriction, so I'm set for now. But I'm unclear why the package would *require* things that ISI does not universally provide. It just adds a hurdle to use that may or may not impact intended analyses, restricting the utility of the package.

**Comment by massimoaria** [comment]
Please, upload the wos export file that returns you an error with convert2df.

**Comment by jimiadams** [comment]
As I said in the thread you closed, the file here - 
https://github.com/massimoaria/bibliometrix/files/5821997/savedrecs.txt
using this code:
df <- convert2df("savedrecs.txt", dbsource = "wos", format = "plaintext")
generates this error:
Generating affiliation field tag AU_UN from C1: Error in AFF[indna] <- M$RP[indna] : replacement has length zero

**Comment by massimoaria** [comment]
Maybe, you are using an old version of bibliometrix.
The last version available on Github (and just published also on CRAN), importing your file, does not report an error but just a warning about some missing metadata:

![image](https://user-images.githubusercontent.com/16023543/105149577-f813aa80-5b03-11eb-8a6f-40163e0760f1.png)

Please update bibliometrix and try again.
