### ISSUE TITLE
labelsize issue in dendrogram of conceptualStructure()

### ISSUE THREAD

**Issue by Sargaleano** [massimoaria/bibliometrix#168]
Hi, guys! Awesome work, congrats! I am using bibliometrix to perform scientific visualization of research production at my graduate school, and I have found it really useful.

I would like to report a easy-to-fix bug, though. When using `conceptualStructure()` the parameter `labelsize` modifies the size of labels in the topic map obtained by the MCA algorithm, but it does not change the size of the labels on the dendrogram plot. I think the problem is that in the source code you are invoking:
 
`fviz_dend(km.res, rect=TRUE, k=clust, labelsize=labelsize, main="Topic Dendrogram", k_colors=cbPalette[clust:1])`

but this function does not accept a `labelsize` parameter but a `cex` parameter to change the size of the label. Thus, I think the above line should read:

`fviz_dend(km.res, rect=TRUE, k=clust, cex=labelsize, main="Topic Dendrogram", k_colors=cbPalette[clust:1])`

Notice this is not the case for the `fviz_cluster()` function used to plot the MCA topic map, as this one indeed, accept a `labelsize` parameter.

Thank you again, and please let me know if this issue and suggested fix makes sense to you.

**Comment by massimoaria** [comment]
Thanks for bug identifying. 

I solved the issue modifying your suggestion dividing labelsize by 20:
 
fviz_dend(km.res, rect=TRUE, k=clust, cex=labelsize/20, main="Topic Dendrogram", k_colors=cbPalette[clust:1])

because the argument "cex" takes as input a proportion instead of an integer number (i.e. cex=0.8 means 80% of max labelsize)

**Comment by Sargaleano** [comment]
Great, Massimo!
Thanks,
-- SergioA.
