### ISSUE TITLE
Is there a way to change the cluster colours in networkplot()? 

### ISSUE THREAD

**Issue by mojohealy** [massimoaria/bibliometrix#169]
Hi there, thanks for the marvellous package. 

I'm curious if there's a way I can manually change the colours of the clusters in network plots. I am comparing the intellectual structure of the Bradford zone 1 articles in my data set, with that of zones 2 and 3, so I have produced a co-citation network plot for each. 

In the first plot, a certain cluster is the largest, and therefore coloured red. In the second plot, a cluster showing the same theme is smaller, and so coloured green. I'd like to make the colours of the plots consistent to allow for easier comparison. 

I know I can use net2VOSviewer to launch the plots in VOSviewer and change the colours manually, but I'm hoping for a solution that I can implement in my R markdown file.

**Comment by massimoaria** [comment]
Node colors are stored in the attribute color of each node item of the object "igraph".

You can directly modify node and edge colors changing their color attribute:

data(management, package = "bibliometrixData")

NetMatrix <- biblioNetwork(management, analysis = "co-occurrences", 
                           network = "keywords", sep = ";")

net <- networkPlot(NetMatrix, n = 30, type = "auto", Title = "Co-occurrence Network",labelsize=1) 

library(igraph)

V(net$graph)$color
E(net$graph)$color

**Comment by mojohealy** [comment]
Thanks Massimo, I appreciate your help.
