### ISSUE TITLE
Error Importing wos 5k

### ISSUE THREAD

**Issue by crestre** [massimoaria/bibliometrix#171]
I run a search in wos that resulted in ~ 6,000 records. Because the volume, I used the export function 5k that allows the user to export up to 5000 records. I have used the command shown below but I get an error message

M <- convert2df(file="savedrecs.txt", dbsource = "wos", format = "plaintext")

Converting your wos collection into a bibliographic dataframe

Error in rep(1:nP, rowPapers) : invalid 'times' argument

I would greatly appreciate your help.  File used appears below

[savedrecs_2001_1983.txt.zip](https://github.com/massimoaria/bibliometrix/files/5999705/savedrecs_2001_1983.txt.zip)

**Comment by massimoaria** [comment]
The WoS option Fast 5k is not compatible with bibliometrix because many mandatory metadata are not included in the export file. 
You have to export multiple files (500 records for file) and read them with convert2df.
