### ISSUE TITLE
unintelligible error in biblioNetwork

### ISSUE THREAD

**Issue by jimiadams** [massimoaria/bibliometrix#172]
I've traditionally used this package only to process data, but am trying some more of its functions, unsuccessfully. In trying to use the biblioNetwork function, I am getting an error that I can't make heads or tails of. 

Error in dimnamesGets(x, value) : 
  invalid dimnames given for “dgCMatrix” object

I've tried this on a range of dataframes, getting the same error on all of them. The attached is a sample from one of those, using the seemingly basic call - 

n <- biblioNetwork(t1, analysis="coupling", network="references")

[sampled.Rdata.zip](https://github.com/massimoaria/bibliometrix/files/6011767/sampled.Rdata.zip)

The above covers the question, but here are some more details. 
- First I tried it just on the imported datafile directly. That didn't work, so I then tried reducing it to just those records with CRs (this is the nature of the sample attached), guessing that maybe it was struggling to name rows for non-existent citations. That still threw the same error.
- So then I wondered if there were data processing problems before getting to that point. So I tried some of the basic summary functions (e.g., biblioAnalysis). But those work fine on these files, so it doesn't seem to be that.

**Comment by massimoaria** [comment]
Maybe something went wrong when you imported your data.
The function seams not to be able to short the reference lables.

Setting the argument shortlabel=FALSE, the function biblioNetworks works fine:

n <- biblioNetwork(t1, analysis="coupling", network="references", shortlabel = FALSE)
