### ISSUE TITLE
Missing fields:  AU DE ID C1 CR  Warning: Error in data.frame: arguments imply differing number of rows: 0, 197

### ISSUE THREAD

**Issue by azhermehdi** [massimoaria/bibliometrix#173]
I  am not able find out what is wrong with the file. it seems like the App is lacking something. Tried .bib, text, files from Wos/Wok and scopus.

> runApp('R/win-library/4.0/bibliometrix/biblioshiny')

Listening on http://127.0.0.1:7549

Converting your scopus collection into a bibliographic dataframe

Warning:
In your file, some mandatory metadata are missing. Bibliometrix functions may not work properly!

Please, take a look at the vignettes:
- 'Data Importing and Converting' (https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html)
- 'A brief introduction to bibliometrix' (https://www.bibliometrix.org/vignettes/Introduction_to_bibliometrix.html)

Missing fields:  AU DE ID C1 CR 
Warning: Error in data.frame: arguments imply differing number of rows: 0, 197
  157: stop
  156: data.frame
  155: cbind
  154: cbind
  153: bib2df
  152: convert2df
  148: eventReactiveValueFunc [C:\Users\SyEd\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#140]
  104: DATAloading
  103: exprFunc [C:\Users\SyEd\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#282]
  102: widgetFunc
  101: htmlwidgets::shinyRenderWidget
  100: func
   87: renderFunc
   86: renderFunc
   82: renderFunc
   81: output$contents
    1: runApp

**Comment by massimoaria** [comment]
Please, upload the files you are trying to use.

**Comment by azhermehdi** [comment]
[My Collection.zip](https://github.com/massimoaria/bibliometrix/files/6213527/My.Collection.zip)

**Comment by massimoaria** [comment]
Your file misses many mandatory metadata such as references, author's affiliations, etc.

Please have a look at our tutorial about 'Data Importing and Converting' (https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html)
