### ISSUE TITLE
The imported text is convert to upper case  

### ISSUE THREAD

**Issue by LucjanJanowski** [massimoaria/bibliometrix#175]
When I use convert2df function the imported fields are converted to upper case. It is especially problematic for titles and abstracts where a term/world can change its meaning depending on the capitalization.

**Comment by massimoaria** [comment]
This is not an issue. Text normalization is a standard step in pre-processing data before performing text analysis.
I understand your point but changing this approach would mean having to rewrite most of the functions.

You could modify the convert2df function by removing the row that includes the toupper() command.

**Comment by LucjanJanowski** [comment]
Thank you for the answer.
