### ISSUE TITLE
Parsing issue with the co-citation network?

### ISSUE THREAD

**Issue by nicolarighetti** [massimoaria/bibliometrix#179]
Hi, I noticed that the co-citation network (I am working with Scopus and WoS data) includes also some nodes not corresponding to authors, but to casual text in the references. From an overview of the data, I suspect that the issue could be due to a parsing problem with the structure of some of the references, which misleads the parsing algorithm used to extract the authors (through the separator specified in the function. I have used ";"). Is there a solution or a workaround to avoid this problem? Thank you!

**Comment by massimoaria** [comment]
Please upload an example file and your code
