### ISSUE TITLE
Extraction of metadata of citations from Web Of Science

### ISSUE THREAD

**Issue by chandryou** [massimoaria/bibliometrix#18]
I'm trying to extract citation data of clinical guidelines (currently focusing on American and European hypertension guidelines) from Web Of Science. 
I found that I couldn't extract whole citations of the guideline (WoS showed 615 citations, but only metadata from about 500 articles can be extracted). It is not a problem of this package, but is their anyone who have an experience like this?

**Comment by massimoaria** [comment]
As explained in the bibliometrix tutorial, WoS does not allow to download more than 500 records at time.
You can download two files:
1) select from record 1 to 500 for the first one, then download it;
2) select from record 501 to 615 for the second one and then download it.

To import the two files in bibliometrix, please use the function readFiles:
D<-readfiles("filename1.txt",filenames.txt")

Another way to import the two files in bibliometrix is to use biblioshiny app (included in bibliometrix package).
You only need to put the two WoS files into a zip file and later read it by using the loading page of biblioshiny app.

**Comment by chandryou** [comment]
Thank you @massimoaria for answering this thread.
I'd tried the exact way you explained. But I'd got only about 550 records. I didn't figure out why...
