### ISSUE TITLE
I can't seem to use Scopus .csv files: "replacement has 0 rows, data has x"

### ISSUE THREAD

**Issue by christiannolting** [massimoaria/bibliometrix#180]
Hi, 
I was using .csv files I exported from Scopus last year without a problem, but now it throws the following error message. 

Warning: Error in $<-.data.frame: replacement has 0 rows, data has 576
  157: stop
  156: $<-.data.frame
  154: csvScopus2df
  153: convert2df
  149: eventReactiveValueFunc [C:\Users\username\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#132]
  105: DATAloading
  104: exprFunc [C:\Users\username\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#282]
  103: widgetFunc
  102: htmlwidgets::shinyRenderWidget
  101: func
   88: renderFunc
   87: renderFunc
   83: renderFunc
   82: output$contents
    2: runApp
    1: biblioshiny

It works fine with a .bib file. 
I've attached a zip file with the .csv file and the .bib file. 
[scopus.zip](https://github.com/massimoaria/bibliometrix/files/6202545/scopus.zip)

Hope you can help.
Kind regards, 
Christian

**Comment by massimoaria** [comment]
> Hi,
> I was using .csv files I exported from Scopus last year without a problem, but now it throws the following error message.
> 
> Warning: Error in $<-.data.frame: replacement has 0 rows, data has 576
> 157: stop
> 156: $<-.data.frame
> 154: csvScopus2df
> 153: convert2df
> 149: eventReactiveValueFunc [C:\Users\username\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#132]
> 105: DATAloading
> 104: exprFunc [C:\Users\username\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#282]
> 103: widgetFunc
> 102: htmlwidgets::shinyRenderWidget
> 101: func
> 88: renderFunc
> 87: renderFunc
> 83: renderFunc
> 82: output$contents
> 2: runApp
> 1: biblioshiny
> 
> It works fine with a .bib file.
> I've attached a zip file with the .csv file and the .bib file.
> [scopus.zip](https://github.com/massimoaria/bibliometrix/files/6202545/scopus.zip)
> 
> Hope you can help.
> Kind regards,
> Christian

Please update your Scopus csv file.

**Comment by massimoaria** [comment]
> Hi,
> I was using .csv files I exported from Scopus last year without a problem, but now it throws the following error message.
> 
> Warning: Error in $<-.data.frame: replacement has 0 rows, data has 576
> 157: stop
> 156: $<-.data.frame
> 154: csvScopus2df
> 153: convert2df
> 149: eventReactiveValueFunc [C:\Users\username\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#132]
> 105: DATAloading
> 104: exprFunc [C:\Users\username\Documents\R\win-library\4.0\bibliometrix\biblioshiny/server.R#282]
> 103: widgetFunc
> 102: htmlwidgets::shinyRenderWidget
> 101: func
> 88: renderFunc
> 87: renderFunc
> 83: renderFunc
> 82: output$contents
> 2: runApp
> 1: biblioshiny
> 
> It works fine with a .bib file.
> I've attached a zip file with the .csv file and the .bib file.
> [scopus.zip](https://github.com/massimoaria/bibliometrix/files/6202545/scopus.zip)
> 
> Hope you can help.
> Kind regards,
> Christian

Dear Christian
your CSV file works fine on my pc.
![image](https://user-images.githubusercontent.com/16023543/112959762-0c97a300-9144-11eb-9cab-4cfcac09d6bb.png)

Please, try to install bibliometrix last version from github.

**Comment by rimchang21** [comment]
Hello..
The same problem, I have found using the OpenAlex database in RStudio. While uploading the data into the software, it showed the following issue:

Error: replacement has 0 rows, data has 1

Can you please help me resolve this
