### ISSUE TITLE
 function readFiles has been dropped

### ISSUE THREAD

**Issue by hydrylcn** [massimoaria/bibliometrix#181]
hello there,
when i try to add new raw data into the Bibliometrix it says; From version 3.0.0, the function readFiles has been dropped.
Please use the function 'convert2df' to import and convert your export files> 
how can i solve this problem?

**Comment by massimoaria** [comment]
Please have a look at our tutorial https://www.bibliometrix.org/vignettes/Introduction_to_bibliometrix.html

Here an example extracted from it:

Data loading and converting
The export file can be read and converted using by R using the function convert2df:

convert2df(file, dbsource, format)

The argument file is a character vector containing the name of export files downloaded from SCOPUS, Clarivate Analytics WOS, Digital Science Dimenions, Lens, PubMed, or Cochrane CDSR website. file can also contain the name of a JSON/XML object download using Digital Science Dimensions or PubMed APIs (through the packages dimensionsR and pubmedR.

es. file <- c(“file1.txt”,“file2.txt”, …)

file <- "https://www.bibliometrix.org/datasets/savedrecs.bib"

M <- convert2df(file = file, dbsource = "wos", format = "bibtex")
## 
## Converting your wos collection into a bibliographic dataframe
## 
## Done!
## 
## 
## Generating affiliation field tag AU_UN from C1:  Done!

**Comment by hydrylcn** [comment]
Hello Massimoaria,
thank you for your quick response
cheers
