### ISSUE TITLE
I can't open neither .csv and .bib files from Scopus, and WOS as well

### ISSUE THREAD

**Issue by martinhobotelho** [massimoaria/bibliometrix#182]
Hi, everybody.

Since 2020 October, biblioshiny web interface was working here, and I worked a lot with scienciemetrics.

However since last month (2021 March), **it is not working here with my old .bib and .csv files.**

I was thinking the problem was the file, so I did another one on Scopus and WOS database. However, **same error message still appears for me**.

Do someone have some tips?

That is the file.

congrats,

Martinho

**Comment by martinhobotelho** [comment]
This is the database.... Scopus..

https://www.dropbox.com/sh/bv4gwd3zw6vcmi5/AACXyqAN204yPLeDyyeicTF7a?dl=0

**Comment by massimoaria** [comment]
Please update bibliometrix from GitHub and upload a screenshot of the error you are facing.
I tried to import your bib file and all works fine on my pc.
![image](https://user-images.githubusercontent.com/16023543/114540607-07634980-9c56-11eb-933a-48ecd5ddc09f.png)
