### ISSUE TITLE
Histnetwork matrix is not the same dimensions as the input dataframe

### ISSUE THREAD

**Issue by vinodhinir** [massimoaria/bibliometrix#186]
I have a list of 168 papers from Scopus on which I am planning to do a citation analysis.
I want to perform a direct citation analysis for the 168 papers , hence i tried to create a histnetwork .
Somehow the netmatrix generated by the histnetwork function is bringing down the number of papers to 105.

Below is the code snippet and a screenshot of the resultant matrix

df_scopus<- convert2df("plat.bib", dbsource = "scopus", format = "bibtex")
H=histNetwork(df_scopus, sep=";", network=TRUE, verbose = TRUE,min.citations = 0)
<img width="701" alt="Screenshot 2021-04-16 at 12 38 38 PM" src="https://user-images.githubusercontent.com/20552585/114985654-adaa8b80-9eb0-11eb-9f88-da5d9976fcb0.png">

Can @massimoaria help me understand the issue here . 
I have tried debugging and verified that my DI and CR columns dont have any nulls/NA's and the separator is ;

**Comment by massimoaria** [comment]
The function histNetwork does not report articles that are not cited by any other article of the collection.
