### ISSUE TITLE
Change Case in 'Labels' for all Networks?

### ISSUE THREAD

**Issue by gilienv** [massimoaria/bibliometrix#189]
I'm using Bibliometrix Verion 3.0.4 on R vesion 4.0.2

All instances of using 'biblioNetwork' converts the elements to lower case words - that appear as lower case labels in all network plots! 
This is difficult to justify in a paper or report or presentation as most of the elements are actually Nouns and should be retained as Caps - this is true for author names, Journals titles, ketwords etc..

Even if I manually convert all lower case terms back to upper case - the plot STILL shows lower case!

I think this is a bug in the newer version, coz the Documentation webpage (updated 2018) shows all Figures and Plots with perfect upper case labels in all figures, just as I would wish mine to be! 
See page: https://bibliometrix.org/documents/bibliometrix_Report.html

Any help greatly apreciated!

**Comment by massimoaria** [comment]
You should convert labels to upper case applying the function toupper to the node labels.
Here a short example:

EXAMPLE
data(scientometrics, package = "bibliometrixData")

NetMatrix <- biblioNetwork(scientometrics, analysis = "co-occurrences",
network = "keywords", sep = ";")

net <- networkPlot(NetMatrix, n = 30, type = "kamada", Title = "Collaboration",labelsize=0.5, verbose=FALSE)

library(igraph)

V(net$graph)$label <- toupper(V(net$graph)$label)

plot(net$graph)

**Comment by gilienv** [comment]
Awesome!!!! Much indebted :)
