### ISSUE TITLE
problem with networkStat summary

### ISSUE THREAD

**Issue by maxdtl** [massimoaria/bibliometrix#190]
Hello

I am using bibliometrix on a scopus db extracted from the request "franc CFA" on scopus. 
I encounter a problem when I try to calculate the statistics of my co-citation network. The command summary(netstat) only gives me statistics for the whole network but not for vertex.

Here are my outputs : 

#reseau de co-citation des auteurs
> corpus_scopus = metaTagExtraction(corpus_scopus,"CR_AU",sep=";")
> co_cit_aut <- biblioNetwork(corpus_scopus, analysis = "co-citation", network = "authors", sep = ";")
> co_cit_aut_net <- networkPlot(co_cit_aut, n=50, Title = "Reseau de co-citation des auteurs", type = "fruchterman", size.cex=TRUE, remove.multiple=FALSE, labelsize=0.7)
> #net2VOSviewer(co_cit_aut_net, vos.path = "C:/Users/maxen/Documents/VOSviewer/other_system")
> 
> netstat_co_cit_aut <- networkStat(co_cit_aut)
> summary(netstat_co_cit_aut, k=10)

Main statistics about the network

 Size                                  2912 
 Density                               0.027 
 Transitivity                          0.591 
 Diameter                              5 
 Degree Centralization                 0.343 
 Average path length                   2.458 
 

> summary(netstat_co_cit_aut$vertex)

   Mode    NA's 
logical       1 

If someone knows what's the problem...

Thank you very much !

**Comment by massimoaria** [comment]
Please update your collection

**Comment by maxdtl** [comment]
Same as on the other post : 
This is a .bib file => the github tells me that it can't be uploaded. But I could send it to you by e-mail? Or CSV (does it change something in the script ?) ?

Thank you very much for your answer !

**Comment by massimoaria** [comment]
Here the right code to obtain vertex centrality (centrality measure is selected by the argument "type"):

library(bibliometrix)

file="scopus.csv"

corpus_scopus <- convert2df(file,"scopus","csv")

corpus_scopus <- metaTagExtraction(corpus_scopus,"CR_AU",sep=";")
co_cit_aut <- biblioNetwork(corpus_scopus, analysis = "co-citation", network = "authors", sep = ";")
co_cit_aut_net <- networkPlot(co_cit_aut, n=50, Title = "Reseau de co-citation des auteurs", type = "fruchterman", size.cex=TRUE, remove.multiple=FALSE, labelsize=0.7)

netstat_co_cit_aut <- networkStat(co_cit_aut, stat = "all", type = "degree")

summary(netstat_co_cit_aut, k=10)

summary(netstat_co_cit_aut$vertex$vertexCentrDegree)
