### ISSUE TITLE
Problem with biblioNetwork on "co-citation" network with "sources" 

### ISSUE THREAD

**Issue by maxdtl** [massimoaria/bibliometrix#191]
Hello

I have a problem when I try to make a co-citations network on "sources" : "Error in strsplit(M[, Field], sep) : l'argument n'est pas une chaîne de caractères"

Even when after having converted the data into character I have the same error.

#reseau de co-citation des revues
> class(corpus_scopus$CR_SO)
[1] "list"
> corpus_scopus$CR_SO = as.character(corpus_scopus$CR_SO)
> class(corpus_scopus$CR_SO)
[1] "character"
> 
> corpus_scopus = metaTagExtraction(corpus_scopus, Field = "CR_SO", sep = ";")
> co_cit_revues <- biblioNetwork(corpus_scopus, analysis = "co-citation", network = "sources", sep = ";")
Error in strsplit(M[, Field], sep) : 
  l'argument n'est pas une chaîne de caractères

If someone can help me with it ! Thank you !!

**Comment by massimoaria** [comment]
Please upload your collection

**Comment by maxdtl** [comment]
This is a .bib file => the github tells me that it can't be uploaded. But I could send it to you by e-mail? Or CSV (does it change something in the script ?) ?

**Comment by massimoaria** [comment]
The issue has been solved.

Please upload bibliometrix from GitHub.
