### ISSUE TITLE
Problem converting with 'plaintext' file

### ISSUE THREAD

**Issue by luizecol** [massimoaria/bibliometrix#193]
Hello, friends. 

I'm having problem with convert2df function when my file is .txt (plaintext). 

The problem is as follow: Error in rep(1:nP, rowPapers) : invalide 'times' argument 

Does someone know how I can solve this problem? 

Thanks in advance

**Comment by massimoaria** [comment]
Please upload your file and code and provide the following info:
- your R version
- Bibliometrix version you are using

**Comment by luizecol** [comment]
Hi, friend! 

My Rstudio version is ‘1.4.1106’ 
My Bibliometrix version is ‘3.1.1’ 

My file is as follow: 
[asre.txt](https://github.com/massimoaria/bibliometrix/files/6501293/asre.txt)

**Comment by massimoaria** [comment]
Your file format is not correct. Bibliometrix reads "plaintext" txt format downloaded from WoS.
Please read carefully our tutorial "how to import and convert data" at the following link:
https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html

**Comment by luizecol** [comment]
Hi, I downloaded just exactly as said so by the tutorial. I first select export other formats >> complete register and references >> tab-separated text (plaintext). Am I doing anything wrong? 

Thanks again

**Comment by massimoaria** [comment]
You have to select "other file formats" and then "plaintext"
