### ISSUE TITLE
An error has occurred! - Can't FIND the function "withSpinner"

### ISSUE THREAD

**Issue by manobacon** [massimoaria/bibliometrix#194]
When I type "biblioshiny()" an error occurs as you can see in the following image.
![Capturar](https://user-images.githubusercontent.com/13083210/118660323-75a2ab00-b7c4-11eb-82ac-e739d76aceb0.PNG)

**Comment by massimoaria** [comment]
Please update bibliometrix from github:
devtools::install_github("massimoaria/bibliometrix")

or alternatively, load shinycssloaders library before launching biblioshiny:
library(shinycssloaders)
biblioshiny()
