### ISSUE TITLE
error while convert WOS data for bibliometrix

### ISSUE THREAD

**Issue by diwahar28** [massimoaria/bibliometrix#195]
When i run the code to convert2df(file, dbsource = "wos", format = "plaintext")
the outcome is Error in rep(1:nP, rowPapers)
[full comp - for use.txt](https://github.com/massimoaria/bibliometrix/files/6541915/full.comp.-.for.use.txt)
[lastsave.txt](https://github.com/massimoaria/bibliometrix/files/6541919/lastsave.txt)

**Comment by massimoaria** [comment]
Bibliometrix supports Endnote Desktop, Bibtex and Plaintext WOS export file formats.
Your txt file is a tab delimited and not a plaintext.

Please use convert2df with one of the supported file formats
You can read more about data loading and converting at this link: 
https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html
