### ISSUE TITLE
Error during converting data from Scopus

### ISSUE THREAD

**Issue by simovat** [massimoaria/bibliometrix#197]
Hello, 
I have problem with converting scopus collection into a dataframe. I have instaled the devtools version of bibliometrix, but still I reciving this error. Could you help me please?  [Here](https://czuvpraze-my.sharepoint.com/:x:/g/personal/simovat_lib_czu_cz/Ed2UA61FIHxMnIc942FryQEBV9YXDxDUJo_FCFXsxriCfw?e=ofiskd) I also sending file with references from scopus, maybe there is something wrong?

WOS files works without problems.

Thank you in advance :)

`> M <- convert2df(file, dbsource = "scopus", format = "csv")

Converting your scopus collection into a bibliographic dataframe

Error in `$<-.data.frame`(`*tmp*`, "J9", value = character(0)) : 
  replacement has 0 rows, data has 1409`

**Comment by massimoaria** [comment]
Sorry, but I cannot open the CSV file. Please upload it.

**Comment by simovat** [comment]
Hello, thanks for information. Here is the file, hope it gonna work :)
Thank you 

[scopus_2021.xlsx](https://github.com/massimoaria/bibliometrix/files/6590061/scopus_2021.xlsx)

**Comment by simovat** [comment]
Hello, after a long time, I had time to encode again for a while and I found out that I had incorrectly downloaded the data from Scopus - I did not choose to download all the data. That's why it didn't work. I apologize for the complications.
