### ISSUE TITLE
Issue to install and run library

### ISSUE THREAD

**Issue by GiridharBojja** [massimoaria/bibliometrix#198]
Hello, I tried to install both the developer version and the stable version. It downloads the dependencies and when I run library('bibliometrix') it says Error in library("bibliometrix") :  there is no package called ‘bibliometrix’ ? Any idea on what's wrong?

**Comment by massimoaria** [comment]
Please, upload a screenshot of your console

**Comment by GiridharBojja** [comment]
Hello Aria,

Thanks for getting back to me. I have uninstalled both R and R studio, and install it back. Now it works fine. You can close the case.

Thanks,

Giridhar Reddy Bojja
Doctoral Student & Research Assistant
Dakota State University
***@***.*** | Phone: (605) 953-9000
________________________________
