### ISSUE TITLE
Articles associated to clusters from co-citation analysis

### ISSUE THREAD

**Issue by guillermo-orjuela** [massimoaria/bibliometrix#199]
Hi.
I run a co-citation analysis using the references from my database and I identified 5 clusters with the networkPlot function. 
My question is how can I know which articles from my database are associated to each cluster?
How can I create a dataframe with a column with the cluster number and another column with the articles names of each cluster.
Thank you!

**Comment by Biabiatiz** [comment]
Hi, Guillermo.

I hope this finds you well. 
I don't know if you are still with the doubt, but perhaps to share what I have done would be useful somehow.

For example:
net <- networkPlot(NetMatrix, n = 30, type = "auto", Title = "Co-occurrence Network",labelsize=1) 

doc = net[["cluster_res"]][["vertex"]] 
cluster = net[["cluster_res"]][["cluster"]]
  
doc = as.data.frame(doc)
cluster = as.data.frame(cluster)
clusters <- bind_cols(doc,cluster)  

In object "clusters" you will have a dataframe with the articles and related clusters.

All the best,
