### ISSUE TITLE
networkPlot warning for Vosviewer

### ISSUE THREAD

**Issue by baqrie** [massimoaria/bibliometrix#20]
Hi,

I try:
```
NetMatrix <- biblioNetwork(M, analysis = "co-citation", network = "references", sep = ".  ") 
net=networkPlot(NetMatrix, n = 30, Title = "Co-Citation Network", type = "vosviewer", size=T, remove.multiple=FALSE, labelsize=0.7,edgesize = 5) 
```

from the documentation (just modify the plot type to vosviewer) and got this error:
```
Error in networkPlot(NetMatrix, n = 30, Title = "Co-Citation Network",  : 
  object 'net_groups' not found
```

Also, in a computer the vosviewer is executed (even with that warning) but not in another computer.
How to solve this issue?

**Comment by massimoaria** [comment]
Are you using the last version of bibliometrix?




Ottieni Outlook per Android







On Mon, Oct 29, 2018 at 4:00 AM +0100, "baqrie" <notifications@github.com> wrote:












Hi,


I try:
NetMatrix <- biblioNetwork(M, analysis = "co-citation", network = "references", sep = ".  ") 
net=networkPlot(NetMatrix, n = 30, Title = "Co-Citation Network", type = "vosviewer", size=T, remove.multiple=FALSE, labelsize=0.7,edgesize = 5) 



from the documentation (just modify the plot type to vosviewer) and got this error:
Error in networkPlot(NetMatrix, n = 30, Title = "Co-Citation Network",  : 
  object 'net_groups' not found



Also, in a computer the vosviewer is executed (even with that warning) but not in another computer.

How to solve this issue?

**Comment by baqrie** [comment]
I tried with 2.0.1 (from R package menu) and 2.0.2 (from github)

**Comment by massimoaria** [comment]
I have just solved the warning about net_groups.
To use vosviewer to visualize the network, you have to declare the path where vosviewer.jar software (java version) is located.
To do that you have to use the vos.path argument in networkPlot.
