### ISSUE TITLE
Issues in termExtraction

### ISSUE THREAD

**Issue by yuyllove** [massimoaria/bibliometrix#200]
Hi Aria,

Thank you for nice work!

The new termExtraction function has new parameter "ngrams". This parameter is from unnest_tokens in tidytext package. When I want to cleaning DE or ID, the new termExtraction function would broke the original phrases. In addition, the en dash hyphen "-" will be deleted using unnest_tokens function, consequently, the parameter "keep.terms" does not work.

**Comment by massimoaria** [comment]
The issue were solved.
