### ISSUE TITLE
thematicEvolution() error: Network matrix is empty! The analysis cannot be performed

### ISSUE THREAD

**Issue by mojohealy** [massimoaria/bibliometrix#202]
Thanks, as always, for your work in providing this tool. 

I'm trying to run a thematic evolution of the attached WoS data set, but get the error "Network matrix is empty! The analysis cannot be performed". 

`thematicEvolution(data,
  field = "ID",
  years = years,
  n = 250,
  minFreq = 2,
  size = 0.5,
  ngrams = 1,
  stemming = FALSE,
  n.labels = 1,
  repel = TRUE
)`

What am I doing wrong? 

[savedrecs.txt](https://github.com/massimoaria/bibliometrix/files/6605877/savedrecs.txt)

**Comment by massimoaria** [comment]
the argument "years" sets the years used to split the timespan into different time-slices.
How did you set "years"?
Maybe, one or more time-slices are empty.
