### ISSUE TITLE
The install.packages is not installing the dependencies of bibliometrix

### ISSUE THREAD

**Issue by adilbilal** [massimoaria/bibliometrix#203]
Hi there,
I tried to install bibliometrix today on my desktop after a long time. I realized that the install.packages is not installing the dependencies needed to run biblioshiny. The installation encountered with errors. Like there is no package named fastmap, then bslib, and so on. Now when I able to get access to biblioshiny, it shows there is no package called farver.

Kindly resolve this issue.

Best,

**Comment by massimoaria** [comment]
Failing to install all right dependencies is an issue of R working under Microsoft Windows. That happens many times for many packages.
Unfortunately, I am only the creator and the maintainer of bibliometrix and I cannot solve general R issues.
When the problem appears, you can try to manually install the missing packages. At the moment, this is the only solution that works.
