### ISSUE TITLE
biblioAnalysis - Error in df$Country[i] - from WoS BibTeX data

### ISSUE THREAD

**Issue by emfk** [massimoaria/bibliometrix#204]
I get the following error when running biblioAnalysis - "Error in df$Country[i] <- co : replacement has length zero". I believe this may also be related to the error I get in Biblioshiny of "Error: replacement has length zero" when trying to look at Dataset->Main Information.

Please see my data file attached, downloaded from Web of Science as a BibTeX file. I'm running the most recent version of Bibliometrix (3.1.3). 

Is this maybe related to the recent Web of Science updates in their field tags? 

Thanks in advance for your help!

[WoS_DataSet_1-371.zip](https://github.com/massimoaria/bibliometrix/files/6684731/WoS_DataSet_1-371.zip)

**Comment by massimoaria** [comment]
On my pc, using the last version of bibliometrix (from GitHub), all works fine:

library(bibliometrix)

file <- "WoS_DataSet_1-371.bib"

M <- convert2df(file, "wos", "bibtex")

res <- biblioAnalysis(M)

summary(res)

MAIN INFORMATION ABOUT DATA

 Timespan                              2001 : 2021 
 Sources (Journals, Books, etc)        156 
 Documents                             371 
 Average years from publication        3.47 
 Average citations per documents       23.98 
 Average citations per year per doc    4.6 
 References                            21979 
 
DOCUMENT TYPES                     
 article                         333 
 article; early access           10 
 article; proceedings paper      5 
 review                          23 
 
DOCUMENT CONTENTS
 Keywords Plus (ID)                    894 
 Author's Keywords (DE)                1318 
 
AUTHORS
 Authors                               958 
 Author Appearances                    1079 
 Authors of single-authored documents  35 
 Authors of multi-authored documents   923 
 
AUTHORS COLLABORATION
 Single-authored documents             35 
 Documents per Author                  0.387 
 Authors per Document                  2.58 
 Co-Authors per Documents              2.91 
 Collaboration Index                   2.75 
 

Annual Scientific Production

 Year    Articles
    2001        1
    2003        1
    2005        1
    2006        2
    2007        1
    2008        2
    2009        1
    2010        9
    2011        6
    2012        9
    2013        4
    2014        4
    2015       23
    2016       21
    2017       42
    2018       55
    2019       71
    2020       97
    2021       11

Annual Percentage Growth Rate 12.73782 


Most Productive Authors

    Authors        Articles Authors        Articles Fractionalized
1  FOERSTL K              5   SEURING S                       1.70
2  SEURING S              5   SILVESTRE BS                    1.70
3  BAG S                  4   KANNAN D                        1.67
4  GRUCHMANN T            4   MOUSAVI S                       1.67
5  MOUSAVI S              4   BHUPENDRA KV                    1.50
6  WANG Y                 4   FOERSTL K                       1.50
7  ALBAREDA L             3   KANT M                          1.50
8  BENITEZ-AMADO J        3   SANGLE S                        1.50
9  BHUPENDRA KV           3   GRUCHMANN T                     1.37
10 BOSSINK B              3   BESKE P                         1.33


Top manuscripts per citations

                                   Paper                                       DOI  TC TCperYear  NTC
1  RINDOVA VP, 2001, ACAD MANAGE J                10.2307/3069400                  405     19.29 1.00
2  BESKE P, 2014, INT J PROD ECON                 10.1016/j.ijpe.2013.12.026       321     40.12 2.56
3  REUTER C, 2010, J SUPPLY CHAIN MANAG           10.1111/j.1745-493X.2010.03189.x 270     22.50 3.18
4  FOERSTL K, 2010, J PURCH SUPPLY MANAG          10.1016/j.pursup.2010.03.011     218     18.17 2.57
5  ARMSTRONG CE, 2007, J MANAG                    10.1177/0149206307307645         212     14.13 1.00
6  PAGELL M, 2010, J SUPPLY CHAIN MANAG           10.1111/j.1745-493X.2009.03186.x 190     15.83 2.24
7  MILLER D, 2003, STRATEG MANAGE J               10.1002/smj.316                  179      9.42 1.00
8  CRITTENDEN VL, 2011, J ACAD MARK SCI           10.1007/s11747-010-0217-2        158     14.36 4.10
9  DANGELICO RM, 2017, BUS STRATEG ENVIRON        10.1002/bse.1932                 129     25.80 4.51
10 BESKE P, 2012, INT J PHYS DISTRIB LOGIST MANAG 10.1108/09600031211231344        129     12.90 1.65


Corresponding Author's Countries

          Country Articles   Freq SCP MCP MCP_Ratio
1  UNITED KINGDOM       39 0.1054  23  16     0.410
2  SPAIN                37 0.1000  23  14     0.378
3  CHINA                34 0.0919  19  15     0.441
4  USA                  31 0.0838  21  10     0.323
5  ITALY                19 0.0514  15   4     0.211
6  GERMANY              17 0.0459  13   4     0.235
7  INDIA                17 0.0459  14   3     0.176
8  NETHERLANDS          17 0.0459   8   9     0.529
9  AUSTRALIA            14 0.0378  11   3     0.214
10 BRAZIL               12 0.0324  12   0     0.000


SCP: Single Country Publications

MCP: Multiple Country Publications


Total Citations per Country

      Country      Total Citations Average Article Citations
1  USA                        1464                     47.23
2  GERMANY                    1380                     81.18
3  UNITED KINGDOM             1142                     29.28
4  SPAIN                       735                     19.86
5  CANADA                      657                     73.00
6  DENMARK                     428                     47.56
7  CHINA                       419                     12.32
8  ITALY                       341                     17.95
9  INDIA                       336                     19.76
10 NETHERLANDS                 313                     18.41


Most Relevant Sources

                                                 Sources        Articles
1  SUSTAINABILITY                                                     51
2  JOURNAL OF CLEANER PRODUCTION                                      38
3  BUSINESS STRATEGY AND THE ENVIRONMENT                              19
4  INTERNATIONAL JOURNAL OF PRODUCTION ECONOMICS                      13
5  SUPPLY CHAIN MANAGEMENT-AN INTERNATIONAL JOURNAL                   10
6  JOURNAL OF BUSINESS ETHICS                                          8
7  ENVIRONMENTAL INNOVATION AND SOCIETAL TRANSITIONS                   7
8  INTERNATIONAL JOURNAL OF LOGISTICS MANAGEMENT                       7
9  CORPORATE SOCIAL RESPONSIBILITY AND ENVIRONMENTAL MANAGEMENT        6
10 JOURNAL OF PURCHASING AND SUPPLY MANAGEMENT                         6


Most Relevant Keywords

             Author Keywords (DE)      Articles Keywords-Plus (ID)     Articles
1  SUSTAINABILITY                           103  DYNAMIC CAPABILITIES       222
2  DYNAMIC CAPABILITIES                      82  PERFORMANCE                142
3  INNOVATION                                26  MANAGEMENT                  86
4  CAPABILITIES                              23  RESOURCE-BASED VIEW         79
5  PERFORMANCE                               17  INNOVATION                  65
6  SMES                                      16  SUSTAINABILITY              65
7  SUSTAINABLE SUPPLY CHAIN MANAGEMENT       16  COMPETITIVE ADVANTAGE       58
8  CORPORATE SUSTAINABILITY                  15  IMPACT                      55
9  RESOURCE-BASED VIEW                       15  FIRM PERFORMANCE            48
10 SUSTAINABLE DEVELOPMENT                   15  FIRM                        47

**Comment by emfk** [comment]
Thanks for your help, Massimo! That did it. I had updated to the new version via RStudio, but it just needed a clean wipe and re-install from the Github source. It also fixed the Biblioshiny issue.
