### ISSUE TITLE
Articles and Citations by Countries and Year

### ISSUE THREAD

**Issue by myaseen208** [massimoaria/bibliometrix#205]
I wonder how to get Number of Articles and Citations by Countries and Year.

`S$MostProdCountries` and `S$TCperCountries` (Complete code is given below) provide Number of Articles by Countries and Number of Citations by Countries. 

```
library('bibliometrix')

## An example from bibliometrix vignettes
file <- "https://www.bibliometrix.org/datasets/savedrecs.bib"
M <- convert2df(file = file, dbsource = "isi", format = "bibtex")
results <- biblioAnalysis(M, sep = ";")
S <- summary(object = results, k = 10, pause = FALSE)
S$MostProdCountries
          Country Articles   Freq SCP MCP MCP_Ratio
1  USA                  81 0.3057  76   5    0.0617
2  UNITED KINGDOM       27 0.1019  27   0    0.0000
3  GERMANY              17 0.0642  12   5    0.2941
4  FRANCE               13 0.0491  11   2    0.1538
5  BRAZIL               12 0.0453  10   2    0.1667
6  CHINA                10 0.0377   8   2    0.2000
7  INDIA                10 0.0377  10   0    0.0000
8  AUSTRALIA             8 0.0302   6   2    0.2500
9  CANADA                8 0.0302   7   1    0.1250
10 SPAIN                 8 0.0302   8   0    0.0000

S$TCperCountries
     Country      Total Citations Average Article Citations
1  USA                       1831                     22.60
2  GERMANY                    330                     19.41
3  ITALY                      163                     32.60
4  AUSTRALIA                  134                     16.75
5  UNITED KINGDOM             125                      4.63
6  CANADA                     111                     13.88
7  INDIA                       85                      8.50
8  IRAN                        74                     37.00
9  SPAIN                       73                      9.12
10 BELGIUM                     70                     10.00
```

**Comment by massimoaria** [comment]
Here a possible solution:

library(bibliometrix)
library(bibliometrixData)
library(tidyverse)

data(management)

M <- metaTagExtraction(management, "AU_CO")



CO <- tibble(Country = unlist(strsplit(M$AU_CO,";")), 
             Year = rep(M$PY,lengths(strsplit(M$AU_CO,";"))), 
             nAuPerArt = rep(lengths(strsplit(M$AU_CO,";")),lengths(strsplit(M$AU_CO,";")))
             )

CO %>% group_by(Country,Year) %>% 
  summarise(frequency = length(Country),
            frequencyFractionalized = sum(1/nAuPerArt))

**Comment by massimoaria** [comment]
Here an example on how to do it:

library(bibliometrix)
library(bibliometrixData)
library(tidyverse)

data(management)

M <- metaTagExtraction(management, "AU_CO")



CO <- tibble(Country = unlist(strsplit(M$AU_CO,";")), 
             Year = rep(M$PY,lengths(strsplit(M$AU_CO,";"))), 
             nAuPerArt = rep(lengths(strsplit(M$AU_CO,";")),lengths(strsplit(M$AU_CO,";")))
             )

CO %>% group_by(Country,Year) %>% 
  summarise(frequency = length(Country),
            frequencyFractionalized = sum(1/nAuPerArt))
