### ISSUE TITLE
Problem with R Studio

### ISSUE THREAD

**Issue by Alfaya1995** [massimoaria/bibliometrix#207]
Hi, i'm working at a research using bibliometrix. I was using R as normal but then i format my pc and after i reinstall R and R Studio i'm having issue to use my usual script. I install all the packages but when i run "biblioshiny()" and try to upload the .csv file something go wrong. Can anybody help me? (sorry for bad english).
This is the error R is returning.
![image](https://user-images.githubusercontent.com/45636991/125285968-9f261180-e2f1-11eb-8408-450ae369a44d.png)
![image](https://user-images.githubusercontent.com/45636991/125286011-ab11d380-e2f1-11eb-9d5b-54d9dd1a1a00.png)

This is the script i was using 

# install.packages("bibliometrix") # Baixar o pacote. Só precisa fazer isso uma vez! E demora muito, por vezes muitos minutos!

library(bibliometrix) # carregar o pacote na memória para utilizá-lo agora.

# Dúvidas de uso do Bibliometrix, execute  o comando que segue: help(bibliometrix)

############### ETAPA 1 - CARREGAMENTO E CONVERSÃO DOS DADOS ###############

# WEB OF SCIENCE (ISI): Converter os dados para o padrão do bibliometrix
A <- convert2df("c:/bib/savedrecs.bib", dbsource = "isi", format = "bibtex")

# SCOPUS: Converter os dados   para o padrão do bibliometrix
B <- convert2df("c:/bib/scopus.bib", dbsource = "scopus", format = "bibtex")

# PUBMED: Se desejar carregar:
    # para agora de executar este script.
    # execute o script do PubMed,que está na pasta deste workshop, gerando o arquivo de dados "C"
    # volte nesta linha e continue a execução deste script

# COCHRANE: Se desejar carregar dados  execute a linha que segue, gerando o arquivo de dados "D"
# D <- convert2df("c:/bib/citation-export.bib", dbsource = "isi", format = "bibtex")

#### Juntar bases WEB OF SCIENCE (ISI), SCOPUS, PUBMED e COCHRANE
 M <- mergeDbSources(A, B, remove.duplicated = TRUE)
# M <- mergeDbSources(A, B, C, D, remove.duplicated = TRUE) # se precisar juntar dados do Pubmed e Cochrane, execute linha que segue

#### Cria um arquivo.csv para importar para o Excel  
P<- M[,c("AU","TI","SO","AB","DE","DI","TC","PY","ID","LA","DT")]  # Cria lista na ordem desejada
# P<- M[,c("AU","TI","SO","AB","DE","DI","TC","PY"               )]  # Se usar Cochrane, use esta linha ao invés da anterior. Cria lista na ordem desejada
write.table(P, "c:/bib/artigos.csv", sep=";", row.names=FALSE) #para gerar com separador ";", sem necessidade de ajustar o CSV, quanto à primeira coluna

# write.table(M, "c:/bib/art4.csv", sep=";", row.names=FALSE) # para gerar com separador ";", sem necessidade de ajustar o CSV, quanto à primeira coluna

resultados <- biblioAnalysis(M) # BiblioAnalysis - Processamento dos dados

####  Resumo dos resultados na console do RStudio
Resumo <- summary(object = resultados, k = 10)
# plot(resultados, k=10)   # Gráficos com dados bibliométricos básicos

#### Para visualizar os resultados via web-interface (browser) 
biblioshiny()

**Comment by dansferr** [comment]
Hi
i'm having the same issue.
(estou usando o mesmo código que você e fiz quase que os mesmo procedimentos pra compilar as pesquisas, você conseguiu prosseguir?)
