### ISSUE TITLE
Function citations() not returning authors' initials after merging of Scopus and WOS data frames

### ISSUE THREAD

**Issue by 4Backup** [massimoaria/bibliometrix#208]
I need to obtain the frequency distributions of cited authors, the bibliometrix doc states that this can be done with 

`citations(M, field = "author", sep=";")`

The function works as intended for the individual WOS data frame, but doesn't work for Scopus.
If I use mergeDbSources with only one database without removing duplicates the function works fine, 
 
However, I need to merge the two of them (Scopus and WOS) and remove the duplicates

After merging Scopus and WOS data frames using 

`M <- mergeDbSources(Scopus, WOS, remove.duplicated = TRUE)`

The function

`CR <- citations(M, field = "author", sep=";")` 

Doesn't return some authors' initials, making it impossible to identify them as many authors have the same second name.

I'm using Bibliometrix 3.1.4, the version of my Rstudio is:

![image](https://user-images.githubusercontent.com/33006674/125525679-3c2c0b81-abb4-46cb-ba0f-0dd1e89322a6.png)

This is my code:

```
library(bibliometrix)

filescopus <- "C:/pathtofolder/scopust.bib"
filewos <- "C:/pathtofolder/wos.txt"
Mscopus <- convert2df(file = filescopus, dbsource = "scopus", format = "bibtex")
Mwos <- convert2df(file = filewos, dbsource = "wos", format = "plaintext")

M <- mergeDbSources(Mscopus, Mwos, remove.duplicated = TRUE)

CR <- citations(M, field = "author", sep=";")
cbind(CR$Cited[1:10])
```
This is the result:

![image](https://user-images.githubusercontent.com/33006674/125525006-5acd4c50-6e74-4c63-af3f-e59b7f3390ba.png)

**Comment by massimoaria** [comment]
The function mergeDbSources is still in beta version. We are hardly working to solve the merging problems.
Please upload your collections so we can try to solve the issue.

**Comment by 4Backup** [comment]
These are the databases I used to show the error in this issue.

[scopus_wos.zip](https://github.com/massimoaria/bibliometrix/files/7188207/scopus_wos.zip)
