### ISSUE TITLE
Autors and publicatios inside thematic network cluster

### ISSUE THREAD

**Issue by rameman** [massimoaria/bibliometrix#209]
I would like to know if there is a method to know what articles are in each cluster of a network by topics or words. For example I have a topic network that is generally distributed in a network that is made up of words referring to the following.

Cluster: 1 Ethics
Cluster: 2 Policy
Cluster: 3 Company

But to do a detailed analysis I would have to know which articles refer to these clusters of words. I've been trying to get it out and I haven't been able to, with some kind of "id" stored it would be enough to make a connection.
Thanks for the package, it is very good.

**Comment by massimoaria** [comment]
Thematic map analysis is based on network analysis.
Networks start from an adjacency matrix (also called bag of words) that only measures the relationships among couples of words. It is not possible to obtain a link between cluster and documents.
If you are interested in this point, you should perform a co-word analysis through a factorial analysis approach.

**Comment by rameman** [comment]
I found the solution with you steps.
Thank you for your response
