### ISSUE TITLE
Use case insensitive Tag matching for conversion of bib to df

### ISSUE THREAD

**Issue by opetchey** [massimoaria/bibliometrix#21]
Hi! Thanks for a great package!
While working with it I did the following and suggest the following:
I made a separate function specifically for zotero bib output to df (due to case sensitivity in the isibib2df() matching and non-capitalised field names from zotero (same as from Papers)), but it would likely be better to have one generally functioning bib to df function (e.g. bibtex2df) (i.e. it should not matter where the bibtex comes from).

My function here:
https://github.com/opetchey/bibliometrix/blob/master/R/zoterobib2df.R
Original one here:
https://github.com/opetchey/bibliometrix/blob/master/R/isibib2df.R

Owen

**Comment by massimoaria** [comment]
Dear Owen 
I followed your advice.
I wrote a new function, bib2df o import bibtex files from any software.
The new function substitute isibib2df and scopus2df (I left the two function names for legacy with old scripts).

**Comment by rodfileto** [comment]
Dear All,

Thank you for the package. It is a great resource for scientometric analysis.

Related to the function "bib2df", I checked that in the dataframe, all semicolons are replaced by comma from the fields in the bibtex file (from Web of Science) "Funding-Text" and "Funding-Acknowledgement". The function work properly with other fields that also have semicolon, such as Author and Address.

Rodrigo
