### ISSUE TITLE
The main indices of centrality and prestige of vertices - summary () not generating vertex description tables

### ISSUE THREAD

**Issue by statosphere-research** [massimoaria/bibliometrix#211]
Hi,

I am trying to generate the vertex statistics of a network, using the following commands:

netstat <- networkStat(NetMatrix)
summary(netstat,k=10)

However, it generates only the "main information about the network" but NOT the -"vertex description through several tables". 

Please advise. 

Thanks & regards

**Comment by massimoaria** [comment]
You have to set the arguments: 
stat="all" 
type = "degree" (or another vertex centrality measure)
in the function networkStat to calculate also the vertex statistics.
e.g.
data(scientometrics, package = "bibliometrixData")

NetMatrix <- biblioNetwork(scientometrics, analysis = "co-citation", 
      network = "references", sep = ";")
netstat <- networkStat(NetMatrix, stat = "all", type = "degree")
summary(netstat,k=10)

Main statistics about the network

 Size                                  4283 
 Density                               0.022 
 Transitivity                          0.684 
 Diameter                              4 
 Degree Centralization                 0.468 
 Average path length                   2.456 
 





Main measures of centrality and prestige of vertices


Degree Centrality: Top vertices

   Vertex ID              Degree Centrality
1       SMALL H 1973                  0.490
2       WHITE HD 1998                 0.280
3       KESSLER MM 1963-1             0.272
4       MCCAIN KW 1990                0.241
5       BARNEY J 1991                 0.233
6       WHITE HD 1981-1               0.230
7       NELSON R. 1982                0.216
8       SMALL H 1974                  0.197
9       PRICE DJD 1965-1              0.191
10      SMALL H 1985-1                0.190

**Comment by statosphere-research** [comment]
Dear Massimo Aria,

It works. Thanks a lot for your help. 

Best regards

**Comment by statosphere-research** [comment]
This issue has now been resolved to my satisfaction. Thanks

**Comment by SRoy1024** [comment]
@massimoaria 
Sir, the function `networkStat` supports the argument `type = "all"`: what is the purpose of that? in place of `type="degree"` I have used `type="all"` in the call to `networkStat`; only the main information about the network is displayed (not the section on 'Main measures of centrality and prestige of vertices')

Is this what is expected?

Thanks in advance: SRoy
