### ISSUE TITLE
Error: unused argument (images = list("data:image/png;base64...

### ISSUE THREAD

**Issue by rameman** [massimoaria/bibliometrix#214]
I have an error when I want to see some plots. I attached the example
I think that part worked the last week, it could be my data but I tried to do with a new data and I have the same problem.
Thanks!

![Captura](https://user-images.githubusercontent.com/32108698/133936639-ad3a12e8-9a41-4dc8-a42f-96fa323a3847.JPG)

**Comment by rameman** [comment]
The error inside R

![Captura1](https://user-images.githubusercontent.com/32108698/133937552-8ddf78ca-73b0-4ffd-bc85-7cfe3f00405e.JPG)

**Comment by massimoaria** [comment]
Please upload your file

**Comment by rameman** [comment]
Hello,
I attached the document ".bib". I upgrade the R, RStudio and the package and I still have the same problem.
Thanks for all.
Rafa

[346_040821.zip](https://github.com/massimoaria/bibliometrix/files/7286461/346_040821.zip)

**Comment by massimoaria** [comment]
Hi,
The error is due to some missing metadata in your collection.
In particular, you are trying to perform a thematic analysis using Keyword Plus, but this field is not included in your file.
The analysis will perform without issues if you change the content field (e.g. Author's keyword or title).
