### ISSUE TITLE
Errors on the citation network using TIpost and CR

### ISSUE THREAD

**Issue by Biabiatiz** [massimoaria/bibliometrix#216]
Hi, Massimo,

I hope this message finds you well. Thanks for the package, which is very useful!

I have realized that developing the direct citation network from the perfect matching between CR and TIpost  - as the [histNetwork function](https://github.com/massimoaria/bibliometrix/blob/master/R/histNetwork.R) does - produces the following errors: 

- Some citations that should not be generated are being generated (which happens when the title of the publication is much simple, as in books, for example); and
- Some citations that should be generated are not being generated (which happens mainly because of slight writting differences between the original publication and the way it is cited by other publications)

Considering those errors, I have adapted the Script of [histNetwotk](https://github.com/massimoaria/bibliometrix/blob/master/R/histNetwork.R) to allow the direct citation network to be generated from the ID of each publication and reference (as a perfect matching of numbers minimizes the errors). This works well, but the Scopus API does not have the ID of references of every publication with references information (sometimes the publication has the CR but does not have the ID of the references), which is making me loose part of my data. 

In this regard, I would like to know if have you ever though about how to avoid those errors? (I bring forward that I have already tried generating the network using the CR and some field with author, title and year, but authorship has almost no patter among publications, which amplifies the problem (and I imagine you developed TIpost because of something related with this).

Anyway, any ideia would be very welcome.

Thanks a lot.
All the best,
Bia

**Comment by massimoaria** [comment]
Dear Bia
I know the issue in building direct citations using Scopus data. 
We are working on a solution.

Best
Massimo

**Comment by rameman** [comment]
I had a similar problem because the same publication is cited as different kind of bibliography. Some solution could be modifying the main file with a text processor, doing a hand edition. With this I solved the problem, but depending of the number of cites that you need repair it it could be difficult to do.
