### ISSUE TITLE
Importing From Zotero

### ISSUE THREAD

**Issue by joofio** [massimoaria/bibliometrix#218]
Hi,

I want to export a few papers from zotero to bibliometrix.

I have been taking a look in the issues, and the function bib2df is working for generic bibtex export?

I have tried with betterbibtex in zotero, but maybe some configuration is missing? 

Is this doable at the moment?

Thank you very much!
Best regards,

**Comment by kevinhosford** [comment]
> 
> 
> I tried out the same and it seems that it depends on the formatting of the BibTeX file. I had to delete any tab `\t` at the beginning of a line and replaced the ` = {` with the version without any spaces, i.e. `={` in my bib-file from Zotero. After that I could use the file with bibliometrix. Maybe, some of these replacements can be included in the code here?

Could you further elaborate on this? what settings via Zotero and possibly your import code? I've been trying this but getting an: Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 0, 224

**Comment by massimoaria** [comment]
Dear all,
I am still working on an importing routine for Zotero files.
Stay tuned!

**Comment by DalzAsylum** [comment]
would have been great... Also as we could have all the pdf into zotero, and possibility to "merge" it in a document with titles and astracts... But no bibliography.
