### ISSUE TITLE
"Times" error with exported files

### ISSUE THREAD

**Issue by kayebohemier** [massimoaria/bibliometrix#222]
Hello. I'm trying to do visualizations, but am unable to directly export from the Web of Science because the Marked Lists in the old version have stopped working, and they haven't added all of the fields to the new version yet. I tried at first to work with the EndNote files downloaded from the new version, but the files refused to load because they didn't contain the full fields.

I got around this by exporting from a Marked List in the new version, importing it into EndNote Desktop, running an update reference task to get the missing fields, syncing with EndNote online, and downloading an EndNote .ciw file (which is a .txt file when downloaded, but I renamed the file). I no longer get a missing fields error.

Unfortunately, whenever I import that file and try to run it with bibliometrix, I get the following error with any file I try:

```
Converting your wos collection into a bibliographic dataframe

Error in rep(1:nP, rowPapers) : invalid 'times' argument
```

Here is my script from the beginning until I hit the error:

```
testname <- "/Users/username/Documents/this is a project/test.ciw"

#install.packages("bibliometrix", dependencies=TRUE)
library(bibliometrix)

testnamed <- convert2df(testname, dbsource = "wos", format = "endnote")
```

I don't know if there's a workaround for the Web of Science being in the state it's in right now or if the formatting of their files has changed, but it seems odd for something to go this badly right off the bat like this.

**Comment by massimoaria** [comment]
The new WoS interface allows exporting the same set of metadata included in the previous version.
You have to:
1) select the export button, 
2) choose one of the supported file formats (Endnote Desktop, BibTex, or Plaintext)
3) select the "Full Record and Cited References" in the Record Content dropdown menu.

The file (or files) download will perfectly work with bibliometrix/biblioshiny.

![image](https://user-images.githubusercontent.com/16023543/143040568-282cbbe2-20f9-4de7-a422-c900922949bc.png)
