### ISSUE TITLE
Importing problem with the "Marked List" of WoS

### ISSUE THREAD

**Issue by xiaochi-liu** [massimoaria/bibliometrix#227]
Hello, I got an importing problem related to files from [Web of Science](https://www.webofscience.com/wos/woscc/basic-search).

When I import a file that is exported directly from the searching result, everything is fine.

However, when I import a file that is exported from a "Marked List" of WoS, no matter what the format is (`plaintext` or `endnote`), I got the error, "Missing fields:  DE C1 RP CR":

``` r
library(bibliometrix)
#> To cite bibliometrix in publications, please use:
#> 
#> Aria, M. & Cuccurullo, C. (2017) bibliometrix: An R-tool for comprehensive science mapping analysis, 
#>                                  Journal of Informetrics, 11(4), pp 959-975, Elsevier.
#>                         
#> 
#> https://www.bibliometrix.org
#> 
#>                         
#> For information and bug reports:
#>                         - Send an email to info@bibliometrix.org   
#>                         - Write a post on https://github.com/massimoaria/bibliometrix/issues
#>                         
#> Help us to keep Bibliometrix free to download and use by contributing with a small donation to support our research team (https://bibliometrix.org/donate.html)
#> 
#>                         
#> To start with the shiny web-interface, please digit:
#> biblioshiny()
M_wos <- convert2df(file = "/Users/liuxiaochi/Documents/rstudio-project/My-Collaboration/XGeoAI/data/wos_refine_15Jan2022.txt", 
                    dbsource = "wos", 
                    format = "plaintext")
#> 
#> Converting your wos collection into a bibliographic dataframe
#> 
#> 
#> Warning:
#> In your file, some mandatory metadata are missing. Bibliometrix functions may not work properly!
#> 
#> Please, take a look at the vignettes:
#> - 'Data Importing and Converting' (https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html)
#> - 'A brief introduction to bibliometrix' (https://www.bibliometrix.org/vignettes/Introduction_to_bibliometrix.html)
#> 
#> 
#> Missing fields:  DE C1 RP CR
#> Error in `$<-.data.frame`(`*tmp*`, "C1", value = character(0)): replacement has 0 rows, data has 38
M_wos <- convert2df(file = "/Users/liuxiaochi/Documents/rstudio-project/My-Collaboration/XGeoAI/data/wos_refine_15Jan2022.ciw", 
                    dbsource = "wos", 
                    format = "endnote")
#> 
#> Converting your wos collection into a bibliographic dataframe
#> 
#> 
#> Warning:
#> In your file, some mandatory metadata are missing. Bibliometrix functions may not work properly!
#> 
#> Please, take a look at the vignettes:
#> - 'Data Importing and Converting' (https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html)
#> - 'A brief introduction to bibliometrix' (https://www.bibliometrix.org/vignettes/Introduction_to_bibliometrix.html)
#> 
#> 
#> Missing fields:  DE C1 RP CR
#> Error in `$<-.data.frame`(`*tmp*`, "C1", value = character(0)): replacement has 0 rows, data has 38
```

<sup>Created on 2022-01-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

And I don't know why the Marked List of WoS can't export the `bibtex` format.

How could I solve this problem? Your kind guidance is much appreciated!

**Comment by massimoaria** [comment]
This is an issue with the new WoS interface.
When you save a collection as a Marked List, The new WoS automatically set all databases as the default option. 
Unfortunately, in WoS only the SCI, SSCI and Emerging Sources databases contain all the metadata needed for a science mapping analysis.
Therefore, before downloading the collection, you must select only the SCI, SSCI, and Emerging Sources databases in the Web of Science Index filter.

![image](https://user-images.githubusercontent.com/16023543/149927075-fa92f994-94d4-490f-b7fc-0251c309b4d7.png)

Then you can export the collection by selecting one of the bibliometrix compatible formats (plaintext, bibtex or Endnote Desktop) and then "Full Record and Cited References" in the field "Record Content"

![image](https://user-images.githubusercontent.com/16023543/149928175-392bd225-3011-44b5-a0e3-f57d6d6a9142.png)

**Comment by xiaochi-liu** [comment]
This is awesome. Thank you very much @massimoaria!
