### ISSUE TITLE
convert2df issue

### ISSUE THREAD

**Issue by felixaraj** [massimoaria/bibliometrix#229]
When I try converting file, I have this error:

Converting your wos collection into a bibliographic dataframe

Error in if (Papers[1] > 1) { : missing value where TRUE/FALSE needed

I tried converting as "Plaintext", still facing the below errors:

Converting your wos collection into a bibliographic dataframe

Error in rep(1:nP, rowPapers) : invalid 'times' argument

**Comment by massimoaria** [comment]
Please upload your collection and the R code you are using.
