### ISSUE TITLE
Biblioshiny

### ISSUE THREAD

**Issue by donibeck** [massimoaria/bibliometrix#234]
Hi, I'm trying to open the biblioshiny and the R retrieves me the following error:

Warning: Error in shinythemes::shinytheme: flatly is not an available theme. Valid themes are: .
  79: stop
  78: shinythemes::shinytheme
Warning: Error in shinythemes::shinytheme: flatly is not an available theme. Valid themes are: .
  79: stop
  78: shinythemes::shinytheme

**Comment by massimoaria** [comment]
The issue is due to shinythemes which is no longer supported. 
Now biblioshiny has base on the new package bslib.

**Comment by Donadb08** [comment]
> 

I have installed the packages bslib, shiny, shinythemes, but I wasn't able to open Biblioshiny. Unfortunately, I have the same error.

**Comment by donibeck** [comment]
Hi, Donald. Unfortunately, even instaling bslib package, I'm facing the same issue. I'm not a programmer. If a good soul here read it and could help us, it will make us happier! 

Thanks, community and Prof. Aria! 


Warm regards,
Doni

**Comment by massimoaria** [comment]
Hi, 
I have solved the issue but you have to update bibliometrix from GitHub to obtain the new working version. 
Please run the following code:

install.packages("devtools")         
devtools::install_github("massimoaria/bibliometrix")

**Comment by donibeck** [comment]
Thank you very much, Prof. Massimo Aria!!!

The Biblioshiny is running with all perfection, now!!!

Thank you, but thank you again!

On a Sunday, you're helping people from all over the world! Thank you for this!!!

Warm regards,
Doni

**Comment by massimoaria** [comment]
You are welcome!

**Comment by Donadb08** [comment]
Thank you so much!

> Hi, I have solved the issue but you have to update bibliometrix from GitHub to obtain the new working version. Please run the following code:
> 
> install.packages("devtools") devtools::install_github("massimoaria/bibliometrix")
