### ISSUE TITLE
biblioshiny() does not open the web page

### ISSUE THREAD

**Issue by aryantono** [massimoaria/bibliometrix#235]
biblioshiny() got this error messages:
Warning: Error in shinythemes::shinytheme: flatly is not an available theme. Valid themes are: .
  79: stop
  78: shinythemes::shinytheme
Warning: Error in shinythemes::shinytheme: flatly is not an available theme. Valid themes are: .
  79: stop
  78: shinythemes::shinytheme

Web page error message:
An error has occurred!
flatly is not an available theme. Valid themes are: .

**Comment by massimoaria** [comment]
Please see the thread #234
