### ISSUE TITLE
Bibliometrix is creating a "phantom" co-word

### ISSUE THREAD

**Issue by Prof1950** [massimoaria/bibliometrix#237]
I am working on an analysis of the field of mixed methods research, and co-word analyses keep including not only the the word "mixed" but also corruptions of that word as "mixeds."

I have checked my raw data file and there no instances of "mixeds". I also tried putting it in the exclusions lists and in the synonyms list, neither of which worked. I have saved as both R and Excel files and they generate the same problem.

Given that this non-existent term is so closely related to my core interests, I won't be able to publish any maps that include it.

FYI I am using Biblioshiny on a Mac.

Suggestions?

**Comment by massimoaria** [comment]
Please upload your example file and more information about the content metadata you are analyzing (authors' keywords, titles, abstracts, etc.)

**Comment by Prof1950** [comment]
The problem seems to have vanished today, although it was there consistently from Friday through Sunday.


David L. Morgan ***@***.***>
Emeritus Professor, Department of Sociology
Portland State University

Of course it works in practice, but will it work in theory?
