### ISSUE TITLE
Cannot create country collaboration using scopus db

### ISSUE THREAD

**Issue by baqrie** [massimoaria/bibliometrix#24]
Hi,

I tried the new function bib2df with scopus database. It give me this error when I create the network plot. 

> Error in if (V(bsk.network)$community[x[1]] == V(bsk.network)$community[x[2]]) { : 
>   argument is of length zero

It works fine with the previous version of convert2df or scopus2df. 
Is there something error in the db conversion?

thanks for the solution.

regards,

**Comment by massimoaria** [comment]
Please send me your scopus file so I can try to replicate the issue

**Comment by baqrie** [comment]
this is the file:
[scopus.zip](https://github.com/massimoaria/bibliometrix/files/2672701/scopus.zip)

My guest is that in the column C1, the separator is , (comma). In the previous function (convert2df or scopus2df), the separator is ; (semicolon).

**Comment by massimoaria** [comment]
I have just solved the issue. Please update your package installation.
