### ISSUE TITLE
world map (country scientific production)

### ISSUE THREAD

**Issue by mehri65** [massimoaria/bibliometrix#243]
Hi everyone
I have a question about "**country scientific production**" in Bibliophily. Does this plot show the number of documents for different countries? Or the number of authors?
The published papers claimed that this is related to the number of documents. But the values of the countries in this plot do not match the number of my documents. So, I think it may be referred to as the number of authors (considering that it is in the Author tab, not the document tab).
Thank you in advance

**Comment by massimoaria** [comment]
Hi,
please have a look at the following discussion:
https://github.com/massimoaria/bibliometrix/issues/133
