### ISSUE TITLE
Problem with scopus csv file

### ISSUE THREAD

**Issue by ManuelSpinola** [massimoaria/bibliometrix#247]
I download a csv file from scopus but the authors and first names are separated by commas that give me a wrong delimitations in authors names and the convert2df cannot distinguish last name from name initials:

This is the format of the Authors column in the csv from scopus:

Gatica, G.N., Sequeira, F.A.

How can I solve this issue?

**Comment by trashbirdecology** [comment]
@ManuelSpinola you should share the full line of convert2df you are running to ensure you are using the `dbsource="scopus"` command...

**Comment by ManuelSpinola** [comment]
Thank you very much, I solved the issue working with other file format.

**Comment by LuciaEspasandin** [comment]
Could you please share how you solved the problem? I have the same issue.
