### ISSUE TITLE
Changing the plot background from "theme_grey()" to "theme_bw() / "theme_linedraw()"

### ISSUE THREAD

**Issue by MohamedaliS** [massimoaria/bibliometrix#249]
Dear Professor,
Is there any function in Bibliometrix package to change the plot background from "theme_grey()" to "theme_bw() / "theme_linedraw()". 

The "plot(x=results, k=10, pause=F)" output produces 5 plots - "Most productive countries", "Most Productive Authors", "Annual Scientific Production", "Average Article Citations per Year", and "Average total citations per year". However, the first two plots have white background and the next three have grey background. I would like to produce them all with white background for journal publication purpose. Your suggestions are greatly appreciated.  

Thanks
Mohamed Ali S

**Comment by matthiasluthi** [comment]
I second @MohamedaliS's question, I would really like to know how to edit the appearence of the plots. Just adding `+ theme_bw()` did not have any effect for me.

**Comment by massimoaria** [comment]
In bibliometrix 4.0, the background color has been set to white for all plots.
