### ISSUE TITLE
network plot problem in Country collaboration 

### ISSUE THREAD

**Issue by baqrie** [massimoaria/bibliometrix#25]
Hi,

What is this error means?

> Error in if (V(bsk.network)$community[x[1]] == V(bsk.network)$community[x[2]]) { : 
>   argument is of length zero

in some data frame, it is OK.

**Comment by massimoaria** [comment]
You have to publish the entire script and the dataset.

In this way, I can help you to solve the issue.

------ Messaggio originale ------
Da: "baqrie" <notifications@github.com>
A: "massimoaria/bibliometrix" <bibliometrix@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Inviato: 13/12/2018 19:22:24
Oggetto: [massimoaria/bibliometrix] network plot problem in Country 
collaboration (#25)

**Comment by baqrie** [comment]
I manage to solve it by merging AU_CO and AU1_CO, but I don't know if it is correct.

**Comment by baqrie** [comment]
I found an error when merging the column AU_CO and AU1_CO into AU_CO. When I run `biblioAnalysis`, the new AU_CO become useless, since the function `countryCollaboration` in `line 199` create a new field AU_CO and use it as the subject to be analyzed.

However, before going there, my question is that, is it correct if I merge the columns?

Thanks for your help.

**Comment by massimoaria** [comment]
No, it is not correct.
AU_CO contains the affiliation's country of each co-author while AU1_CO contains the affiliation's country of the corresponding author.
