### ISSUE TITLE
why Bibliometrix runs much slower than BiblioShiny 

### ISSUE THREAD

**Issue by Xiaojun928** [massimoaria/bibliometrix#250]
Hi Massimoaria,

Thanks for developing the amazing tool👍 

I tried bibliometrix for ~4,000 papers from WOS by following your report template in rmarkdown. And I also tried the same dataset using BiblioShiny. 
But I found BiblioShiny is much quicker than running codes of bibliometrix. The former only takes less than one minute to present network, while the latter would take over 10min. 

I ran both of them on win10.

Have you met this problem? Or do you know what is the potential reason? Thanks in advance!

Best,
Xiaojun

**Comment by massimoaria** [comment]
When you create a network using bibliometrix, the argument verbose is set TRUE as default. 
At the and of network calculation, the function will start to plot the network in the R window ant it takes a lot of time (biblioshiny uses a more efficient js library called visnetwork).
Try to set the argument verbose=FALSE in the networkPlot function. The calculation time should be the same of biblioshiny.
