### ISSUE TITLE
My bibliometrix code stop working after I updated to version 4.0.0

### ISSUE THREAD

**Issue by ManuelSpinola** [massimoaria/bibliometrix#251]
After updating to bibliometrix 4.0.0 my code was working without a problem, but after updated to version 4.0.0 the code stop running in the way that shpuld be.

````
```{r}
file_1975_2005 <- "scopus_1975-2005.bib"
```
```{r}
archivo_1975_2005 <- convert2df(file = file_1975_2005, dbsource = 'scopus', format = "bibtex")
```
Converting your scopus collection into a bibliographic dataframe


Warning:
In your file, some mandatory metadata are missing. Bibliometrix functions may not work properly!

Please, take a look at the vignettes:
- 'Data Importing and Converting' (https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html)
- 'A brief introduction to bibliometrix' (https://www.bibliometrix.org/vignettes/Introduction_to_bibliometrix.html)


Missing fields:  DE ID C1 CR 
Done!


```{r}
results_1975_2021 <- biblioAnalysis(df_1975_2021, sep = ";")
```
Error in C1[which(is.na(C1))] <- M$RP[which(is.na(C1))] : 
replacement has length zero

````

**Comment by dbampoh** [comment]
I am having the same issue. See below:

The issue I have is that when I run the biblioAnalysis function in the bibliometrix r package on a bibtex file of 20 wos/isi article bibliographic data that imports and converts to the supported dataframe correctly without any issues, I get the following error:

```
>Pers_Stud_Anal <- biblioAnalysis(Pers_Stud_Main, sep = ";")
Error in C1[which(is.na(C1))] <- M$RP[which(is.na(C1))] : replacement has length zero
```

Any thoughts on what is going on here?

The C1 and AU_UN fields (which are both logi/lgl data types) in the dataframe has all NAs in it. When I remove the field or change all of it to 1 or put random characters in it to assign it dummy data, I get the following error when I rerun the biblioAnalysis function:

```
>Pers_Stud_Anal <- biblioAnalysis(Pers_Stud_Main, sep = ";")
Error in if (sum(ind > -1) > 0) { : missing value where TRUE/FALSE needed
```

Curious to hear how I might fix this issue.

**Comment by massimoaria** [comment]
I have just solved the issue. Please refer to #253
