### ISSUE TITLE
Errors with the use of Lens.org keywords for the network approach to conceptual structure analysis in Biblioshiny

### ISSUE THREAD

**Issue by Yannsb** [massimoaria/bibliometrix#252]
Hello,
When using Biblioshiny, selecting "keywords plus" and "author's keywords" fields from a lens.org .csv file to analyse the conceptual structure from the network approach results in errors : 
- co-occurence : "argument is of length zero"
- thematic map & evolution : "the arguments imply different numbers of lines: 0, 4"

No problem with other fields (abstract and title)

Here is the file used : [uwbtest.csv](https://github.com/massimoaria/bibliometrix/files/8926898/uwbtest.csv)

Thanks for the help

**Comment by massimoaria** [comment]
Lens.org export files don not include keyword fields!
If you look at your csv file, you can note the the column "keyword" is empty.
Biblioshiny cannot analyze metadata not included in your collection.
