### ISSUE TITLE
run biblioAnalysis function on bibtex-converted dataframe resulting in "replacement has length zero" error

### ISSUE THREAD

**Issue by dbampoh** [massimoaria/bibliometrix#253]
The issue I have is that when I run the biblioAnalysis function in the bibliometrix r package on a bibtex file of 20 wos/isi article bibliographic data that imports and converts to the supported dataframe correctly without any issues, I get the following error:

```
>Pers_Stud_Anal <- biblioAnalysis(Pers_Stud_Main, sep = ";")
Error in C1[which(is.na(C1))] <- M$RP[which(is.na(C1))] : replacement has length zero
```

Any thoughts on what is going on here?

The C1 and AU_UN fields (which are both logi/lgl data types) in the dataframe has all NAs in it. When I remove the field or change all of it to 1 or put random characters in it to assign it dummy data, I get the following error when I rerun the biblioAnalysis function:

```
>Pers_Stud_Anal <- biblioAnalysis(Pers_Stud_Main, sep = ";")
Error in if (sum(ind > -1) > 0) { : missing value where TRUE/FALSE needed
```

Running in biblioshiny() does not work either. Curious to hear how I might fix this issue.

**Comment by massimoaria** [comment]
Please upload a bib file so I could try to identify the issue.

**Comment by dbampoh** [comment]
@massimoaria Thanks for looking into this issue. github will not allow me to upload the .bib file so here is a google drive link from which it can be download: https://drive.google.com/file/d/1ubCRlobJ-8vuHTwDEyYfR4D_hage43Kl/view?usp=sharing

**Comment by massimoaria** [comment]
Hi,
The error appears because your bib file misses info about authors' affiliations.
I added a code line to check this problem and overcome it.
Please, update bibliometrix from GitHub.
