### ISSUE TITLE
Problems in the command convert2df

### ISSUE THREAD

**Issue by nrfsilva** [massimoaria/bibliometrix#255]
Hi,

I am trying to convert my csv from Dimensions. I am using the command 

biblio <- 'C:/Users/xxx/xxx/file.csv'
DIMENSION_df <- convert2df(file = biblio, dbsource = "dimensions", format = "csv"), but I am receiving this error:

_Converting your dimensions collection into a bibliographic dataframe

Rows: 4 Columns: 31                                                                             
-- Column specification -------------------------------------
Delimiter: ","
chr  (17): Publication ID, DOI, Title, Abstract, Acknowle...
dbl   (7): Rank, PubYear, Volume, Issue, Times cited, Rec...
lgl   (6): PMID, PMCID, Anthology title, MeSH terms, RCR,...
date  (1): Publication Date (online)

**i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in strsplit(DATA$AU_UN, ";") : non-character argument
In addition: Warning message:
One or more parsing issues, see `problems()` for details**_ 

I am trying to use this dataset: [file.csv](https://github.com/massimoaria/bibliometrix/files/8987372/file.csv)

Someone could help me?
Best regards,
Nildson

**Comment by nishagove** [comment]
Hi.I am encountering a similar problem. Appreciate if someone could troubleshoot this error

**Comment by massimoaria** [comment]
Hi, 
Dimensions changed the column label of its CSV format and then created an issue in convert2df(). 
I have just corrected it but my advice is to use the excel format to download file from Dimensions. The xlsx full record contains more accurate information.

**Comment by kawai-grammer** [comment]
I have tried working on excel data as well. The error is:
Error in gsub("\\.|-", " ", names(DATA)) : object 'DATA' not found  

Your help will be much appreciated.

**Comment by massimoaria** [comment]
Please give a look to the thread: https://github.com/massimoaria/bibliometrix/issues/262
