### ISSUE TITLE
BIBLISOHINY: Dimensions CSV convert error; non-character argument.

### ISSUE THREAD

**Issue by drashutoshkumarsingh** [massimoaria/bibliometrix#258]
I am using Biblioshiny for a bibliometric analysis using data exported from DIMENSIONS. While the Dimensiosn CSV file is being converted in bibliographic format, it outputs an error: STRSPLIT: Non-character argument. Below is the Rstudio output. Please help me as I rely on dimensions as it is free, and do not have access to Scopus or WoS, which are subscription based.

Converting your dimensions collection into a bibliographic dataframe

Rows: 372 Columns: 15
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (12): Publication ID, DOI, Title, Abstract, Source title/Anthology title, Volume, Pagination, Authors, Authors Affiliat...
dbl (3): PubYear, Issue, Times cited

:information_source: Use spec() to retrieve the full column specification for this data.
:information_source: Specify the column types or set show_col_types = FALSE to quiet this message.
Warning: Error in strsplit: non-character argument
159: strsplit
156: postprocessingDim
155: dimensions2df
154: convert2df
150: eventReactiveValueFunc [/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bibliometrix/biblioshiny/server.R#448]
106: DATAloading
105: exprFunc [/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bibliometrix/biblioshiny/server.R#506]
104: widgetFunc
103: ::
htmlwidgets
shinyRenderWidget
102: func
89: renderFunc
88: renderFunc
84: renderFunc
83: output$contents
2: runApp
1: biblioshiny

**Comment by massimoaria** [comment]
Please,
look at this thread https://github.com/massimoaria/bibliometrix/issues/262
