### ISSUE TITLE
BIBLISOHINY: Dimensions xlsx convert error

### ISSUE THREAD

**Issue by Shashanka87** [massimoaria/bibliometrix#260]
Hello
I am using Biblioshiny for a bibliometric analysis using data exported from DIMENSIONS. While the Dimensiosn xlsx file is being converted in bibliographic format, it outputs an error: Either using R Studio or `Biblioshiny`

"Converting your dimensions collection into a bibliographic dataframe"

Error in gsub("\\.|-", " ", names(DATA)) : object 'DATA' not found

Also facing problem

BIBLISOHINY: Dimensions CSV convert error; non-character argument. #258 [(https://github.com/massimoaria/bibliometrix/issues/258)]

**Comment by massimoaria** [comment]
Please load the dimensions CSV file you are facing the issue.

**Comment by Shashanka87** [comment]
[Dimensions-Publication-2022-07-01_16-07-27.xlsx](https://github.com/massimoaria/bibliometrix/files/9090623/Dimensions-Publication-2022-07-01_16-07-27.xlsx)
[Dimensions-Publication-2022-06-21_18-12-20.csv.zip](https://github.com/massimoaria/bibliometrix/files/9090625/Dimensions-Publication-2022-06-21_18-12-20.csv.zip)

**Comment by felixaraj** [comment]
Greetings,
I am facing an issue in loading Dimensions XLSX files.

[Dimensions-Publication-2022-08-03_10-10-11.xlsx](https://github.com/massimoaria/bibliometrix/files/9250957/Dimensions-Publication-2022-08-03_10-10-11.xlsx)

**Comment by massimoaria** [comment]
Hi,
your xlsx file works perfectly on my pc.
Take care to choose **import raw file** and **Dimensions as source database** when you upload the xlsx file!
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/16023543/183241691-b0ae0c5b-8ca2-47b7-8084-98c7bf282d9c.png">
