### ISSUE TITLE
Question: What is the difference between conference and procedings papers?

### ISSUE THREAD

**Issue by jacksonraniel** [massimoaria/bibliometrix#261]
Hi,

I'm conducting a simple citation analysis, and I could not realize the difference between "conference papers" and "proceedings papers" in the results of the summary function.

Can anyone enlighten it for me, please?

Thank you!

**Comment by massimoaria** [comment]
You can read it on Web of Science information.

However, a conference paper is an journal article published into a journal special issue linked  to a conference.
A proceeding papers is a long paper published into the proceedings book of a conference.
