### ISSUE TITLE
rendering took so much time and did not finish

### ISSUE THREAD

**Issue by ruolan** [massimoaria/bibliometrix#263]
hi there,

i am using the rmd file template i got from the bibliometrix website to render my own data, i find after hours of rendering the process seems never  finish and stocked in the 2% as you can see from the pic. the screenshot were captured when i stopped the process

sourcecode: [Science Mapping Analysis with bibliometrix R-package: sourceCode] https://www.bibliometrix.org/home/images/rmd/bibliometrix_Report.zip

i also added verbose=FALSE to every networkPlot function, i saw this in previous issues and thought it would help solve my problem, but it didn't work either. 

i am using macos  12.4 (21F79), rstudio version RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

is there anything i missed?

thanks

![image](https://user-images.githubusercontent.com/7134844/181679568-93fc0b3e-d40b-4603-9b2f-1aa9cc19c018.png)
![image](https://user-images.githubusercontent.com/7134844/181679408-fab2a0e8-a13b-404a-9281-6f1d79d876ee.png)
![image](https://user-images.githubusercontent.com/7134844/181679436-f69e9a0a-2c17-45b9-a1e6-73c6871a2047.png)

**Comment by massimoaria** [comment]
This is an issue with the R environment rendering system and igraph.

please look at this thread https://github.com/massimoaria/bibliometrix/issues/250
