### ISSUE TITLE
Question: Order of nodes in "Table" at co-occurrences network

### ISSUE THREAD

**Issue by hklab35** [massimoaria/bibliometrix#264]
I would like to ask how bibliometrix output the "Table" in the co-occurrences network analysis. In particular, I am confused about the order of nodes. 
1. How bibliometrix determine the cluster number? For instance, if we have cluster 1-3, what does that number stand for?
2. What determines the order among nodes within the same cluster, by betweenness, closeness, or pagerank? 

Thank you in advance.

**Comment by massimoaria** [comment]
Hi, the cluster number is as in any clustering algorithm. The number is just a numeric label to distinguish different clusters.

The order among nodes usually is based on their occurrences (total degree) within the cluster, but you can obviously reorder them using any centrality index.
