### ISSUE TITLE
How to plot Most Relevant Source with bibliometrix

### ISSUE THREAD

**Issue by tomryjo** [massimoaria/bibliometrix#265]
I would like to plot most relevant source but do not know how to do so. I know I can get it with biblioshiny but as I am writing things in Rmarkdown, it would be better if I can do it with bibliometrix. 

Many thanks.

**Comment by tomryjo** [comment]
Also, could you please guide me how to make a wordcloud of keywords with Bibliometrix? Much appreciate your support.

**Comment by massimoaria** [comment]
Hi, you can do that easily using biblioshiny(), the bibliometrix shiny interface.
