### ISSUE TITLE
Loading Rdata bibliometric export directly into R environment

### ISSUE THREAD

**Issue by sdspieg** [massimoaria/bibliometrix#267]
I have an export from a relatively large dataset that I imported from Scopus (see [here](https://drive.google.com/open?id=10E25CSizRx7KJfczmpfXzYdvYbslmuFF)). That one loads fine in bibliometrix, but I'd still like to play around a bit more with that dataset in R itself too. And so when I try to import it directly into R via read OR base, it only reads the author column, and not even completely. Am I missing something? Thanks!

**Comment by massimoaria** [comment]
When you read a ".rdata" file in R you have to use the function load()

e.g
load("/mypath/myfile.rdata")
