### ISSUE TITLE
Inconsistent count of local citations across different versions

### ISSUE THREAD

**Issue by brunopenteado** [massimoaria/bibliometrix#271]
Dear colleagues,

I executed a query on the Web of Science database and exported its resultset as full record plain text. I managed to import them successfully into two computers running different versions of bibliometrix.

In the first one, using **_bibliometrix 3.0.2_**, I have the following result in the "_Most Local Cited Authors_"
![image](https://user-images.githubusercontent.com/1571708/195996477-f4a08ef3-0656-4126-90fd-95d420815509.png)

However, when using **_bibliometrix 4.0.2_**, I have a very different result for the same data file:
![image](https://user-images.githubusercontent.com/1571708/195937322-3ae5ed45-6f98-479a-8b62-b0bd69a5d74e.png)

Is there any reason for these differences?

File used: https://drive.google.com/file/d/19Y8iOpqMaFnbkflN7mso1DsXNUnczNLq/view?usp=sharing.

Best

**Comment by massimoaria** [comment]
Hi,
In version 4 we improved the algorithm which analyzes references to extract cited authors (first authors in the case of WoS).
Then the latter results are most accurate.
We are continuously working to improve our metadata extraction algorithms. Unfortunately, bibliographic databases have not established a standard record path, so the format changes greatly between one source and another. In addition, the databases contain a lot of incomplete and missing information.

**Comment by brunopenteado** [comment]
Hi Massimo, thank you for your feedback.
My problem here, with the same dataset from WoS, is that the results are not even close to each other (neither the counts nor the authors). They are completely different, and the previous version (3.0.2) is more consistent with our manual checks.
