### ISSUE TITLE
Can't remove terms from some features

### ISSUE THREAD

**Issue by naufaltfa** [massimoaria/bibliometrix#277]
I tried removing terms from my co-occurrence network and word dynamics but the terms still appears on the graph/network. I used an older version and it used to work before but after updating to 4.0.1 terms removal doesn't work despite using the same exact txt file

**Comment by massimoaria** [comment]
Please provide a reproducible example

**Comment by MtWessels** [comment]
I am facing a similar problem as above using the Shiny app. The file preview shows a correct upload of terms to remove from the analysis, but they don't get removed from the Trend Topics plots.

**Comment by massimoaria** [comment]
The issue has been solved in bibliometrix 4.1
