### ISSUE TITLE
How does "synonyms" works...

### ISSUE THREAD

**Issue by DalzAsylum** [massimoaria/bibliometrix#280]
In the "manual" it's written
synonyms is a character vector. Each element contains a list of synonyms, separated by ";", that will be merged into a single term (the first word contained in the vector element). The default is synonyms = NULL

# So before calling for instance a keyword co-occurrences network (cf. code under)

#keyword co_occurence network
NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")
#Plot the network
net=networkPlot(NetMatrix, n = 1000, normalize="association", weighted=T, Title = "Keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,labelsize=0.7)

# I should do like : 

#synonyms list
synonyms= c("keyword 1, keyword 1bis","keyword 2, Keyword 2bis")
#keyword co_occurence network
NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";", synonyms= synonyms) #maybe synonyms= "synonyms" ?
#Plot the network
net=networkPlot(NetMatrix, n = 1000, normalize="association", weighted=T, Title = "Keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,labelsize=0.7)

Sorry, i'm quite new both to R and to bibliometrix, so i think that's an easy solution, but wasnt able to find it with google...

**Comment by DalzAsylum** [comment]
So, self answer, needed to spend something like a couple of more time on it, it's not "well" written in the manual I guess, no error whil writting, for instance (code below)

synonyms = c("cocreation, co-creation", "value co-creation, cocreation of value, co-creation of value, value cocreation", "dominant logic, service dominant logic, service-dominant logic, SDL")
NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";", synonyms= synonyms)

net = networkPlot(NetMatrix, normalize="association", weighted=T, n = 50, Title = "Keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,labelsize=0.7)

BUT, the graph does include the "synonyms" in different
![image](https://user-images.githubusercontent.com/25615339/203088038-5bfd6670-fc17-4b6d-b3a3-553828dab663.png)
So I guess, i "must" rerun the creation of the biblioanalysis or alike ? Or, maybe, synonytms just does not perform what I understood it's doing?

**Comment by massimoaria** [comment]
Hi,
As written in the manual:
**Each element contains a list of synonyms, separated by ";"** (and not by using ",")

This means that the correct definition of the argument synonyms is:
synonyms = c("cocreation; co-creation", "value co-creation; cocreation of value; co-creation of value; value cocreation", "dominant logic; service dominant logic; service-dominant logic, SDL")

**Comment by DalzAsylum** [comment]
That works like a charm, as I'm new to this I did not find out how to properly write the list in R, sorry for that. Thank you for your work and answer!
