### ISSUE TITLE
Annual Growth Rate calculation inconsistent

### ISSUE THREAD

**Issue by TianyaImpression** [massimoaria/bibliometrix#281]
R 4.2.1
bibliometrix 4.0.0

I found that the annual growth rate calculated by bibliometrix is inconsistent in many places, the calculation result in MainInformation is consistent with the calculation result according to the PY field, shiny is consistent with AnnualGrowthRate and inconsistent with MainInformation. Is this a change in the algorithm or what ? Why is Annual Growth Rate different in different places ? Thank you !

![image](https://user-images.githubusercontent.com/22004043/204954064-43fcfa9a-0c5b-4cc1-a902-2186302673cc.png)
![image](https://user-images.githubusercontent.com/22004043/204954084-1e563637-7607-4cdf-a28a-efe9942376b7.png)
![image](https://user-images.githubusercontent.com/22004043/204954289-230687df-7e26-421d-a51e-104277da7dc4.png)
![image](https://user-images.githubusercontent.com/22004043/204954518-42f7b1a9-cccb-4de3-9b67-f30b06211320.png)

**Comment by massimoaria** [comment]
Hi,
thanks for your remark.
The correct calculation is the number provided in biblioshiny. We corrected a bug in summary function to be consistent with the correct formula.
You can update bibliometrix from GitHub
