### ISSUE TITLE
Error in Clustering by Coupling (Biblioshiny) "arguments imply differing number of rows: 0, 1"

### ISSUE THREAD

**Issue by GCamp6** [massimoaria/bibliometrix#284]
I correctly import a raw file downloaded from Lens.org. 

In the "Clustering by Coupling" pane I get the error "arguments imply differing number of rows: 0, 1" with any parameter combination in the fields "Unit of Analysis", "Coupling measured by", "Cluster labeling by"

**Comment by massimoaria** [comment]
The issue has been solved in bibliometrix 4.1
