### ISSUE TITLE
Problem with Scopus CSV an BIB

### ISSUE THREAD

**Issue by phillipeG-ucen** [massimoaria/bibliometrix#288]
I have re-downloaded the data from Scopus, making sure to download all the
metadata.
It still does not identify the titles, so I cannot perform the analyses
that need them.
I have about 4200 data downloaded from the new version of Scopus, both in CSV and BiB.

When I analyze the BIB file, C1, RP, DT, NR, WC are not found. 

![BIB_MissingDataTable-2023-01-13 png (1)](https://user-images.githubusercontent.com/122309204/212383779-fba5c19e-f784-4066-a7a7-be9c89136143.png)

When I analyze  the CSV file, ID, NR, WC, TI are not found.

![CSV_MissingDataTable-2023-01-13 png (1)](https://user-images.githubusercontent.com/122309204/212385005-cabef0b0-b0cd-416c-9bf0-80d5d36d5932.png)

**Comment by massimoaria** [comment]
Unfortunately, the Italian academic subscription for Scopus doesn't allow us to use the new version of the Scopus interface.
Please upload an example collection in bibtex and CSV so I can understand what they changed in their file format.

Massimo

**Comment by phillipeG-ucen** [comment]
Sure

bib:  https://drive.google.com/file/d/1VjYpwMUBYGoMZa16CXDtTRz6iiqguLtA/view?usp=share_link

CSV:  https://drive.google.com/file/d/1bE4Cqfa-XJGeJjgAdARfOAzv9bMMQe_I/view?usp=share_link

**Comment by massimoaria** [comment]
Hi,
based on the two files you uploaded, I corrected the convert2df() function to be able to convert also new Scopus formats.

Please, try it upgrading bibliometrix from GitHub develop branch:

`remotes::install_github("massimoaria/bibliometrix", ref="develop")`
