### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, "TI", value = character(0)) :    replacement has 0 rows, data has 6396

### ISSUE THREAD

**Issue by WizardCake** [massimoaria/bibliometrix#290]
Greetings!

I have a problem merging the df.

Everything is fine reading and converting the files to df (when i run convert2df), but when i use mergeDbSources() function the error message"Error in `$<-.data.frame`(`*tmp*`, "TI", value = character(0)) : replacement has 0 rows, data has 6396" pops up.

Did i do anything wrong? What was that?

I'm sharing some samples of my files to be possible to reproduce my situation

[wos 1001 1500.txt](https://github.com/massimoaria/bibliometrix/files/10427953/wos.1001.1500.txt)
[wos 501 1000.txt](https://github.com/massimoaria/bibliometrix/files/10427954/wos.501.1000.txt)
[wos 1 500.txt](https://github.com/massimoaria/bibliometrix/files/10427955/wos.1.500.txt)
[sample scopus.csv](https://github.com/massimoaria/bibliometrix/files/10428010/sample.scopus.csv)

**Comment by massimoaria** [comment]
The issue has already been solved.
please update bibliometrix from GitHub:
install.packages("remotes")
remotes::install_github("github.com/massimoaria/bibliometrix")

Here, an example with two your files:
![image](https://user-images.githubusercontent.com/16023543/212867441-610842ee-d671-4abc-a90d-0294d89c321e.png)

**Comment by WizardCake** [comment]
Hi!

Thank you for your quick answer. I'm going to uptade right now. Appreciate your great work

**Comment by akinyem3** [comment]
Thank you so much, Massimo, for taking the time to me despite your busy schedule.

I looked at #290 and tried installing the repo from GitHub as advised but encountered this error:

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`github.com`) and repo name (`massimoaria`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

Do I need permission to access the repo?

**Comment by WizardCake** [comment]
Hi, I'm the guy from #290.

Run this code tu update to the git version:

install.packages("remotes")
remotes::install_github("massimoaria/bibliometrix")

This worked to me

**Comment by akinyem3** [comment]
Hi All,

Thank you so much for sharing the codes.
I just installed the codes it works for me as well.

Thank you, Massimo, for the amazing work you are doing.

Your response is much appreciated.

Cheers,
Babatope

Dr. Babatope Akinyemi (he/him/his)
Research Associate
Department of Animal Science
3270C Anthony Hall
Michigan State University
517-402-4012 cell
***@***.******@***.***>


From: WizardCake ***@***.***>
Date: Tuesday, January 17, 2023 at 8:40 AM
To: massimoaria/bibliometrix ***@***.***>
Cc: Akinyemi, Babatope ***@***.***>, Comment ***@***.***>
Subject: Re: [massimoaria/bibliometrix] Error in `$<-.data.frame`(`*tmp*`, "TI", value = character(0)) : replacement has 0 rows, data has 6396 (Issue #290)

Hi, I'm the guy from #290<https://urldefense.com/v3/__https:/github.com/massimoaria/bibliometrix/issues/290__;!!HXCxUKc!x7-qo3Vl0hP_jyctrJKPeN9QPSEduDLUoOaCqnLe0rqvVFJq35mgli93cVCyKinX-9DjhhTYKr38oluVeMT7-xRe$>.

Run this code tu update to the git version:

install.packages("remotes")
remotes::install_github("massimoaria/bibliometrix")

This worked to me
