### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, "TI", value = character(0))   replacement has 0 rows

### ISSUE THREAD

**Issue by akinyem3** [massimoaria/bibliometrix#291]
Hello,

I wanted to convert and merge bibliometrics metadata from the Scopus and WOS databases using the code below:
#The convert2df code below works perfectly. 

file <- "scopus.csv"
d1 <- convert2df(file, dbsource = "scopus", format = "csv")
head(d1["TC"])

file <- "savedrecs.txt"
d2 <- convert2df(file, dbsource = "wos", format = "plaintext")
head(d2["TC"])

#However, the mergeDbSources code below returned the error message shown  below 
M <- mergeDbSources(d1, d2, remove.duplicated=TRUE)

Here is the error message:
# Error in `$<-.data.frame`(`*tmp*`, "TI", value = character(0)) : 
  replacement has 0 rows, data has 528

Please find the attached Scopus and WOS files
[savedrecs.txt](https://github.com/massimoaria/bibliometrix/files/10428467/savedrecs.txt)
[scopus.csv](https://github.com/massimoaria/bibliometrix/files/10428468/scopus.csv)

Your kind suggestion/advice will be highly appreciated.

**Comment by massimoaria** [comment]
take a look to #290

**Comment by akinyem3** [comment]
Thank you so much, Massimo, for taking the time to me despite your busy schedule.

I looked at #290 and tried installing the repo from GitHub as advised but encountered this error:

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`github.com`) and repo name (`massimoaria`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

Do I need permission to access the repo?

Kind regards,
Babatope

Dr. Babatope Akinyemi (he/him/his)
Research Associate
Department of Animal Science
3270C Anthony Hall
Michigan State University
517-402-4012 cell
***@***.******@***.***>


From: Massimo Aria ***@***.***>
Date: Tuesday, January 17, 2023 at 8:27 AM
To: massimoaria/bibliometrix ***@***.***>
Cc: Akinyemi, Babatope ***@***.***>, Author ***@***.***>
Subject: Re: [massimoaria/bibliometrix] Error in `$<-.data.frame`(`*tmp*`, "TI", value = character(0)) replacement has 0 rows (Issue #291)

take a look to #290<https://urldefense.com/v3/__https:/github.com/massimoaria/bibliometrix/issues/290__;!!HXCxUKc!z6MYDIphun-l726jWZabZusBQNnyjTRufsBM53HjHFWy6HOOLAFq4B3su4McD9ll435YA07jfgzKI5VLGuI1TZBv$>
