### ISSUE TITLE
Error with indexing in collaboration network

### ISSUE THREAD

**Issue by michaelhlew** [massimoaria/bibliometrix#292]
Problem: the collaboration network by country does not seem to work for bibliometric data frames that have been merged together using the mergeDbSources() function. 

When I use the individual bibliometric data frames I am able to load the country collaboration network. However, if I use the merged bibliometrics data frame I get an invalid indexing error. 

The specific error I get is: Warning: Error in E<-: invalid indexing

Again, this only seems to be a problem for bibliometric data frames that have been merged together. 

Path to what I am using: biblioshiny > social structure > collaboration network on country

**Comment by michaelhlew** [comment]
For example -- 

combined <- mergeDbSources(scopus1, scopus2, scopus3, scopus4)

the collaboration network will not load if I run it on "combined". However, it will load if I run it on "scopus" 1-4.

**Comment by massimoaria** [comment]
We know the problem.
At the moment, the merging function works only for metadata involving content (abstract, title and keywords).
We are working on improving support for other metadata.
