### ISSUE TITLE
biblioanalysis function problem to use dimensions database

### ISSUE THREAD

**Issue by ferck** [massimoaria/bibliometrix#295]
Bibliometrix 4.0.1
R 4.2.2

HI everyone, 
I'm working in an bibliometric analysis and I need Dimensions results. However, after last update dimensions database cannot  be read by biblioanalysis function with next error when i imported the data depending if it is full record, or if it is a bibliometric map record .

IF I use full record error instead is "Error in df$Country[i] <- co : replacement has length zero"
For second case error is "Error in strsplit(M$AU_CO, sep) : non-character argument"

using this code:

resultdim <- biblioAnalysis(df, sep = ";")

Do you know about any bug or I'm doing something wrong? Until december 2022 I can use dimensions, but know i can load and convert data using convert2df just with this warning that apparently didn't affect data load, but i can´t continue to the next step.

Warning when data is load with convert2df
"Converting your dimensions collection into a bibliographic dataframe

Rows: 164 Columns: 15                                                                                                            
── Column specification ──────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (13): Publication ID, DOI, Title, Abstract, Source title/Anthology title, Volume, Issu...
dbl  (2): PubYear, Times cited

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Done!
"
What can i do?

I attached CSV and XLSX files to make error reproducible

THX. 

[Dimensions_2023-19-20-09.csv](https://github.com/massimoaria/bibliometrix/files/10489003/Dimensions_2023-19-20-09.csv)
[Dimensions_2023-19-20-26.xlsx](https://github.com/massimoaria/bibliometrix/files/10489004/Dimensions_2023-19-20-26.xlsx)

**Comment by massimoaria** [comment]
The issue has been solved.
