### ISSUE TITLE
Error in thematic evolution

### ISSUE THREAD

**Issue by evrimyanar** [massimoaria/bibliometrix#305]
Hello,

I am trying to run a thematic evolution analysis on biblioshiny, and I get different results each time although I put the same parameters. I took a screen recording of the issue that you access through the link below. 

https://drive.google.com/drive/folders/1D56OvTVovCikdCQqbd1-tdGEgJcQKVko?usp=share_link

I was wondering if we can access the old version of the package.

**Comment by massimoaria** [comment]
Please update the package and take a look at this thread:
https://github.com/massimoaria/bibliometrix/issues/259

**Comment by evrimyanar** [comment]
Many thanks, the problem is solved with the walktrap algorithm.
