### ISSUE TITLE
Name changes for maps not working as intended

### ISSUE THREAD

**Issue by thimacek** [massimoaria/bibliometrix#308]
https://github.com/massimoaria/bibliometrix/blob/4675f9e577218413c7eb74256465ddcffef94478/inst/biblioshiny/server.R#L4321

I've been looking at the code for the Country Productivity and Country Collaboration maps in the shiny server, and I noticed a few issues in the name changes done while trying to replicate the maps on R with a dataset I'm using (which uses Web of Science data). 

For the Country Productivity map, the Web of Science country names for two countries I had in my dataset didn't match those in the maps (map_data function) database: "MACEDONIA" in WoS data is "NORTH MACEDONIA" in the map_data database, and "U ARAB EMIRATES" in WoS data is "UNITED ARAB EMIRATES" in the 'map_data' database. There may be other cases in which the names don't match - it might be worth explicitly verifying how WoS (and other data sources) name countries to make sure the functions cover all necessary cases.

For the Country Collaboration map, where changes are applied to the country names in the 'map_data' database, in addition to the problems above there's also an issue with how you're changing "UK" to "UNITED KINGDOM". 

Since you're using 

map.world$region=gsub("UK","UNITED KINGDOM",map.world$region)

you end up also changing any other names starting with 'UK'. Specifically, that ends up changing 'UKRAINE' to "UNITED KINGDOMRAINE". 

A quick fix for that is to change the gsub for 'UK' to anchor the expression to the start and end of a string:

map.world$region=gsub("^UK$","UNITED KINGDOM",map.world$region)

I didn't run into any similar problems elsewhere, but I believe it might be a good idea to anchor country names in general to prevent other such problems.

Thanks for all the work on bibliometrix!

Kind regards

**Comment by massimoaria** [comment]
Thanks a lot for your help in improving the package.
I just solved the issue integrating your suggestions.
