### ISSUE TITLE
`tibble::as.data.frame.tbl_df()` and the `row.names` argument

### ISSUE THREAD

**Issue by krlmlr** [massimoaria/bibliometrix#314]
The current CRAN version of tibble ignores the `row.names` argument, but we are considering making use of it in an updated version of tibble. Your package seems to call `as.data.frame()` on a tibble object with the `row.names` argument set to an invalid value. This is most likely an error or omission.

To reproduce, please install the relevant tibble PR via

```r
pak::pak("tidyverse/tibble#1507")
```

See https://github.com/tidyverse/tibble/pull/1507 for details. Please let me know if I'm missing anything.

**Comment by massimoaria** [comment]
Solved
