### ISSUE TITLE
The parameter remove.terms in thematicEvolution() is not working

### ISSUE THREAD

**Issue by mancebral** [massimoaria/bibliometrix#315]
I am working in windows 10 with R.4.2.2 and bibliometrix 4.0.1 and I am trying to apply the function thematicEvolution but removing some of the terms, particulary, because they appear very often in the sample, and I would like to view with more detail how the maps would be created wwithout them. 

I created a vector firstly to store the words (in this case are author keywords) as following:

`remove.terms.1word = c("LOVE", "love")`

And then I apply the parameter over the function. However, ther terms continue appearing:
  
```
loveEvolution <- thematicEvolution(M22Clean, 
                                   field = "DE", 
                                   years = c(2000, 2008, 2016), 
                                   remove.terms = remove.terms.1word,
                                   n= 150, 
                                   minFreq = 6,
                                   n.labels = 3,
                                   stemming = TRUE)
```
![Rplot](https://user-images.githubusercontent.com/32591227/222927233-a537dcbf-2404-41d9-86a2-5ae27b243e46.png)

Thanks for the help!

**Comment by massimoaria** [comment]
Hi,
we solved the issue in the last version.
