### ISSUE TITLE
Three Fields Plot (Sankey Diagram) Exports

### ISSUE THREAD

**Issue by Maghsad** [massimoaria/bibliometrix#325]
Hi,

Could you please advise me using Bibliometrix, how can I export the connected elements to each item in Three Fields Plot (Sankey Diagram) to a CSV file (I need an R code)?

**Example**: for the first item in middle (bibliographic coupling) I want to export the references on the left side (small h, 1973 ... and kessler mm, 1956 ... ). Also, I want to export the list of items on the right side connected to this item (science, networks, indicators).  Here is the R code for this Three Fields Plot:
```
library(bibliometrix)
data(scientometrics, package = "bibliometrixData")
threeFieldsPlot(scientometrics, fields=c("CR","DE","ID"),n=c(5,5,5))
```

<img src="https://i.ibb.co/L61nrxP/SCR-20230307-gjv.png">

**Comment by massimoaria** [comment]
Unfortunately,
it is not possible to do that (for the moment...)
