### ISSUE TITLE
Error in networkPlot() when plotted using Vosviewer

### ISSUE THREAD

**Issue by xiangx898** [massimoaria/bibliometrix#33]
Hello, I  run into problems again.

When I input the codes below:
> NetMatrix <- biblioNetwork(M, analysis = "collaboration", network = "authors", sep = ";")
> net <- networkPlot(NetMatrix, n=30, type="vosviewer", Title = "Authors collaboration", labelsize = 0.5)
Error in networkPlot(NetMatrix, n = 30, type = "vosviewer", Title = "Authors collaboration",  : 
  object 'bsk.network1' not found
The vosviewer is executed, but an error occurs and there is no connection between nodes.
![wechat screenshot_20190121110720](https://user-images.githubusercontent.com/40451945/51451098-a5fdea00-1d6e-11e9-98fc-3420d912a1a0.png)

However, in another case, when I put the codes below:
>NetMatrix <- biblioNetwork(M,analysis = "co-citation", network = "references",sep = ";")
> net <- networkPlot(NetMatrix, n=30, Title = "Co-Citation Network", type = "vosviewer",size = T, remove.multiple = FALSE, edgesize = 5, labelsize = 0.9)
Error in networkPlot(NetMatrix, n = 30, Title = "Co-Citation Network",  : 
  object 'bsk.network1' not found
The vosviewer is executed and the network is plotted correctly, but the error still occurs.
![wechat screenshot_20190121110741](https://user-images.githubusercontent.com/40451945/51451107-ae562500-1d6e-11e9-9671-92248335da33.png)

I installed bibliometrix from CRAN a few days ago and the vosviewer is the version 1.6.10 released on January 10, 2019.
How to solve this issue and plot networks correctly in Vosviewer?

**Comment by massimoaria** [comment]
Please, send me your collection to replicate the issue.


Meanwhile, you could use biblioshiny(), the shiny web interface included in bibliometrix.


It creates dynamic network plots that can be eventually saved into pajek format and opened by vosviewer.








On Mon, Jan 21, 2019 at 4:28 AM +0100, "pheobe.xiang" <notifications@github.com> wrote:












Hello, I  run into problems again.


When I input the codes below:



NetMatrix <- biblioNetwork(M, analysis = "collaboration", network = "authors", sep = ";")

net <- networkPlot(NetMatrix, n=30, type="vosviewer", Title = "Authors collaboration", labelsize = 0.5)

Error in networkPlot(NetMatrix, n = 30, type = "vosviewer", Title = "Authors collaboration",  :

object 'bsk.network1' not found

The vosviewer is executed, but an error occurs and there is no connection between nodes.





However, in another case, when I put the codes below:



NetMatrix <- biblioNetwork(M,analysis = "co-citation", network = "references",sep = ";")

net <- networkPlot(NetMatrix, n=30, Title = "Co-Citation Network", type = "vosviewer",size = T, remove.multiple = FALSE, edgesize = 5, labelsize = 0.9)

Error in networkPlot(NetMatrix, n = 30, Title = "Co-Citation Network",  :

object 'bsk.network1' not found

The vosviewer is executed and the network is plotted correctly, but the error still occurs.





I installed bibliometrix from CRAN a few days ago and the vosviewer is the version 1.6.10 released on January 10, 2019.

How to solve this issue and plot networks correctly in Vosviewer?

**Comment by xiangx898** [comment]
Hello, my collection has showed in #29 .
Thank you.

**Comment by massimoaria** [comment]
I solved the issue "object 'bsk.network1' not found".

Regarding the missing links in VOSviewer, links are not missing but are not visible because many nodes are collapsed. Try to zoom the graph or update the layout choosing "no normalization method" in the top left menu "Analysis" of VOSviewer.
![image](https://user-images.githubusercontent.com/16023543/51543181-49c5c380-1e5d-11e9-9e4e-f0f597b96c27.png)

**Comment by xiangx898** [comment]
Thanks for your kindly help and sharing!
