### ISSUE TITLE
missing Cited References in Biblioshiny (SCOPUS.bib) 

### ISSUE THREAD

**Issue by Koblianska** [massimoaria/bibliometrix#330]
Hi, 
I've downloaded a bib file from scopus with full metadata but have a resulting error: completely missing CR, NR, and critical for ID (76,92% missing). I see references in the bib file opened via the text editor. What should I do to fix this? 
P.S. I've opened the file already analysed successfully via Biblioshiny earlier (in an old interface) but had the same problem: completely missing CR, NR, and critical for ID

Thank you in advance for the suggestion!
<img width="1315" alt="Снимок экрана 2023-03-20 в 23 50 00" src="https://user-images.githubusercontent.com/125991259/226475201-03065780-28dd-47e9-b159-4b37dbc66e65.png">
<img width="1315" alt="Снимок экрана 2023-03-20 в 23 50 15" src="https://user-images.githubusercontent.com/125991259/226475221-ad94647d-6cc4-4723-ab90-6ce1d1d1dba9.png">

**Comment by massimoaria** [comment]
Hi,
Cited references are correctly identified. 
Looking at the fourth row of the table you can read "CR - Cited references 0 missing Status: Excellent".
Info about the number of references and WC is not included in the Scopus file format.
