### ISSUE TITLE
bibliometrix issue

### ISSUE THREAD

**Issue by najeeb-al01** [massimoaria/bibliometrix#332]
Dear Bibliometric Support Team,

I am writing to inform you that I am encountering two issues while using your application. I hope that you can assist me in resolving these issues urgently.

Firstly, I have noticed that when I export data from Scopus in BibTeX format and import it into Bibliometric, the application displays a different image (image number one) than the one associated with the original data. I am not sure why this is happening, and I would appreciate it if you could investigate the issue and provide me with a solution.

Secondly, when I use the combined file feature in your application, a different image (image number two) appears, which is not consistent with the data I have inputted. This is causing confusion, and I need your help to resolve this problem as soon as possible.

I would be grateful if you could provide me with a solution to these issues, as I need to use your application to complete my work. Please let me know what steps I can take to resolve these problems, or if there is anything you can do to help me.

The error I got is:
Please note that our software is open source and available for use, distributed under the MIT license.
When it is used in a publication, we ask that authors properly cite the following reference:

Aria, M. & Cuccurullo, C. (2017) bibliometrix: An R-tool for comprehensive science mapping analysis, 
                        Journal of Informetrics, 11(4), pp 959-975, Elsevier.

Failure to properly cite the software is considered a violation of the license.

![Image 1](https://user-images.githubusercontent.com/128687671/227151989-aec0d8b1-e2ae-4366-aa86-df5a03f41ea7.png)
![Image 2](https://user-images.githubusercontent.com/128687671/227152000-15804b0c-6148-4abe-874d-a085fa5d7d30.png)

**Comment by jhoncaicedossb** [comment]
Dear Bibliometrix technical support team.
This bug is also present in the new version (4.1.2); it does not allow to analyse of data (Scopus, WoS, combined database).
While in previous versions (e.g., 4.0.1), it allows for analysis. Please consider fixing this bug.
Regards.

**Comment by massimoaria** [comment]
Please upload your file.
