### ISSUE TITLE
Error: reached elapsed time limit

### ISSUE THREAD

**Issue by WalidMerrouche** [massimoaria/bibliometrix#334]
Hello sir, 
I always get this message whenever I use the package. I tried several CSV files that contain between 58 to more than 900 documents which were downloaded from the Scopus database.
However, I never encountered a problem when performing different analyses with the package. 
![Capture d’écran 2023-03-30 022914](https://user-images.githubusercontent.com/71950088/228704586-d5539c56-d1e3-4872-9eb2-022d23bdfb77.png)

**Comment by massimoaria** [comment]
The error is due to a slow internet connection. The app cannot reach our server to download new messages into an acceptable time.
You can simply ignore the message. it does not affect the analyses.
