### ISSUE TITLE
The extension Buttons does not exist

### ISSUE THREAD

**Issue by JamesMPM** [massimoaria/bibliometrix#335]
Hi,

I upload scopus file (see file attached) (both in .bib and -csv formats) in bibliometrix and get the following message:

**The extension Buttons does not exist**

[scopus (19).csv](https://github.com/massimoaria/bibliometrix/files/11124065/scopus.19.csv)

Please advise, thanks.

**Comment by massimoaria** [comment]
Please report the script using reprex.

**Comment by massimoaria** [comment]
You file works perfectly on my pc both using bibliometrix convert2df() function and biblioshiny web-app:

``` r
library(bibliometrix)
#> Please note that our software is open source and available for use, distributed under the MIT license.
#> When it is used in a publication, we ask that authors properly cite the following reference:
#> 
#> Aria, M. & Cuccurullo, C. (2017) bibliometrix: An R-tool for comprehensive science mapping analysis, 
#>                         Journal of Informetrics, 11(4), pp 959-975, Elsevier.
#> 
#> Failure to properly cite the software is considered a violation of the license.
#>                         
#> For information and bug reports:
#>                         - Take a look at https://www.bibliometrix.org
#>                         - Send an email to info@bibliometrix.org   
#>                         - Write a post on https://github.com/massimoaria/bibliometrix/issues
#>                         
#> Help us to keep Bibliometrix and Biblioshiny free to download and use by contributing with a small donation to support our research team (https://bibliometrix.org/donate.html)
#> 
#>                         
#> To start with the Biblioshiny app, please digit:
#> biblioshiny()
file="/Users/massimoaria/Downloads/scopus.19.csv"

M <- convert2df(file=file, dbsource="scopus", format="csv")
#> 
#> Converting your scopus collection into a bibliographic dataframe
#> 
#> Done!
#> 
#> 
#> Generating affiliation field tag AU_UN from C1:  Done!
```

<sup>Created on 2023-04-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


<img width="1472" alt="image" src="https://user-images.githubusercontent.com/16023543/231099028-cc5b4783-2b5b-417b-b11f-7572639225f0.png">

**Comment by JamesMPM** [comment]
> Please report the script using reprex.

biblioshiny()
Loading required package: shiny
Warning: package ‘shiny’ was built under R version 4.1.3

Listening on http://127.0.0.1:5928
Warning: package ‘igraph’ was built under R version 4.1.3
Warning: package ‘ggplot2’ was built under R version 4.1.3
Warning: package ‘ggmap’ was built under R version 4.1.3
Warning: package ‘maps’ was built under R version 4.1.3
Warning: package ‘visNetwork’ was built under R version 4.1.3
Warning: package ‘plotly’ was built under R version 4.1.3
Warning: package ‘fontawesome’ was built under R version 4.1.3
Warning: package ‘shinydashboardPlus’ was built under R version 4.1.3
Warning: package ‘shinydashboard’ was built under R version 4.1.3
Warning: package ‘shinyjs’ was built under R version 4.1.3
Warning: package ‘shinyscreenshot’ was built under R version 4.1.3
Warning: package ‘openxlsx’ was built under R version 4.1.3
Warning: package ‘shinyWidgets’ was built under R version 4.1.3
Warning: package ‘Matrix’ was built under R version 4.1.3
Warning: package ‘dimensionsR’ was built under R version 4.1.3
Warning: package ‘dplyr’ was built under R version 4.1.3
Warning: package ‘tidyr’ was built under R version 4.1.3
Warning: package ‘sparkline’ was built under R version 4.1.3
Warning: package ‘tidygraph’ was built under R version 4.1.3
Warning: package ‘ggraph’ was built under R version 4.1.3
Error in utils:::readCitationFile("C:/Program Files/RStudio/resources/app/resources/CITATION") : 
  reached elapsed time limit

Converting your scopus collection into a bibliographic dataframe

Done!                                                                                                      


Generating affiliation field tag AU_UN from C1:  Done!

Warning: Error in FUN: The extension Buttons does not exist
  108: formatColumns
  107: formatStyle
  105: exprFunc [D:\OneDrive - Universidad Tecnológica de Bolívar\Documentos\R\win-library\4.1\bibliometrix\biblioshiny/server.R#480]
  104: widgetFunc
  103: ::
htmlwidgets
shinyRenderWidget
  102: func
   89: renderFunc
   88: renderFunc
   84: renderFunc
   83: output$contents
    2: runApp
    1: biblioshiny
Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'dt-core-1.10.20'; `directoryPath` = ''
  113: stop
  112: value[[3L]]
  111: tryCatchOne
  110: tryCatchList
  109: tryCatch
  108: addResourcePath
  107: FUN
  106: lapply
  105: renderWidget
  104: transform
  103: func
  101: f
  100: Reduce
   91: do
   90: hybrid_chain
   89: renderFunc
   88: renderFunc
   84: renderFunc
   83: output$missingDataTable
    2: runApp
    1: biblioshiny

**Comment by JamesMPM** [comment]
@massimoaria , Thanks for your support. I just copied this from the console, I don´t know how to report the script using "reprex". Thanks and hope this helps.
