### ISSUE TITLE
Getting "non-character argument" error while trying to generate overview of information

### ISSUE THREAD

**Issue by mirAamirr** [massimoaria/bibliometrix#336]
I am trying to analyse a scopus csv with biblioshiny. The data is converted easily but then I get the above mentioned error while viewing the overview.
The R output is following:
Warning: Error in strsplit: non-character argument
  112: strsplit
  100: ValueBoxes [utils.R#274]
   99: vbox_fun [C:\Users\miraa\AppData\Local\R\win-library\4.2\bibliometrix\biblioshiny/server.R#1003]
   98: renderUI
   97: func
   84: renderFunc
   83: output$Timespan
    2: runApp
    1: biblioshiny

The output screen is also attached below
<img width="660" alt="output screen" src="https://user-images.githubusercontent.com/36182604/229271423-32788b0c-138b-41c9-9339-d4567ca2bb8e.png">

The source datafile is below:
[dataa.csv](https://github.com/massimoaria/bibliometrix/files/11128699/dataa.csv)

**Comment by massimoaria** [comment]
Hi, your files misses many metadata as you can see from the import report:

![MissingDataTable-2023-04-03 png](https://user-images.githubusercontent.com/16023543/229449558-f6b1160b-5f2c-4db3-9399-da1bb8855914.png)

This means that many analyses cannot be performed.

Moreover, overview works fine using the latest version of biblioshiny from GitHub:
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/16023543/229449064-923d2950-112b-4821-b124-b3cb1a0bc996.png">

**Comment by mirAamirr** [comment]
I had an old file which was working fine. I copied all the new data to old file and the old file works like a charm but the new file gives the error. Very strange.

Appreciate your efforts to give time to my query. Also, thank you for providing a great library :)
Have a nice time.
