### ISSUE TITLE
Error: Problem while computing `..1 = across(where(is.character), tidyr::replace_na, "")`

### ISSUE THREAD

**Issue by AliHudzaifi** [massimoaria/bibliometrix#338]
I have been facing this issue Error: Problem while computing `..1 = across(where(is.character), tidyr::replace_na, "")` when I upload Scopus CSV file into RBiblioshiny apps.

Please do let me know to solve this issue.

Thank you,

Ali.

**Comment by massimoaria** [comment]
please upload here your csv scopus file

**Comment by AliHudzaifi** [comment]
Dear Prof,

The issue has been solved. I use another PC to run the analysis and it just went well. I guess the problem now is with my PC. I think I need to re-install R Studio.

Anyway, thank you very much for your response.
