### ISSUE TITLE
WoS import issues

### ISSUE THREAD

**Issue by maria-pro** [massimoaria/bibliometrix#339]
Hi, 
i have several issues trying to import a file from WoS.
1. There is no bib option available now in WoS
2. Tried using "plaintext" and Endnote formats to get this warning and error (I don't think it is related to the format but rather looks like WoS changed the export fields and they are not updated in the package):

Missing fields:  DE C1 RP CR 
Error in `$<-.data.frame`(`*tmp*`, "C1", value = character(0)) : 
  replacement has 0 rows, data has 42

To replicate you can use any of the files here https://github.com/maria-pro/lit_review/tree/master/test_data_WoS

with 

M <- convert2df(file = ma_ref, 
                dbsource = "isi", format = "endnote")

**Comment by massimoaria** [comment]
Hello,
The export formats available on WoS have not changed (see the image below):

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/16023543/234920288-58c271e3-628a-4e94-8146-81eb3ede3b9d.png">

Here, I selected "PlainText" format (the txt file you send me wasn't a plaintext but a TAB format) and then selected "Full Record and Cited References" as Record Content argument:

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/16023543/234921105-97d50f93-2e90-45e7-b8b2-444f41f9b7b8.png">
