### ISSUE TITLE
Error with collaboration network: duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by yavvictoria** [massimoaria/bibliometrix#342]
Hi! 

I'm trying to run a collaboration network analysis (for authors, affiliations and countries) in biblioshiny and this error occurs: duplicate 'row.names' are not allowed.

Everything worked perfectly with the same dataset (4872 records) before I updated the package. How could I solve the problem?

Thank you very much in advance!

Kind regards,
Victoria

**Comment by massimoaria** [comment]
Please upload your file so I can try to solve the issue.

**Comment by yavvictoria** [comment]
Hello @massimoaria! Does the link to the database work?

Could you please indicate the way to work around this issue?

Kind regards,
Victoria

**Comment by massimoaria** [comment]
Hi, I have just solved the issue.
Please update bibliometrix from GitHub running the following lines:

` install.packages("remotes")         

   remotes::install_github("massimoaria/bibliometrix")`
