### ISSUE TITLE
Local citation score: how does it work?

### ISSUE THREAD

**Issue by yavvictoria** [massimoaria/bibliometrix#343]
Hi!

I'm attempting to clean up the reference column (CR) in the database in order to produce reliable results for the local citations (authors and papers). What do the functions look for in the reference column in order to identify a citation?

We tried to change references for the short citation that is kept in the database already (column SR) and the algorithm doesn't see these references for papers anymore. 

For authors, it's particularly tricky as we refined authors in the database (harmonized spelling and differentiated duplicates in AU column) but this disharmony still persists in references (CR). 

Thank you very much in advance!

Kind regards,
Victoria

**Comment by massimoaria** [comment]
It depends on the source database.
For WoS, DOIs are used since these are also present in the CR field.
For Scopus, references do not report DOIs so the publication title and journal are used.

**Comment by yavvictoria** [comment]
Hello!

I looked into the code and for scopus, it was a title and a publication year, not a journal.
