### ISSUE TITLE
Warning: Error in $<-.data.frame

### ISSUE THREAD

**Issue by amesassy** [massimoaria/bibliometrix#347]
Hello!
I get an error when I want to execute the file in "txt" format. The error is "Error in $<-.data.frame: replacement has 0 rows, data has 40".
I attach screenshot and file downloaded from WoS.
I remain attentive and thank you very much.
Regards
[bibliometrix-1.txt](https://github.com/massimoaria/bibliometrix/files/11391496/bibliometrix-1.txt)
![warning-1](https://user-images.githubusercontent.com/823096/236058321-fc99b24a-536b-4adb-b12d-946a9fec6b3e.png)

**Comment by massimoaria** [comment]
Your txt file misses of many mandatory metadata. That's why it is not possible to import it.

Please read carefully the tutorial about how to import data in bibliometrix published on our website.
