### ISSUE TITLE
Error: arguments imply differing number of rows: 0, 79

### ISSUE THREAD

**Issue by FTamas77** [massimoaria/bibliometrix#350]
I want to open a .bib file which was exported from Mendeley Reference Manager.
I've a fresh R Studio install and fresh bibliomterix.
I've this error: 
Error: arguments imply differing number of rows: 0, 79

And the 79 is the number of records.

I opened the .bib and everything is there:

@article{Gira...18,
   abstract = {[The ....most.]},
   author = {Pat...plett},
   issn = {00...0964},
   issue = {4},
   journal = {Sy...se},
   pages = {16...3},
   publisher = {S.....er},
   title = {Priori......asoning},
   volume = {195},
   url = {http.....708},
   year = {20...8},
}

Paper from IEEE Xplore, Scopus, JSTOR

**### I checked the logs too:**

Converting your scopus collection into a bibliographic dataframe

                                                                                                                                  
Warning:
In your file, some mandatory metadata are missing. Bibliometrix functions may not work properly!

Please, take a look at the vignettes:
- 'Data Importing and Converting' (https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html)
- 'A brief introduction to bibliometrix' (https://www.bibliometrix.org/vignettes/Introduction_to_bibliometrix.html)

Missing fields:  AU DE ID C1 CR 
Warning: Error in data.frame: arguments imply differing number of rows: 0, 79

**Comment by massimoaria** [comment]
Actually, Mendeley bibtex files are not supported by bibliometrix.

As reported in the warning message, please look at this tutorial explaining what file format you can import in bibliometrix:
https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html
