### ISSUE TITLE
related to issue #25

### ISSUE THREAD

**Issue by maria-pro** [massimoaria/bibliometrix#352]
I am having the same error with my dataset 
Error in if (V(bsk.network)$community[x[1]] == V(bsk.network)$community[x[2]]) 

NetMatrix <- biblioNetwork(M, analysis = "co-citation", network = "references", sep = ";")
net=networkPlot(NetMatrix, n = 50, Title = "Co-Citation Network", type = "fruchterman", size.cex=TRUE, size=20, remove.multiple=FALSE, labelsize=1,edgesize = 10, edges.min=5)

This is [M dataset](https://github.com/maria-pro/medit_food/blob/main/netmatrix_error.csv)

**Comment by massimoaria** [comment]
Hi,
Only 5 documents in your dataset contain information about references. Obviously, this makes it impossible to do a co-citation analysis!

`sum(M$CR=="none")
[1] 4704`
