### ISSUE TITLE
Non-character argument error when loading Dimensions data

### ISSUE THREAD

**Issue by dromito** [massimoaria/bibliometrix#361]
R version 4.2.3, using Biblioshiny. Received "Error: non-character argument" message when trying to start the attached Dimensions output file.

[Dimensions-Publication-2023-06-16_18-41-19.csv](https://github.com/massimoaria/bibliometrix/files/11773550/Dimensions-Publication-2023-06-16_18-41-19.csv)

**Comment by massimoaria** [comment]
Hi,

I have just added a commit that solves the issue.
Dimensions changed CSV format and now the function convert2df is able to import the new bibliographic record.
