### ISSUE TITLE
 Error:duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by akinyem3** [massimoaria/bibliometrix#369]
I am currently encountering the error: duplicate 'row.names' are not allowed and I realized the error has not been addressed in the FAQs. Any advice on how this error can be resolved will be appreciated

**Comment by massimoaria** [comment]
Please provide a reproducible example using Reprex

**Comment by DrMattG** [comment]
I have the same issue. It is hard to give you a reproducible example but here I try my best! 

I have put the data and script on this [repo](https://github.com/DrMattG/BiblioNINA/tree/main). I attempted to bring in two datasets and deduplicate them using the mergeDBSources function. Using the original (M1 or M2) works - the merged version gives this error: 

"Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed"

``` 
library(bibliometrix)
path <- paste0(here::here(),"/data/bibliometrix_data")
files<-list.files(path = path, pattern="*).bib", full.names = TRUE)
M1 <- convert2df(files, dbsource = "wos", format = "bibtex")
files2<-list.files(path = path, pattern="*.csv", full.names = TRUE)
M2 <- convert2df(files2, dbsource = "lens", format = "csv")
M <- mergeDbSources(M1, M2, remove.duplicated=TRUE)
A <- cocMatrix(M, Field = "SO", sep = ";")
row.names(M)
any(duplicated(rownames(M)))
```

**Comment by akinyem3** [comment]
Hello,

Thanks for resolving the issue. I will try and reinstall bibliometrix from the github and keep you posted.
Again, thanks for resolving the issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DrMattG** [comment]
Perfect! Thank you so much
