### ISSUE TITLE
Error in open.connection(5L, "rb") : 

### ISSUE THREAD

**Issue by felixaraj** [massimoaria/bibliometrix#370]
When convert2df function is used, I get the following error -

M <- convert2df(file=files, dbsource = 'wos', format = "plaintext")

Converting your wos collection into a bibliographic dataframe

**Error in open.connection(5L, "rb") : 
  Timeout was reached: [www.bibliometrix.org] Connection timeout after 10005 ms**

Regards

**Comment by massimoaria** [comment]
Please provide a reproducible example using reprex
