### ISSUE TITLE
Error loading biblioshiny

### ISSUE THREAD

**Issue by ricardovargash** [massimoaria/bibliometrix#371]
Good morning, the application of biblioshiny, this presented an error, ¿how can you solve?, I leave the screenshots

Thanks so much

![error biblioshiny2](https://github.com/massimoaria/bibliometrix/assets/127892573/ea83a919-a22b-4b89-9a60-82a2cbf88754)
![error biblioshiny](https://github.com/massimoaria/bibliometrix/assets/127892573/d72fc596-3504-4286-afc4-d826b53a89d7)

**Comment by massimoaria** [comment]
Looking at your error message, I think one or more packages are missing from your installation.

Please install "jquerylib" package and retry.

**Comment by ricardovargash** [comment]
> Looking at your error message, I think one or more packages are missing from your installation.
> 
> Please install "jquerylib" package and retry.

good morning professor, thanks for your answer, I installed the missing jquerylib package and the problem is solved, thanks for your help.
