### ISSUE TITLE
Biblioshiny Most Local Cited Sources function analyzing authors not sources from Scopus

### ISSUE THREAD

**Issue by hayesb** [massimoaria/bibliometrix#374]
When I load the included Scopus export file (includes References) in Biblioshiny and run the Most Local Cited Sources function the plot/table generated lists author names with corresponding citing articles rather than sources and citing articles.  Please advise.
[Pubs4Biblioshiny-Scopus-534-WithReferences-RefAnalysisIssues.csv](https://github.com/massimoaria/bibliometrix/files/12328224/Pubs4Biblioshiny-Scopus-534-WithReferences-RefAnalysisIssues.csv)

**Comment by bondif** [comment]
I have the same issue

**Comment by massimoaria** [comment]
Recently, Scopus has changed its cited reference format and now it is not longer possible to automatically extract source names from bibliographies.
Next bibliometrix/biblioshiny version will include a new dynamic menu that, based on the initial check on imported data, will automatically hide analyses that cannot be performed.

You can try it (in beta version) downloading the package from GitHub:

```
 install.packages("remotes")         
 remotes::install_github("massimoaria/bibliometrix")
```

**Comment by bondif** [comment]
Thanks for the clarification.
