### ISSUE TITLE
Thematic evolution plots: server error

### ISSUE THREAD

**Issue by yavvictoria** [massimoaria/bibliometrix#379]
Hi!

I was trying to download a plot for the thematic evolution and it constantly gives a server error (I reinstalled the package multiple times already, my network is also fine). Screenshot attached.

Interestingly, it seems to be an issue only for this analysis, as I've downloaded thematic map without any problems.

I use chrome, if that's of any issue.

Would really appreciate any help!

Kind regards,
Victoria

![Screenshot 2023-08-18 at 19 33 14](https://github.com/massimoaria/bibliometrix/assets/122989812/cbb4aed1-fc85-4461-a55f-bce16f33db39)

**Comment by massimoaria** [comment]
The feature works fine on my pc.

<img width="1352" alt="image" src="https://github.com/massimoaria/bibliometrix/assets/16023543/95761a18-1d57-41a4-abf1-472f10df5153">

Please try to upgrade bibliometrix to last version through GitHub.
