### ISSUE TITLE
`biblioAnalysis()` treats the same author with a different punctuation style differently

### ISSUE THREAD

**Issue by jooyoungseo** [massimoaria/bibliometrix#38]
I have found that the current `biblioAnalysis()` function categorizes the same author with a different punctuation style into two different individuals.

For example, there is "John Smith" denoted with Smith J. in journal A; Smith J in journal B.
Even though "Smith J" and "Smith J." are the same person, the internal function of bibliometrix counts them towards two different individuals just because of the punctuation (.).
Would there be anyway to identify the same individual regardless of their punctuation?

**Comment by massimoaria** [comment]
Please send me your collection and your script.

**Comment by jooyoungseo** [comment]
I am sorry, the issue caused by `citations()` function specifically. Please refer to the following reproducible R code:

``` r
## ----bibliometrix loading------------------------------------------------
suppressPackageStartupMessages(library(bibliometrix))

## ----Data loading--------------------------------------------------------
D <- readFiles("http://jooyoungseo.com/test.bib")

## ----Data converting-----------------------------------------------------
M <- convert2df(D, dbsource = "isi", format = "bibtex")

## ----Author citation-----------------------------------------------------
## "STAHL G" and "STAHL G." are the same author but counted towards two different individuals as in "SCARDAMALIA M" and "SCARDAMALIA M."
CR <- citations(M, field = "author", sep = ";")
cbind(CR$Cited[1:10])
```

**Comment by massimoaria** [comment]
Solved

**Comment by jooyoungseo** [comment]
Fantastic! Thank you very much for your hard work!!
