### ISSUE TITLE
Any plans for OpenAlex?

### ISSUE THREAD

**Issue by HCSS-StratBase** [massimoaria/bibliometrix#380]
It's getting to be a great collection and we can get quite nice jsonl-files that may be easier to import into Bibliometrix than some others. Just a thought!

**Comment by HCSS-StratBase** [comment]
I tried [this](https://docs.ropensci.org/openalexR/reference/oa2bibliometrix.html). But I seemingly can't make this work with the latest 'development' version of bibliometrix... Any pointers anybody?

**Comment by massimoaria** [comment]
We are working on it.
If you download the last github version, you can start to work with it (not all functionalities).
convert2df accepts openalex data frame and also historiograph and local citations routine have been updated.
Now also biblioshiny works (but not completely) with OpenAlex .RData files.

**Comment by HCSS-StratBase** [comment]
Thanks Massimo! We'll try tomorrow...

**Comment by sdspieg** [comment]
We managed to make it work. Thanks much!
