### ISSUE TITLE
I can not load csv file directly download from lens.org. Thank you for your help in advance!

### ISSUE THREAD

**Issue by Jovie1030** [massimoaria/bibliometrix#384]
I can not load csv file directly download from lens.org. Thank you for your help in advance!

[B60T.csv](https://github.com/massimoaria/bibliometrix/files/12509090/B60T.csv)

![image](https://github.com/massimoaria/bibliometrix/assets/68634396/3640a5f3-8383-45a3-b719-34da7ddcaef7)

**Comment by massimoaria** [comment]
Your file contains metadata about patents and not publications. 
That's why convert2df() returns an error.

For the moment, bibliometrix only supports metadata about publications (articles, book chapters, etc.)
