### ISSUE TITLE
Biblioshiny :: change setup from local host to real IP and change Port number

### ISSUE THREAD

**Issue by zalpany2000** [massimoaria/bibliometrix#385]
dear all, 

I wonder how to force biblioshyiny to lunch on the real IP address and certain Port, the backgrownd, we wanted to run it on a server that is accessabile via our network. for network complecations, local host is not accessible from outside. 

best

**Comment by massimoaria** [comment]
You can set the IP and the port using the arguments 'host' and 'port' in the biblioshiny() function.


<img width="450" alt="image" src="https://github.com/massimoaria/bibliometrix/assets/16023543/e77376bd-c748-48ad-8e6d-b4f4b425037c">
