### ISSUE TITLE
Biblioshiny: The export button on the 'Load data' page has disappeared

### ISSUE THREAD

**Issue by kostask84** [massimoaria/bibliometrix#388]
I am using the 'bibliometrix' version 4.1.3 and I noticed that on the 'Load data' page has disappeared/been replaced with the 'Print' option, which only allows for PDF conversion and xlsx file conversion. Is that a bug or is it happening only on my PC?

Thank you in advance for your time and efforts

**Comment by massimoaria** [comment]
The load page has not changed.

<img width="1491" alt="image" src="https://github.com/massimoaria/bibliometrix/assets/16023543/e757c236-8df9-4116-865e-aa2979101060">
