### ISSUE TITLE
Authors vs. co-authors per document

### ISSUE THREAD

**Issue by akastrin** [massimoaria/bibliometrix#39]
I try to understand difference between `Authors per Document` and `Co-authors per Document` in a `summary` object. I think that short explanation  of `$MainInformation` items is necessary in this wonderful package.

**Comment by massimoaria** [comment]
Authors per Documents is the ratio between n.of authors and n. of documents.
Co-author per Documents is the tattoo between N. of Author Appearances and n. of documents.

**Comment by massimoaria** [comment]
![image](https://user-images.githubusercontent.com/16023543/55457173-729acf80-55e9-11e9-9811-970462dba1ee.png)
