### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by RustemLox** [massimoaria/bibliometrix#399]
Dear developers, 

I have trouble installing the package as the error is difficult to fix. I am using the 2023.03.0 Build 386. The error message is the following:

installing the source package ‘bibliometrix’

trying URL 'https://cran.rstudio.com/src/contrib/bibliometrix_4.1.3.tar.gz'
Content type 'application/x-gzip' length 1287874 bytes (1.2 MB)
downloaded 1.2 MB

* installing *source* package 'bibliometrix' ...
** package 'bibliometrix' successfully unpacked and MD5 sums checked
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/ru/AppData/Local/Temp/RtmpmI6Bxj/R.INSTALL4be87d2c725b/bibliometrix/R/csvLens2df.R:11:42: unexpected input
10:       mutate(across(where(is.numeric), as.character)) %>% 
11:       mutate(across(where(is.character), \
                                             ^
ERROR: unable to collate and parse R files for package 'bibliometrix'
* removing 'C:/Users/ru/OneDrive/Documents/R/win-library/4.0/bibliometrix'
Warning in install.packages :
  installation of package ‘bibliometrix’ had non-zero exit status 

Can you please help with this issue? Thanks.

**Comment by clacosta5** [comment]
i have the same problem...
did you find a solution?

**Comment by RustemLox** [comment]
I managed to install it by updating my R version to the newest one.

Kind regards, Rus

**Comment by clacosta5** [comment]
i have already the latest version of R... damn

**Comment by clacosta5** [comment]
uh thank you so much! It worked! @massimoaria
