### ISSUE TITLE
Logical error with conceptualStructure()

### ISSUE THREAD

**Issue by swood-ecology** [massimoaria/bibliometrix#4]
Hi,

I downloaded three .bib files from ISI, converted them to a data frame, and stitched them together with the following command:

```
data <- rbind(isibib2df(readFiles("results_1to500.bib")),
              isibib2df(readFiles("results_501to1000.bib")),
              isibib2df(readFiles("results_1001to1461.bib")))
```

When I attempted to run a conceptual structure analysis I was given the following error:

```
> CS <- conceptualStructure(data)
Error in which(unlist(lapply(listModa, is.numeric))) : 
  argument to 'which' is not logical
```

**Comment by massimoaria** [comment]
Please Read the function help. 
To run conceptualstructure you have to specify some other argument. 
On bibliometrix web site (www.bibliometrix.org), you can find an useful tutorial 

Sent from Alto
On Thursday, August 3, 2017 at 22:39 Stephen Wood <notifications@github.com> wrote:

Hi,

I downloaded three .bib files from ISI, converted them to a data frame, and stitched them together with the following command:

data <- rbind(isibib2df(readFiles("results_1to500.bib")), isibib2df(readFiles("results_501to1000.bib")), isibib2df(readFiles("results_1001to1461.bib"))) 

When I attempted to run a conceptual structure analysis I was given the following error:
