### ISSUE TITLE
Error in NetMatrix[nchar(colnames(NetMatrix)) != 0, nchar(colnames(NetMatrix)) !=  :    incorrect number of dimensions

### ISSUE THREAD

**Issue by lexdrennan** [massimoaria/bibliometrix#40]
I have followed the steps laid out in the documentation and get the following error when I try to run NetMatrix:
Error in NetMatrix[nchar(colnames(NetMatrix)) != 0, nchar(colnames(NetMatrix)) !=  : 
  incorrect number of dimensions

Can anyone help me with what I'm doing wrong? I have looked around the internet for discussions but can't find anything specific. Thanks!

Lex

Code below:
_D1 <- readFiles("data/savedrecs.bib") #reads in the citation file
D2 <- readFiles("data/savedrecs1.bib") #reads in the citation file

DataF1 <- convert2df(D1, dbsource="isi", format="bibtex") #converts to data frame
DataF2 <- convert2df(D2, dbsource="isi", format="bibtex") #converts to data frame

Data_Clean <- rbind(DataF1,DataF1) #creates one dataset

Cocitation <- biblioNetwork(Data_Clean, analysis = "Co-Citation Network", network = "references", sep = ". ")_

**Comment by massimoaria** [comment]
Please send me your files so I can try to identify the issue

**Comment by Arizonagong** [comment]
How did you solve this problem? would you please share me? because I have the same problem.
