### ISSUE TITLE
Error with igraph 1.6.0 release candidate

### ISSUE THREAD

**Issue by krlmlr** [massimoaria/bibliometrix#402]
This package fails its checks for the release candidate for igraph 1.6.0. See <https://github.com/igraph/rigraph/blob/main/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

We're planning to release igraph 1.6.0 early December. This should give us at least until late mid-December, perhaps early January, to resolve this and keep CRAN happy at the same time. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/968.

**Comment by massimoaria** [comment]
Hi,
we solved the issue in the release candidate 4.1.4.
We planned to release it on CRAN by the end of November.

Thanks
Massimo Aria

**Comment by krlmlr** [comment]
Thanks, I see the update on CRAN. Fingers crossed!

**Comment by krlmlr** [comment]
No longer seeing bibliometrix failures.
