### ISSUE TITLE
The bibliometrix package is missing CR when converting my scopus collection

### ISSUE THREAD

**Issue by cassandra2211** [massimoaria/bibliometrix#403]
Hi!

When I try to convert my scopus collection in bibtex, I get the message 
"Warning: In your file, some mandatory metadata are missing. Bibliometrix functions may not work properly!
Please, take a look at the vignettes:
- 'Data Importing and Converting' (https://www.bibliometrix.org/vignettes/Data-Importing-and-Converting.html)
- 'A brief introduction to bibliometrix' (https://www.bibliometrix.org/vignettes/Introduction_to_bibliometrix.html)
Missing fields:  CR 
Done!"

As you suggested to someone else here before I used this code to install the 
package, but it still didn't work.
>install.packages("remotes", force=TRUE)         
>remotes::install_github("massimoaria/bibliometrix")

The code I used after is:
>library(bibliometrix)
>scopus <- "scopus.bib"
>M <- convert2df(file= scopus, dbsource="scopus",format="bibtex").

Is there a way I can solve this?

Thank you in advance

Cassandra

**Comment by massimoaria** [comment]
Dear Cassandra,
Unfortunately, the Scopus metadata export system has been suffering from a bug for a few months now. 
When downloading data in BibTex format, the Scopus file does not contain the Cited References (CR field) even if the user has chosen to export them. 
This does not happen if you choose to export the metadata in CSV format.

Therefore, at the moment the only solution is to export the collection in CSV format.

**Comment by cassandra2211** [comment]
Hi.

Thank you so much for your prompt reply. By using the CSV format it's working.
