### ISSUE TITLE
Remove unused Matrix imports

### ISSUE THREAD

**Issue by jaganmn** [massimoaria/bibliometrix#405]
Please avoid importing functions, methods, and classes from **Matrix** (or really any package) that you do not use.  Notably, `Matrix::T2graph` and `Matrix::graph2T` may be ported from **Matrix** to **graph**.  If that occurs, then installation of your package will fail for essentially no reason, because you import those functions from **Matrix** without using them.  So, at a minimum, please remove these two lines from `NAMESPACE`:

https://github.com/massimoaria/bibliometrix/blob/26bc46cceffcfc475c4e3cabb6eb5462ffc0f215/NAMESPACE#L84
https://github.com/massimoaria/bibliometrix/blob/26bc46cceffcfc475c4e3cabb6eb5462ffc0f215/NAMESPACE#L118

perhaps by removing the corresponding lines in `R/zzz.R` and regenerating `NAMESPACE`.

**Comment by jaganmn** [comment]
@massimoaria, can you also remove the following unused import from `NAMESPACE`

https://github.com/massimoaria/bibliometrix/blob/ed6d47fd0b5ec62ade01164b7c7e4d3eccf2c5fb/NAMESPACE#L167

again by removing the corresponding line in `R/zzz.R` and regenerating `NAMESPACE`?  The development version of **Matrix**, not yet released, does not export an S4 generic function `unname`, causing an error when one attempts to install **bibliometrix**.

**Comment by massimoaria** [comment]
Done!

**Comment by jaganmn** [comment]
Thanks for acting so quickly! Looks good.
