### ISSUE TITLE
Error: 'to' must be a finite number

### ISSUE THREAD

**Issue by silbia95** [massimoaria/bibliometrix#43]
I'm trying to import a .bib file generated by Scopus and modified in Excel (just to delete some documents). As soon as I import it in Biblioshiny it gives me this error: 'to' must be a finite number.

I read previous "issues" on the topic but seems I have no problem with tab character or @

How can I solve?
Thank you!

[Try_1.txt](https://github.com/massimoaria/bibliometrix/files/3101515/Try_1.txt)

**Comment by massimoaria** [comment]
Maybe, when you modified the file (in Excel) the original bib Scopus format has not been preserved.
Please, import the whole original .bib scopus collection in biblioshiny, save it in excel and later remove the documents in excel and reload the xlsx file.
