### ISSUE TITLE
Critical Issue

### ISSUE THREAD

**Issue by albert8899** [massimoaria/bibliometrix#433]
(1)	Bibliometrix may have data issues, especially with missing data such as "authors," during bibliometric analysis. After downloading the Excel data exported from Bibliometrix, it was found that the "AU" column, representing authors, is incomplete. For example, a prolific author shows a total of 13 publications in WOS, but Bibliometrix displays only 10 publications, with three missing. Upon manually checking the exported Excel file, it was discovered that three publications were completely absent from the "AU" column. Upon revisiting the original Bib files, no issues were found, indicating a problem with Bibliometrix's own conversion process. 
For instance, in the case of the publication with DOI 10.1007/s00261-018-1667-0, which lists a total of seven authors, Bibliometrix and its exported Excel file only show five authors.
(2)	At the same time, In the “Authors” Column, there is also an issue of arbitrarily combining the surnames and given names of Chinese, Korean, and other Asian authors, leading to an inflated number of publications by Asian authors in the author column of the dataset. 
For example, publications by authors named Cheng Yang, Cheng Yan, and Cheng Yu may all be merged into publications credited to "Cheng Y," causing data distortion.

**Comment by massimoaria** [comment]
Thanks for your remark.
Please upload your bibtex file to check the issue.

**Comment by albert8899** [comment]
[savedrecs.zip](https://github.com/massimoaria/bibliometrix/files/14560452/savedrecs.zip)
I have randomly uploaded a downloaded bib.file for you to check issue 2 in the author column.
(2)  For example, publications by authors named Cheng Yang, Cheng Yan, and Cheng Yu may all be merged into publications credited to "Cheng Y," causing data distortion.

**Comment by massimoaria** [comment]
> [savedrecs.zip](https://github.com/massimoaria/bibliometrix/files/14560452/savedrecs.zip) I have randomly uploaded a downloaded bib.file for you to check issue 2 in the author column. (2) For example, publications by authors named Cheng Yang, Cheng Yan, and Cheng Yu may all be merged into publications credited to "Cheng Y," causing data distortion.

If you want use Author fullnames instead of Author surname and initials you have only to overwrite the content of column AU with the column AF:
`
library(dplyr)
M <- M %>% 
                 rename(AU_IN = .data$AU,
                        AU = .data$AF)
`
