### ISSUE TITLE
[Question] are there any plans to support google scholar?

### ISSUE THREAD

**Issue by marabesi** [massimoaria/bibliometrix#438]
I have been working on a systematic literature review that also covers google scholar as a database, unfortunately tools that automate bibliographic analysis seems to not support it, the same happens with bibliometrix(i guess). Is there any plans to support it?

If not, is there any suggestion for me to look for?

Thanks for this awesome project that helped my a lot in my research.

**Comment by massimoaria** [comment]
No. 
GS is not a bibliographic database but just a search engine. 
This means that: 
1) GS does not allow you to download the results of your query (of course we could try to obtain them by web-scraping but this is not polite);
2) Query results are not deterministic. GS provides different results for different users who submit the same search string! This violates the principle of replicability in science!
3) GS adopts unclear criteria on citations and coverage.

**Comment by marabesi** [comment]
I understand the points mentioned, but for people doing review within the gray literature, google scholar is the go to engine (violating or not the principle you mentioned)
