### ISSUE TITLE
Error in convert2df (Scopus)

### ISSUE THREAD

**Issue by BarbaraCartagenaMatos** [massimoaria/bibliometrix#44]
I'm trying to convert my Scopus database in R studio, but it's not working. Maybe there's a problem in some lines? If yes, how do I find it? It worked fine for my WoS database...

"Converting your scopus collection into a bibliographic dataframe
Error in seq.default(iP, iPs) : 'to' must be a finite number"

[scopus251all.txt](https://github.com/massimoaria/bibliometrix/files/3121698/scopus251all.txt)

**Comment by massimoaria** [comment]
Have you selected all contents before export the bib file?

**Comment by ramirbjunior** [comment]
I had the same problem here. It is impossible to download the data in the BibTex format by Scopus.. At least it did not work out here. I ended up using another source of information for data acquisition, such as the Web of Science. It worked!

**Comment by massimoaria** [comment]
The file you are trying to import has a wrong format. 
Bibliometrix reads only bibtex files from Scopus (while bibtex and plaintext for WoS).

You wrote " It is impossible to download the data in the BibTex format by Scopus", why?
Il 26/04/2019 16:29:03, BarbaraCartagenaMatos <notifications@github.com> ha scritto:
I'm trying to convert my Scopus database in R studio, but it's not working. Maybe there's a problem in some lines? If yes, how do I find it? It worked fine for my WoS database...
"Converting your scopus collection into a bibliographic dataframe
Error in seq.default(iP, iPs) : 'to' must be a finite number"
scopus251all.txt [https://github.com/massimoaria/bibliometrix/files/3121698/scopus251all.txt]
