### ISSUE TITLE
Unable to locate the assignment of `values$SO`

### ISSUE THREAD

**Issue by tanchangde** [massimoaria/bibliometrix#442]
Hello,I am reviewing the following line of code in the `server.R` file:

```r
x <- c(
  max(values$DF$Year) - 0.02 - diff(range(values$SO$Year)) * 0.20,
  max(values$DF$Year) - 0.02) - 1
```

I noticed that this line of code uses values$SO, but I can't find where values$SO is assigned in the other files of the project. Could you please tell me where values$SO is defined? 

Thank you for your help!

## Ref

https://github.com/massimoaria/bibliometrix/blob/d8ca5a99507afde04b93ddf85e40eb63200f45fc/inst/biblioshiny/server.R#L3511

**Comment by massimoaria** [comment]
Thanks for your remark.
The row contains a typo. 
I just corrected it.
