### ISSUE TITLE
Exporting pajek file, min no of citations in co-citation network

### ISSUE THREAD

**Issue by RabeelKhan84** [massimoaria/bibliometrix#445]
Hi, 
I have created a co-citation network in biblioshiny and I want to download it as a Pajek file to use in VOS viewer. I am getting an error when I click the Pajek download. Can you help me solve this?

Also, is it possible to set a minimum number of citations of document to 10 in co-citation network in biblioshiny?
![Co-citation network](https://github.com/massimoaria/bibliometrix/assets/167270615/68d07918-fb36-4ccc-9c50-5386884b6fd2)

**Comment by massimoaria** [comment]
Hi,
What bibliometrix version are you using?
Last beta version from GitHub already solved the issue.
Please try last version or provide a sample file to replicate the error.

**Comment by massimoaria** [comment]
It is not possible to set min no of citations but a max no of references.

**Comment by RabeelKhan84** [comment]
I am using the latest R version 4.3.3. 
[savedrecs.zip](https://github.com/massimoaria/bibliometrix/files/15007145/savedrecs.zip)

File is attached.  Requirement is to run a co-citation analysis with 200 nodes. And then export the network as a pajek file.

**Comment by massimoaria** [comment]
I am not referring to the R version but to the bibliometrix version.

To install the latest version from GitHub you need to use the following lines of code:

`
install.packages("remotes")         
`
`
remotes::install_github("massimoaria/bibliometrix")
`
