### ISSUE TITLE
Scopus CSV file reading error. Nos. of Authors incorrectly recognised 

### ISSUE THREAD

**Issue by gordeswapnil** [massimoaria/bibliometrix#448]
[Scopus Query.docx](https://github.com/massimoaria/bibliometrix/files/15064924/Scopus.Query.docx)
[scopus-5.csv](https://github.com/massimoaria/bibliometrix/files/15064925/scopus-5.csv)
I have shared you my scopes sample database. I am trying with version RStudio
2023.12.1 Build 402. after uploading the file I am getting following screenshot for summery of data I have uploaded. check the Authors and Coauthors. it is showing only 1 Author. 
<img width="898" alt="image" src="https://github.com/massimoaria/bibliometrix/assets/65887061/c1a72a04-fdce-49f9-bc1d-97e9b879f872">
the above image is after data is loaded from CSV. 
following is the General information screenshot. Check author Coauthor and Ref. 
<img width="1611" alt="image" src="https://github.com/massimoaria/bibliometrix/assets/65887061/accdedf9-9052-4256-aa0e-e5d8a213e21f">

**Comment by massimoaria** [comment]
Thanks for your remark.

I have solved the issue.

Please update from github.

**Comment by gordeswapnil** [comment]
I am new to R. Can you guide me how can I update R from GitHub. I can see the code you have shared but not able to figure out how to update it.

**Comment by massimoaria** [comment]
Open R or Rstudio (in console window) and digit:

install.packages("remotes")         

Then:
   remotes::install_github("massimoaria/bibliometrix")

**Comment by gordeswapnil** [comment]
hi, i tried doing it.

following is the output.

install.packages("bibliometrix")WARNING: Rtools is required to build R
packages but is not currently installed. Please download and install
the appropriate version of Rtools before proceeding:
https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/swapnil/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)also installing the dependency ‘ca’
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/ca_0.71.1.zip'Content
type 'application/zip' length 243417 bytes (237 KB)downloaded 237 KB
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/bibliometrix_4.2.0.zip'Content
type 'application/zip' length 2445339 bytes (2.3 MB)downloaded 2.3 MB
package ‘ca’ successfully unpacked and MD5 sums checked
package ‘bibliometrix’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\swapnil\AppData\Local\Temp\RtmpcNVQDV\downloaded_packages>
install.packages("bibliometrixData")WARNING: Rtools is required to
build R packages but is not currently installed. Please download and
install the appropriate version of Rtools before proceeding:
https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/swapnil/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)trying URL
'https://cran.rstudio.com/bin/windows/contrib/4.3/bibliometrixData_0.3.0.zip'Content
type 'application/zip' length 3948907 bytes (3.8 MB)downloaded 3.8 MB
package ‘bibliometrixData’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\swapnil\AppData\Local\Temp\RtmpcNVQDV\downloaded_packages>
install.packages("remotes")WARNING: Rtools is required to build R
packages but is not currently installed. Please download and install
the appropriate version of Rtools before proceeding:
https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/swapnil/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)trying URL
'https://cran.rstudio.com/bin/windows/contrib/4.3/remotes_2.5.0.zip'Content
type 'application/zip' length 430384 bytes (420 KB)downloaded 420 KB
package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\swapnil\AppData\Local\Temp\RtmpcNVQDV\downloaded_packages>
remotes::install_github("massimoaria/bibliometrix")Downloading GitHub
repo ***@***.*** packages have more recent
versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All
 2: CRAN packages only
 3: None
 4: tidyselect (1.2.0   -> 1.2.1  ) [CRAN]
 5: digest     (0.6.34  -> 0.6.35 ) [CRAN]
 6: sass       (0.4.8   -> 0.4.9  ) [CRAN]
 7: htmltools  (0.5.7   -> 0.5.8.1) [CRAN]
 8: promises   (1.2.1   -> 1.3.0  ) [CRAN]
 9: openssl    (2.1.1   -> 2.1.2  ) [CRAN]
10: curl       (5.2.0   -> 5.2.1  ) [CRAN]
11: tinytex    (0.49    -> 0.50   ) [CRAN]
12: bslib      (0.6.1   -> 0.7.0  ) [CRAN]
13: xfun       (0.42    -> 0.43   ) [CRAN]
14: rmarkdown  (2.25    -> 2.26   ) [CRAN]
15: knitr      (1.45    -> 1.46   ) [CRAN]
16: munsell    (0.5.0   -> 0.5.1  ) [CRAN]
17: gtable     (0.3.4   -> 0.3.5  ) [CRAN]
18: httpuv     (1.6.13  -> 1.6.15 ) [CRAN]
19: zip        (2.3.0   -> 2.3.1  ) [CRAN]
20: data.table (1.14.10 -> 1.15.4 ) [CRAN]
21: tidytext   (0.4.1   -> 0.4.2  ) [CRAN]
22: shiny      (1.8.0   -> 1.8.1.1) [CRAN]
23: igraph     (1.6.0   -> 2.0.3  ) [CRAN]
24: DT         (0.32    -> 0.33   ) [CRAN]
Enter one or more numbers, or an empty line to skip updates: ── R CMD
build ─────────────────────────────────────────────────────────✔
checking for file
'C:\Users\swapnil\AppData\Local\Temp\RtmpcNVQDV\remotes95070237c88\massimoaria-bibliometrix-bc93aa8/DESCRIPTION'
(376ms)─  preparing 'bibliometrix': (863ms)✔  checking DESCRIPTION
meta-information ...─  installing the package to process help pages
         -----------------------------------─  installing *source*
package 'bibliometrix' ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   *** installing help indices
   *** copying figures
   ** building package indices
   ** testing if installed package can be loaded from temporary location
   ERROR: loading failed─  removing
'C:/Users/swapnil/AppData/Local/Temp/RtmpsroC2X/Rinst50825d12f1d/bibliometrix'
         -----------------------------------
   ERROR: package installation failedError: Failed to install
'bibliometrix' from GitHub:
  ! System command 'Rcmd.exe' failed

>

Create your WiseStamp email signature
<https://www.wisestamp.com/lp/promo/professional-email-signature?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>

[image: __tpx__]
‌

**Comment by gordeswapnil** [comment]
Hi,
still the same problem persist.

Issue not resolved. I checked.

Regards,
Swapnil

Create your WiseStamp email signature
<https://www.wisestamp.com/lp/promo/professional-email-signature?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>

[image: __tpx__]
‌

**Comment by massimoaria** [comment]
As I mentioned in a previous post, You **have to** install bibliometrix from GitHub (and not from CRAN)!
Please use the following code lines in R console:

`install.packages("remotes")`

`remotes::install_github("massimoaria/bibliometrix")`

**If you continue to install bibliometrix using install.packages() function, bibliometrix will not update to the last beta version.**
