### ISSUE TITLE
Add reference or more information for "stability" measure in plotThematicEvolution

### ISSUE THREAD

**Issue by TrashBirdEcology** [massimoaria/bibliometrix#45]
The measure **stability** is a possible argument value  in function `plotThematicEvolution()`. E.g., `plotThematicEvolution(..., measure="stability)`, yet there is no reference or definition/explanation of this measure option in the package documentation on CRAN.

Can you please add a reference or more information on this option to the package documentation?

Thanks!

**Comment by massimoaria** [comment]
The measures used in the plotThematicEvolution are defined by Cobo et al. 2011.

Cobo, M. J., López-Herrera, A. G., Herrera-Viedma, E., & Herrera, F. (2011). An approach for detecting, quantifying, and visualizing the evolution of a research field: A practical application to the fuzzy sets theory field. Journal of Informetrics, 5(1), 146-166.

**Comment by TrashBirdEcology** [comment]
Thanks!
