### ISSUE TITLE
Problem loading Lens

### ISSUE THREAD

**Issue by sdspieg** [massimoaria/bibliometrix#452]
Am I the only one?  Here's a direct export from The Lens.
[lens-export.csv](https://github.com/massimoaria/bibliometrix/files/15097726/lens-export.csv)
And this is the error I get
![image](https://github.com/massimoaria/bibliometrix/assets/691472/8050b2b5-7fe7-44d1-8260-ed2ef2b72a2b)

**Comment by massimoaria** [comment]
The issue has already been solved.

Please update biblioiatrica from GitHub

**Comment by sdspieg** [comment]
Great! So yes, the latest beta version of bibliometrix does indeed fix this (see below)! Thanks much.... 
![image](https://github.com/massimoaria/bibliometrix/assets/691472/36c0b528-95e7-4c47-b820-ce39df47fd90)
