### ISSUE TITLE
convert2df OpenAlex error

### ISSUE THREAD

**Issue by sibu116** [massimoaria/bibliometrix#459]
I extracted a dataset from OpenAlex ( [works.csv](https://github.com/massimoaria/bibliometrix/files/15370413/works.csv) )and is is trying to run the following `convert2df("works.csv","openalex","csv")` in Rstudio. However, I keep getting the following error 

Error in `$<-.data.frame`(`*tmp*`, "C1", value = character(0)) :                    
  replacement has 0 rows, data has 73
In addition: Warning message:
One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat) 

I have also tried loading this dataset in Bibliometrix too but keep getting the "replacement has 0 rows, data has 73" error.

How can I resolve this issue

**Comment by gabrielesh** [comment]
It sounds like something is missing. Have you confirmed the number of rows in the data itself? are there missing columns?

**Comment by massimoaria** [comment]
Please take a look at this issue:
https://github.com/massimoaria/bibliometrix/issues/468

**Comment by sibu116** [comment]
> It sounds like something is missing. Have you confirmed the number of rows in the data itself? are there missing columns?

Yes I did. No missing columns in the data.

**Comment by sibu116** [comment]
> It sounds like something is missing. Have you confirmed the number of rows in the data itself? are there missing columns?

Yes I did. No missing columns in the data.

**Comment by massimoaria** [comment]
The issue has been solved. Please update the library from GitHub

**Comment by sibu116** [comment]
> The issue has been solved. Please update the library from GitHub

Worked. Thanks
