### ISSUE TITLE
Bibtext file issue when importing

### ISSUE THREAD

**Issue by 00logan00** [massimoaria/bibliometrix#461]
Hi all,
I am a new user to both R and Bibliometrix. Currently I want to merge WoS.txt with Scopus.bib to upload the combined version to Biblioshiny.

I have no issue when importing WoS.txt. However, it happens when I do with Scopus.bib. It appears a message saying that object "M" is not found some thing. Please advise me if anyone know how to fix this issue?

Many thanks

**Comment by massimoaria** [comment]
Please provide a reproducible example with data and code.
