### ISSUE TITLE
Can't import data from Openalex

### ISSUE THREAD

**Issue by berleal3** [massimoaria/bibliometrix#468]
Hi, when i try to import data from Openalex using biblioshiny the Error message "replacement has 0 rows" always is present. What can i do for import data from openalex?
Thanks

**Comment by massimoaria** [comment]
OpenAlex is a recently introduced database and is still in a beta development phase.
For this reason, its record layout is constantly changing as the developers proceed with optimizing the database.
The consequence of these constant changes is that software that analyses this data may not work when the changes affect critical elements.
In this case, the way affiliations and keywords are stored and exported in the CSV file has changed.
The problem has however been resolved.
Update bibliometrix from GitHub and try again.

**Comment by berleal3** [comment]
Thanks, I'll try again
