### ISSUE TITLE
direct citation network

### ISSUE THREAD

**Issue by roneyfraga** [massimoaria/bibliometrix#47]
Dear authors,

Thank you for the continued development of the `bibliometrix`.

Is it possible to build a direct citation network from references in `bibliometrix`?  

I am assuming that a direct citation network consists of citation between the articles returned in the query, as presented by Boyak and Klavans (2010), Figure 1.

![Boyack and Klavans 2010 - Figure 1](https://user-images.githubusercontent.com/4466935/57861775-38664580-77c5-11e9-9e45-d10a134da207.png)

Boyack, K. W., & Klavans, R. (2010). Co‐citation analysis, bibliographic coupling, and direct citation: Which citation approach represents the research front most accurately?. Journal of the American Society for Information Science and Technology, 61(12), 2389-2404.

thanks

**Comment by massimoaria** [comment]
The direct citation network is already implemented in the histNetwork function.

**Comment by roneyfraga** [comment]
Thanks, I missed the latest `bibliometrix` updates.

I found the way you followed to treat the references interesting. 

In the past, I was inspired by `bibexcel` to generate a direct citation network when building a key like:
<img width="304" alt="Screen Shot 2019-05-17 at 15 56 58" src="https://user-images.githubusercontent.com/4466935/57952959-b35e5780-78bc-11e9-89a3-c8550febcac7.png">
and then generate a list of vertices.

The code was more or less this. 
[gist link](https://gist.githubusercontent.com/roneyfraga/e1a24b77c301bb7eae961688bb52d451/raw/56144c4634d6c5426adb2260c5edf6aab6b1ec34/1.R)

This is an old code with multiple inefficiencies. ;)
