### ISSUE TITLE
Problem with bibliometrix(), Open Alex and VOS viewer 

### ISSUE THREAD

**Issue by DebsKing** [massimoaria/bibliometrix#474]
Hello, and thank you for creating such a helpful package,

I have downloaded data from Open Alex via API in R, and I am analysing through my own coding and with bibliometrix(). So far so good. However, I am use VOS Viewer in R, in combination, as indicated in the bibliometrix() tutorial. Any help would be appreciated.

I am using bibliometrix package version 4.2.3. I have used 'jar' and 'exe' files for VOSViewer, with no change in outcome. 

This is my relevant R code chunk. 'mydata' is the dataframe of results from my Open Alex API query. 

> vos.path <- "C:/.../VOSviewer_1.6.20_jar/"

> mydata_t <- metaTagExtraction(mydata,  Field = "ID", sep = ";")

> NetMatrix <- biblioNetwork(mydata_t, analysis = "co-occurrences", network = "keywords", sep = ";")

> net <- networkPlot(NetMatrix, n = 25, Title = "Keyword Co-occurrences", 
 type = "vosviewer", normalize = "association", 
 weighted = TRUE, labelsize = 0.7, 
vos.path = vos.path)

Error in switchLayout(bsk.S, type, community.repulsion) : 
  object 'l' not found

Many thanks, 
Deborah King

**Comment by massimoaria** [comment]
Dear Deborah,

Could you give me more info about your issue (data and the complete code)?

Moreover, from bibliometrix 4.1, we introduced a new function, called net2VOSviewer(), to plot networks with VosViewer.

Here a brief example:

# VOSviewer.jar have to be present in the working folder

data(scientometrics, package = "bibliometrixData")

NetMatrix <- biblioNetwork(scientometrics, analysis = "co-citation", 
network = "references", sep = ";")

net <- networkPlot(NetMatrix, n = 30, type = "kamada", Title = "Co-Citation",labelsize=0.5) 

net2VOSviewer(net)
