### ISSUE TITLE
Error Encountered When Using convert2df Function with PubMed Database in RStudio

### ISSUE THREAD

**Issue by crybcto** [massimoaria/bibliometrix#476]
I apologize for any mistakes; I'm not an English speaker, and this is practically my first time dealing with programming.
I'm using R (4.4.1) along with RStudio (2024.04.2 Build 764) to analyze the PubMed database.
When I execute the code:

 `> pm <- convert2df("C:/Users/victt/OneDrive/Documents/Sexuality Scale Master/csv-sexualityA-set C.csv", dbsource = "pubmed", format = "csv")`

I get the following error:

> **Converting your pubmed collection into a bibliographic dataframe**
>
> _Error in rep(1:nP, rowPapers) : argument 'times' invalid_> 

What should I do?

--
Thank you for your help,
Victtor

**Comment by massimoaria** [comment]
Hi,
PubMed CSV format is not supported by bibliometrix.
Please take a look at the following table and our tutorials on www.bibliometrix.org.

![table_DBformats](https://github.com/massimoaria/bibliometrix/assets/16023543/8fd67d43-a63e-4932-8cc0-d4ce3a88fa2b)
