### ISSUE TITLE
Unite two bib files

### ISSUE THREAD

**Issue by smolski** [massimoaria/bibliometrix#48]
Thanks for de the great job!

My question: is possible unite two bib files (for example wos.bib and scopus.bib)?

Best regards,

Felipe Smolski

**Comment by kapedani** [comment]
united_bib<-readFiles('wos.bib', 'scopus.bib')
convert2df(united_bib)

**Comment by mlagisz** [comment]
hi, when uniting files from different databases, such as WoS and Scopus, the conventions used to store reference lists (citations) in a CR field are different. As result, citation-based analyses do not work on such hybrid data frames. Can you suggest any workaround for this? For example, a function that would check what database a given record (row) originated from and then converting the string of citations to a standardised format?

**Comment by cristitosa** [comment]
Hi,
I encountered the same issue. There are some examples in the literature. You can refer to Miika Kumpulainen & Marko Seppänen (https://link.springer.com/article/10.1007/s11192-022-04475-7), and Echchakoui (https://link.springer.com/article/10.1057/s41270-020-00081-9).
Hope you can get to the end of it, I am still working on it.
