### ISSUE TITLE
convert2df error

### ISSUE THREAD

**Issue by westie14** [massimoaria/bibliometrix#482]
Hello, 

I keep getting this error when using the convert2df function to convert a dimensions file to bibliometric data frame.

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in `$<-.data.frame`(`*tmp*`, "AU", value = character(0)) : 
  replacement has 0 rows, data has 137

This is my code:
Z= convert2df("file path.csv", dbsource='dimensions', format='csv')

AU column is labeled as such, with authors separated by semi-colon, last name, first initial

R 4.3.1
packages loaded

Appreciate any help!

**Comment by massimoaria** [comment]
Plese upload your csv dataset.

**Comment by westie14** [comment]
Hello,

Thank you so much for your response. Please see the attached CSV with
headings in the format required for "bibliometrix" package in R.

Thank you!

**Comment by massimoaria** [comment]
I cannot see the file.
