### ISSUE TITLE
Is there a way of making graph over time with the keywords? 

### ISSUE THREAD

**Issue by bemacedom** [massimoaria/bibliometrix#484]
I'm developing a study and I'd like to display the most used keywords on the y-axis and the years on the x-axis. The idea is that the lines for each keyword contain the circles according to the quantity over time. It would be similar to the “productivity of the main authors over time” and “Historical Direct Citation Network” graphs.

Thanks for your attention.

**Comment by massimoaria** [comment]
Hi,
Of course you can do that.

Through Biblioshiny you can use Words' frequency over time analysis or Trend Topics.
Through Bibliometrix functions you can use  fieldByYear() and keywordGrowth()

Here an output obtained with Biblioshiny():
<img width="1471" alt="image" src="https://github.com/user-attachments/assets/4683c9c3-24cb-424c-926a-b0be5ecebca0">

![WordsFrequencyOverTime-2024-09-10](https://github.com/user-attachments/assets/7468cf00-3702-4559-b3a0-6955a67b13a5)
