### ISSUE TITLE
Problem with opening library(bibliometrix) in R

### ISSUE THREAD

**Issue by cemoens** [massimoaria/bibliometrix#488]
Hello can somebody help me with the bug with opening bliometrix/biblioshiny?

I can install.packages("bibiliometrix"), but when I write library(bibliometrix) I get the following error:
Error: package or namespace load failed for 'bibliometrix' in loadNamespace(ii, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called 'gtable'. 

However when I command: install.packages('gtable') this is tsill not working and get weird message when installing saying "ERROR: lazy loading failed for package 'gtable'.... installation of package 'gtable" had non-zero exit status. 

Thank you for you help.

**Comment by massimoaria** [comment]
try to remove and reinstall the package gtable.

```
remove.packages("gtable")
install.packages("gtable")
```
