### ISSUE TITLE
"Matrix is empty!! Error in strsplit(LABEL, "\\. ") : non-character argument

### ISSUE THREAD

**Issue by ajcanepa** [massimoaria/bibliometrix#492]
I had followed the tutorial given [here](https://bibliometrix.org/documents/bibliometrix_Report.html).

Following the scopus BibTex code I can get the proper M object.
`# Converting the loaded files into a R bibliographic dataframe
M <- convert2df(file = myfile,
                dbsource = "scopus",
                format = "bibtex")`

However, when I run
`NetMatrix <- biblioNetwork(M, analysis = "co-citation", network = "references", sep = ";")`

I had the following error message:
```
[1] "Matrix is empty!!"
Error in strsplit(LABEL, "\\. ") : non-character argument
```
If the `M` object is OK and gives me all the neccesary information, I have no clue about what can be wrong with the `biblioNetwork()` function, since I had followed the example by default.

**Comment by massimoaria** [comment]
Unfortunately, the bibtex format exported by Scopus no longer contains bibliographies. You can verify that the CR (Cited References) column of the M object is empty.

If you want to perform a co-citation analysis, you need to download the Scopus data in CSV format.

**Comment by ajcanepa** [comment]
Many thanks @massimoaria ,
I think you perform such a brave work trying to use this data from those huge companies. Keep doing it!
