### ISSUE TITLE
Customized WoS Field Tags

### ISSUE THREAD

**Issue by swood-ecology** [massimoaria/bibliometrix#5]
It would be great to have the option to customize the Field Tags included in the `...2df` functions. I'd really like to be able to include a DOI code, which I have in my downloaded WoS search, but can't seem to transfer into the R data frame with the current functions.

**Comment by massimoaria** [comment]
If you use plaintext format (for wos Data), the tag DI (DOI identifier ) will be automatically create by convert2df

Sent from Alto
On Monday, August 7, 2017 at 16:44 Stephen Wood <notifications@github.com> wrote:

It would be great to have the option to customize the Field Tags included in the ...2df functions. I'd really like to be able to include a DOI code, which I have in my downloaded WoS search, but can't seem to transfer into the R data frame with the current functions.

**Comment by swood-ecology** [comment]
Is there a way to either convert the .bib format to plaintext or to build that functionality into the .bib import function? I have a pretty big database and it would take me a while to go back to the WoS website, conduct the searches, and re-save the data in a different format.

**Comment by massimoaria** [comment]
I Will work on it in the next days. 
Please send me your bib file, so I can use it to try my solution. 


Sent from Alto
On Monday, August 7, 2017 at 17:39 Stephen Wood <notifications@github.com> wrote:

Is there a way to either convert the .bib format to plaintext or to build that functionality into the .bib import function? I have a pretty big database and it would take me a while to go back to the WoS website, conduct the searches, and re-save the data in a different format.

**Comment by swood-ecology** [comment]
Thank you. Here's a sample data set for testing.
 
[soil.quality_6501to7000.bib.zip](https://github.com/massimoaria/bibliometrix/files/1205345/soil.quality_6501to7000.bib.zip)

**Comment by massimoaria** [comment]
This morning, I have updated the package. Now, DOIs are extracted from bibtex. 

Sent from Alto
On Monday, August 7, 2017 at 17:44 Stephen Wood <notifications@github.com> wrote:

Thank you. Here's a sample data set for testing.

soil.quality_6501to7000.bib.zip
