### ISSUE TITLE
Bib2df replace semicolon by comma

### ISSUE THREAD

**Issue by rodfileto** [massimoaria/bibliometrix#50]
Thank you for the package. It is a great resource for scientometric analysis.

Related to the function "bib2df", I checked that all semicolons are replaced by comma on the fields "Funding-Text" and "Funding-Acknowledgement" (bib files from Web of Science). The function work properly with other fields that also have semicolon, such as Author and Address.

**Comment by rodfileto** [comment]
The same is happening in the field "WC" which is about scientific categories.

**Comment by massimoaria** [comment]
Solved for "Funding-Text" and "Funding-Acknowledgement".
For "WC", semicolons have to be replace by comma because semicolons (and then comma) separate different categories.
