### ISSUE TITLE
BiblioShiny producing black unreadable graphs

### ISSUE THREAD

**Issue by PedroSennaVieira** [massimoaria/bibliometrix#51]
Hello! the biblioshiny is producing unreadable graphas in the last update that i downloaded...before the graphs were collored and somehow clustered... how can i work around this problem? Using the normal code in bibliometrix the graph works fine...

![image](https://user-images.githubusercontent.com/51272424/58752365-0ec74280-8484-11e9-9bab-1fbfce1b02da.png)

**Comment by massimoaria** [comment]
In my experience, this issue happens when the browser is not fully compatible with js plots (i.e. safari, edge).
Please, try to use biblioshiny with Chrome or Firefox.

**Comment by PedroSennaVieira** [comment]
THanks a lot Massimo! grazzie mille! it works fine now on chrome

![image](https://user-images.githubusercontent.com/51272424/59067814-ed51c680-8888-11e9-8a14-b6a1e42b33ab.png)
