### ISSUE TITLE
How do I implement specified output?

### ISSUE THREAD

**Issue by perlatex** [massimoaria/bibliometrix#52]
`
data(scientometrics)

histResults <- histNetwork(scientometrics, sep = ";")

net <- histPlot(histResults, n = 20, size.cex = TRUE, size = 5, arrowsize = 0.3)
`

In Rmarkdown beamer, this function generates one data.frame and one plots. 
The graph is very beautiful, so i want to hide the data.frame and show plot only. 
How do I implement specified output?

**Comment by massimoaria** [comment]
I have just introduced a new argument (verbose) in HistPlot function.
Setting verbose=FALSE, histPlot draws only the graph.


net <- histPlot(histResults, n = 20, size.cex = TRUE, size = 5, arrowsize = 0.3, verbose=FALSE)
