### ISSUE TITLE
biblioshiny and author impact misreading author

### ISSUE THREAD

**Issue by dr-ish** [massimoaria/bibliometrix#54]
Hi, 
I'm using biblioshiny to analyze my data and when I use the author impact function I see that it has misread one author. Here, author No, R, must be the same as Siliciano, RF. When I look at the .bib file, I don't see any instances where there is an author by the name of No, R. How can I correct this?
Marcella

Author | h_index | g_index | m_index | TC | NP | PY_start
-- | -- | -- | -- | -- | -- | --
NO R | 56 | 111 | 2.666667 | 12456 | 132 | 1999
SILICIANO RF | 55 | 110 | 2.619048 | 12219 | 122 | 1999

**Comment by massimoaria** [comment]
Please send me your bib file to analyze the issue

**Comment by dr-ish** [comment]
Thank you so much! I separated the files into 4 time periods so that I could send them over, but I've been working with a file that combined all of these. Also, the problem with the names exists for several authors: No R; An J; An M; Son J; Son M; Ni M;
My guess is that these authors are: Siliciano RF (No R);Sullivan J (An J); Lederman M (An M);  Blankson J (Son J); Stevenson M (son M) and I have no idea who Ni M is...

Author | h_index | g_index | m_index | TC | NP | PY_start
-- | -- | -- | -- | -- | -- | --
NO R | 56 | 111 | 2.666666667 | 12450 | 131 | 1999
SILICIANO RF | 55 | 110 | 2.619047619 | 12213 | 121 | 1999
AN J | 46 | 83 | 2.19047619 | 7225 | 143 | 1999
AN M | 46 | 84 | 2.19047619 | 7798 | 199 | 1999
SON J | 43 | 86 | 2.047619048 | 7935 | 170 | 1999
SON M | 40 | 73 | 1.904761905 | 5606 | 112 | 1999
MARGOLIS D | 39 | 79 | 1.95 | 6320 | 86 | 2000
MARGOLIS DM | 37 | 75 | 1.85 | 5759 | 76 | 2000
SILICIANO JD | 36 | 58 | 1.714285714 | 7116 | 58 | 1999
DEEKS SG | 34 | 71 | 1.7 | 5174 | 92 | 2000
DEEKS S | 34 | 71 | 1.7 | 5189 | 94 | 2000
ROUZIOUX C | 33 | 61 | 1.736842105 | 3834 | 76 | 2001
PALMER S | 31 | 52 | 1.9375 | 4364 | 52 | 2004
RICHMAN D | 31 | 63 | 1.476190476 | 5473 | 63 | 1999
AN P | 31 | 59 | 1.476190476 | 3632 | 93 | 1999
NG C | 31 | 54 | 1.476190476 | 3165 | 104 | 1999
CHOMONT N | 30 | 63 | 2.307692308 | 4083 | 68 | 2007
CHUN TW | 30 | 43 | 1.428571429 | 4092 | 43 | 1999
LEWIN S | 30 | 66 | 1.428571429 | 4463 | 78 | 1999
LEWIN SR | 29 | 61 | 2.230769231 | 3731 | 76 | 2007
FAUCI AS | 28 | 33 | 1.333333333 | 3010 | 33 | 1999
NI M | 28 | 49 | 1.333333333 | 2713 | 128 | 1999





[scopus same as pubmed 2007-1999.zip](https://github.com/massimoaria/bibliometrix/files/3287858/scopus.same.as.pubmed.2007-1999.zip)
[scopus same as pubmed 2013-2008.zip](https://github.com/massimoaria/bibliometrix/files/3287862/scopus.same.as.pubmed.2013-2008.zip)
[scopus same as pubmed 2016-2014.zip](https://github.com/massimoaria/bibliometrix/files/3287864/scopus.same.as.pubmed.2016-2014.zip)
[scopus same pubmed 2019-2017.zip](https://github.com/massimoaria/bibliometrix/files/3287865/scopus.same.pubmed.2019-2017.zip)

**Comment by massimoaria** [comment]
The issue is due to non-standard ASCII character in some author names.
For example the author name “Noë R” contains the character “ë” which it not recognized by R so the name becomes “NO R”.

I have modified the function readFiles to take into account this issue.

**Comment by dr-ish** [comment]
Thank you so much!
