### ISSUE TITLE
Produce a readable file for Biblioshiny

### ISSUE THREAD

**Issue by PedroSennaVieira** [massimoaria/bibliometrix#56]
Hello Massimo,

i used to work like that, i read many bib files from many different searchs like this:

Scop <- readFiles('NovoScopus1.bib')
Scop_Bib10 <- convert2df(Scop, dbsource = "scopus", format = "bibtex")
Scop <- readFiles('NovoScopus2.bib')
Scop_Bib11 <- convert2df(Scop, dbsource = "scopus", format = "bibtex")

Wos<- readFiles('WOS1.bib')
Wos_Bib1 <- convert2df(Wos, dbsource = "isi", format = "bibtex")
Wos<- readFiles('WOS2.bib')
Wos_Bib2 <- convert2df(Wos, dbsource = "isi", format = "bibtex")
Wos<- readFiles('WOS3.bib')
Wos_Bib3 <- convert2df(Wos, dbsource = "isi", format = "bibtex")

M<- mergeDbSources(Scop_Bib10,Scop_Bib11,Wos_Bib1,Wos_Bib2,Wos_Bib3, remove.duplicated=TRUE)
write.csv(M, file="M.csv")

then, i loaded the "M" fle into shiny and it all worked just fine. Nevertheless, now shiny does not load the file and so i cannot procede with the analyzes...

i Loaded the example file called "joi.txt" (which works just fine) and it looks very similar to the file i generated...

do you have any clues of what is going on?

thank you very much

**Comment by massimoaria** [comment]
Dear Pedro,

i need to have a look to your collection to understand the issue.
Please attach it or send it to my email.

**Comment by PedroSennaVieira** [comment]
Dear massimo,

what is your e-mail? I wrote a big message but it seems that github have a
limit

Pedro Senna Vieira
*Professor*
Production Engineering Department
Av. Maracanã, 229 -Maracanã-Rio de Janeiro- RJ- Brazil
<https://maps.google.com/?q=Av.+Maracan%C3%A3,+229+-Maracan%C3%A3-Rio+de+Janeiro-+RJ-+Brazil%C2%A0+20271-110&entry=gmail&source=g>
20271-110
<https://maps.google.com/?q=Av.+Maracan%C3%A3,+229+-Maracan%C3%A3-Rio+de+Janeiro-+RJ-+Brazil%C2%A0+20271-110&entry=gmail&source=g>
Lattes: http://lattes.cnpq.br/5524140651664494
<https://wwws.cnpq.br/cvlattesweb/PKG_MENU.menu?f_cod=EB8E63F703B32C300E4AFE2B90D85F39>




Em ter, 25 de jun de 2019 às 08:06, Massimo Aria <notifications@github.com>
escreveu:

**Comment by massimoaria** [comment]
massimo.aria@gmail.com
