### ISSUE TITLE
upper case necessary?

### ISSUE THREAD

**Issue by franciscowilhelm** [massimoaria/bibliometrix#57]
Dear Massimo and Corrado

I wanted to skim some abstracts from a bibliometrix data frame and noticed that all abstracts are converted to upper case in the bib2df function. Is this character case conversion strictly necessary for all data fields? Retaining the abstracts in their original case would improve readability.

Best
Francisco

**Comment by massimoaria** [comment]
Dear Francisco,

upper case (or lower case) are necessary to normalize the text. 
Text normalization (upper or lower case, punctuation removing, etc.) is a mandatory phase to implement correct text analysis procedures.

**Comment by gaospecial** [comment]
Is it possible to keep text case non-changed? I just want to retrieve the text.

**Comment by massimoaria** [comment]
No, sorry
