### ISSUE TITLE
synonyms in termExtraction only works for the last element of the vector character

### ISSUE THREAD

**Issue by flpker64** [massimoaria/bibliometrix#59]
Dear Massimo,
In [`termExtraction`](https://github.com/massimoaria/bibliometrix/blob/master/R/termExtraction.R) _L114_  
`for (i in length(synonyms)) {`
may be changed to
`for (i in 1:length(synonyms)) {`
otherwise it seems that only the last element of the vector is considered as synonym

Thank you very much for your work

**Comment by massimoaria** [comment]
Thanks for your remark.

Just solved!
