### ISSUE TITLE
DOI is not part of the structure created by scopus2df

### ISSUE THREAD

**Issue by GilmourR** [massimoaria/bibliometrix#6]
Version 1.9 includes provision for reading the doi field when data is extracted from the Scopus database. However, this field is not present in the data structure created by the scopus2df function. Tested with this data file: http://www.bibliometrix.org/datasets/scopus.bib.

**Comment by massimoaria** [comment]
DOI data are regularly extracted from scopus. These information are stored in the Tag Field "DI" (following the ISI codify as illustrated in the bibliometrix vignette)

**Comment by GilmourR** [comment]
Thank you Professor for your reply and this wonderful package. Assuming M is the data structure produced by scopus2df, I expected to be able to write M$DI[1:10] to get the first 10 doi's. However, M$DI does not exist. I was surprised because having read the doi's in, I expected them to be in M, but that does not appear to be the case. Tq.

**Comment by massimoaria** [comment]
Are you using the last version from github?
Please update bibliometrix using the following code:

install.packages("devtools")
library("devtools")
install_github("massimoaria/bibliometrix")

I tried to import and convert the collection scopus.bib from www.bibliometrics.com\datasets both using scopus2df() and convert2df(). Both methods seems work fine. 

Here the screenshots:
Using convert2df()....
![screen shot 01-24-18 at 06 12 pm](https://user-images.githubusercontent.com/16023543/35346488-abd01218-0132-11e8-9f90-fdc05d06e19b.PNG)

...and using scopus2df()
![screen shot 01-24-18 at 06 18 pm](https://user-images.githubusercontent.com/16023543/35346672-2676b080-0133-11e8-802c-cbd962c87965.PNG)

**Comment by GilmourR** [comment]
Thank you Professor. My mistake. I installed the GitHub version and it works for me. I appreciate your help and all the work you have done to develop 'bibliometrix'.
