### ISSUE TITLE
parameter min.citations of histNetwork cannot be set to 0?

### ISSUE THREAD

**Issue by weikang9009** [massimoaria/bibliometrix#63]
The [docstring for the parameter `min.citations`](https://github.com/massimoaria/bibliometrix/blob/master/R/histNetwork.R#L10) of function `histNetwork` claims "It sets the minimum number of citations for the documents included in the analysis. The default is \code{min.citations = 0}." 

However, in the implementation of this function, [`min.citations=max(c(1,min.citations))`](https://github.com/massimoaria/bibliometrix/blob/master/R/histNetwork.R#L40) makes sure `min.citations` is always larger than 0. 

Would you mind explaining why `min.citations=0` is not allowed? Thanks!

**Comment by massimoaria** [comment]
histNetwork() identify the articles connected each other by direct citations. 
Direct citations or "Local Citations" (LC) are citations among articles included in the same collection. 
"Global Citations" consist instead in the number of citations that an article has received in the whole database scopus or wos and stored in the field tag "TC".
There is a trivial relationship between TC and LC: TC ≥ LC then if TC is 0 this implies that LC is 0. 
And if an article have an LC = 0, the article has never been cited by any other article in the collection and it will not appear in the historical direct citation network.

Choosing min.citation = 0 grow up the computational costs but does not change the results.
It does not make sense searching local citations for articles that have never been cited in the whole DB!

I have just corrected the function documentation fixing min.citation ≥ 1.
