### ISSUE TITLE
'Error in l[[1]]' when using convert2df()

### ISSUE THREAD

**Issue by oliviergimenez** [massimoaria/bibliometrix#65]
Hello, 

First of all, congrats to the authors for an amazing package!

I'm using convert2df() after readFiles() on a bunch of files. Everything works fine except for the file attached, for which convert2df produces "Error in l[[1]]":

D <- readFiles("savedrecs(9).txt")
M <- convert2df(D, dbsource="isi",format="plaintext")

I don't seem to have non-ascii characters, as shown by the result of which(stringi::stri_enc_mark(D)!='ASCII')

Any help would be much appreciated.
Cheers,
Olivier

[savedrecs(9).txt](https://github.com/massimoaria/bibliometrix/files/3468198/savedrecs.9.txt)

**Comment by massimoaria** [comment]
The issue has been solved.

**Comment by oliviergimenez** [comment]
Awesome, thanks a lot!
