### ISSUE TITLE
How to properly format file list for readFiles

### ISSUE THREAD

**Issue by zilch42** [massimoaria/bibliometrix#66]
Hi, I'm having trouble reading in multiple .bib files. 

If I specify them explicitly it works fine:
`readFiles('C:/Users/ABB064/Downloads/savedrecs.bib',  'C:/Users/ABB064/Downloads/savedrecs1.bib', 'C:/Users/ABB064/Downloads/savedrecs2.bib')`

But I have a lot of them so I just want to give it a character vector of all of the names. The following fails:
`files <- list.files(dir, pattern = "*.bib$", full.names = TRUE)`
`readFiles(files)`

printing files to the console looks like this:
`> files`
`[1] "C:/Users/ABB064/Downloads/savedrecs.bib"  "C:/Users/ABB064/Downloads/savedrecs1.bib" "C:/Users/ABB064/Downloads/savedrecs2.bib"`

I have also tried getting the file list with fs::dir_ls()

Both give the following error.
`Error in file(con, "r") : invalid 'description' argument`

How do I properly format the list?

**Comment by massimoaria** [comment]
I made several tests and all works fine.
Are you using bibliometrix in the last version from github?
readFiles() accepts a character vector listing the bib or txt files (with or without path)
and readFiles works fine with dir_ls() but just when your folder contains only the bib/txt files you need (non empty subfolders or other files).

Please send me a zip file with your folder and files so I can try to replicate the issue.

**Comment by zilch42** [comment]
Hi @massimoaria please see attached. Includes three bibtex files and a short script.
I was using the CRAN version but I just installed the github version and got the same error. 
[Bibliometrix Test.zip](https://github.com/massimoaria/bibliometrix/files/3518175/Bibliometrix.Test.zip)

**Comment by massimoaria** [comment]
The issue is due to tcltk package.
When I try to run the code:
dir <- tk_choose.dir(default = "my path etc..", 
                     caption = "Please navigate to the batch folder you wish to process")
My pc goes in a loop and I have to stop Rstudio by task manager.

If I run the following code without using the argument dir, all works fine.

files <- list.files(pattern = "*.bib$", full.names = TRUE)
bibs <- readFiles(files) %>% convert2df(dbsource = "wos", format = "bibtex")
bibData <- biblioAnalysis(bibs)

**Comment by zilch42** [comment]
That is interesting. Thanks for figuring it out.
