### ISSUE TITLE
Interactive network map 

### ISSUE THREAD

**Issue by clbti** [massimoaria/bibliometrix#69]
Hi, 

When using Biblioshiny, the network maps (e.g. keywords co-occurrences) interactive. When using R markdown (HTML), those network maps are static. Is there a way to make these network maps interactive in R markdown?

Thanks
Irine

**Comment by massimoaria** [comment]
You can use visNetwork package to transform a igraph object into an interactive network.

In biblioshiny, I wrote the following function that you can reuse:

 igraph2vis<-function(g,curved,labelsize,opacity,type,shape){
    LABEL <- igraph::V(g)$name
    LABEL[igraph::V(g)$labelsize==0] <- ""
    vn <- toVisNetworkData(g)
    
    vn$nodes$label <- LABEL
    vn$edges$num <- 1
    vn$edges$dashes <- FALSE
    vn$edges$dashes[vn$edges$lty==2] <- TRUE
  
    ## opacity
    vn$nodes$color <- adjustcolor(vn$nodes$color,alpha=min(c(opacity+0.2,1)))
    vn$edges$color <- adjustcolor(vn$edges$color,alpha=opacity)
    
    ## removing multiple edges
    vn$edges <- unique(vn$edges)
    
    ## labelsize
    scalemin <- 20
    scalemax <- 150
    Min <- min(vn$nodes$font.size)
    Max <- max(vn$nodes$font.size)
    if (Max>Min){
      size <- (vn$nodes$font.size-Min)/(Max-Min)*10*labelsize+10
    } else {size <- 10*labelsize}
    size[size<scalemin] <- scalemin
    size[size>scalemax] <- scalemax
    vn$nodes$font.size <- size
    l <- type
    
    ### TO ADD SHAPE AND FONT COLOR OPTIONS
    
    VIS < -visNetwork(nodes = vn$nodes, edges = vn$edges, type="full", smooth=TRUE, physics=FALSE) %>%
      visNodes(shape=shape, font=list(color="black")) %>%
      visIgraphLayout(layout = l) %>%
      visEdges(smooth = curved) %>%
      visOptions(highlightNearest =list(enabled = T, hover = T, degree=1), nodesIdSelection = T) %>%
      visInteraction(dragNodes = TRUE, navigationButtons = TRUE, hideEdgesOnDrag = TRUE)
    values$COCVIS=VIS
    return(list(VIS=VIS,vn=vn, type=type, l=l, curved=curved))
  }

g is an igraph object (the object 'graph' of the networkPlot output list)

curved is a logical (curved edges TRUE or FALSE)
labelsize
opacity  (from 0 to 1)
type (is the network layout argument).
In visNetwork type could be:
type <- "layout_nicely",
type <- "layout_in_circle",
type <- "layout_with_mds",
type <- "layout_as_star",
type <- "layout_on_sphere",
type <- "layout_with_fr",
type <- "layout_with_kk"

shape (is the vertex shape).
It could be:
"box", "circle", "database", "ellipse", "text"

**Comment by clbti** [comment]
Hi Massimo,

Thank you so much for sharing the code!

When I run the above code in R, it did work, and i was able to make the keyword co-occurrence graph interactive. However, when I output it as HTML markdown, it is not interactive. It is still a static graph.

Do you have some insights if i did this wrongly? Thank you again!

NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")
net=networkPlot(NetMatrix, normalize="association", n = 50, Title = "Keyword Co-occurrences", type = "fruchterman", size.cex=TRUE, size=20, remove.multiple=F, edgesize = 10, labelsize=3,label.cex=TRUE,label.n=30,edges.min=2)

igraph2vis<-function(g,curved,labelsize,opacity,type,shape){
  LABEL <- igraph::V(g)$name
  LABEL[igraph::V(g)$labelsize==0] <- ""
  vn <- toVisNetworkData(g)
  vn$nodes$label <- LABEL
  vn$edges$num <- 1
  vn$edges$dashes <- FALSE
  vn$edges$dashes[vn$edges$lty==2] <- TRUE
  
  ## opacity
  vn$nodes$color <- adjustcolor(vn$nodes$color,alpha=min(c(opacity+0.2,1)))
  vn$edges$color <- adjustcolor(vn$edges$color,alpha=opacity)
  
  ## removing multiple edges
  vn$edges <- unique(vn$edges)
  
  ## labelsize
  scalemin <- 20
  scalemax <- 150
  Min <- min(vn$nodes$font.size)
  Max <- max(vn$nodes$font.size)
  if (Max>Min){
    size <- (vn$nodes$font.size-Min)/(Max-Min)*10*labelsize+10
  } else {size <- 10*labelsize}
  size[size<scalemin] <- scalemin
  size[size>scalemax] <- scalemax
  vn$nodes$font.size <- size
  l <- type
  
  ### TO ADD SHAPE AND FONT COLOR OPTIONS
  
  VIS <- visNetwork(nodes = vn$nodes, edges = vn$edges, type="full", smooth=TRUE, physics=FALSE) %>%
    visNodes(shape=shape, font=list(color="black")) %>%
    visIgraphLayout(layout = l) %>%
    visEdges(smooth = curved) %>%
    visOptions(highlightNearest =list(enabled = T, hover = T, degree=1), nodesIdSelection = T) %>%
    visInteraction(dragNodes = TRUE, navigationButtons = TRUE, hideEdgesOnDrag = TRUE)
  vn$COCVIS=VIS
  return(list(VIS=VIS,vn=vn, type=type, l=l, curved=curved))
}

igraph2vis(net$graph,TRUE,3, 0.4,"layout_with_mds","circle")

**Comment by massimoaria** [comment]
No, try to search on google "how to include visNetwork in rmarkdown"

**Comment by clbti** [comment]
No worries Massimo, I managed to get it to work. Thanks a lot for the help!

**Comment by clbti** [comment]
Hi Massimo, I have another question regarding the network map. 

Using Biblioshiny(), the size of the nodes are nicely generated in relation to the number of publications published by the institutions or the authors . However, when I used the above code to try to replicate it in Markdown, all the nodes have the same size. Can you kindly advise how can i set this up? Thanks.

Attached are the 2 graphs as comparison.

![using biblioshiny](https://user-images.githubusercontent.com/35282535/64153572-bb3d0a00-ce61-11e9-9878-536507269c7e.jpg)
![using R](https://user-images.githubusercontent.com/35282535/64153573-bb3d0a00-ce61-11e9-884c-6b2589c0cb9b.jpg)

**Comment by massimoaria** [comment]
The node size can be set using the arguments "size" and "size.cex" in networkPlot function.
