### ISSUE TITLE
Suggestion: A Function to convert rscopus::scopus_search responses to M objects

### ISSUE THREAD

**Issue by benjaminschwetz** [massimoaria/bibliometrix#71]
Hi,

I am planning to use bibliometrix on `rscopus::scopus_search`, instead of going through scopus website and downloading bib-files.

I.e. something like:

```
response <- rscopus::scopus_search("TITLE-ABS-KEY(somthing and something)")
data <- rscopus::gen_entries_to_df(response$entries)
M <- new_function(data)
```

I have only recently started to use both, `rscopus` and `bibliometrix` and as far as I can see, you are already wrangling some of the output e.g. from `rscopus::author_df_orig` in `bibliometrix::retrievalByAuthorID`  So I am a bit surprised that there seems to be no general function to generate M-objects directly, like `convert2df` does.

Before I go on and write something myself, I wanted to ask, is this something you have already looked at and abandoned, or is this out of scope for you?

**Comment by massimoaria** [comment]
I wrote retrievalByAuthorID function to allow  to download and analyze all publications of a set of authors directly with bibliometrix.
The idea to write a general function to wrangle rscopus output  is very good but, at the moment, I am very busy to do that.
Most of the code required to write a general function to generate M-objects is already included in retrievalByAuthorID. 
Let me know if you write something.

Best
Massimo

**Comment by Biabiatiz** [comment]
Hello!

Hope you're doing well.
I'm interested in the same issue (to join rscopus and bibliometrix). 
So, my doubt is the same.. Before I work on something by myself, I would like to know if you guys have already tried something about it? 

Best
Bia
