### ISSUE TITLE
Removing Topic Dendogram chart

### ISSUE THREAD

**Issue by itanudjaja** [massimoaria/bibliometrix#74]
Hi, may I know if it is possible to remove the topic dendogram chart when i run this line of code?

CS <- conceptualStructure(M, method="MCA", field="ID", minDegree=10, clust=5, stemming=FALSE, labelsize=8,documents=20)

I tried to edit the conceptualStructure function on this line:
if (isTRUE(graph)){plot(b_dend)} 

But i kept getting the following error:
Error in get_mca_var(res.mca) : could not find function "get_mca_var"

Would appreciate your advice on this, thank you!

**Comment by massimoaria** [comment]
You can run conceptualStructure using the argument graph=FALSE and then plot only the graphs you need.
i.e.
CS <- conceptualStructure(M, method="MCA", field="ID", minDegree=10, clust=5, stemming=FALSE, labelsize=8,documents=20, graph=FALSE)
CS$graph_terms                      # plot the word map
CS$graph_dendogram             #plot the dendrogram
CS$graph_documents_Contrib #plot the most contributing documents
CS$graph_documents_TC         #plot the most cited documents

**Comment by itanudjaja** [comment]
Thanks very much Massimo

**Comment by itanudjaja** [comment]
Hi Massimo, I created a collaboration network for institutions and would like to clarify the following:

- The size of the node (i.e. institution) corresponds to the no of publications affiliated to the institutions  (if size.cex=T)

- The edge size between two nodes corresponds to the no of publications they collaborated together

- How about the distance between the nodes and color of the node? Do they mean anything?

Thanks
