### ISSUE TITLE
Error with thematicEvolution()

### ISSUE THREAD

**Issue by KVanMeerbeek** [massimoaria/bibliometrix#77]
I get some errors when using thematicEvolution(). I tried to run this function with one or two breaks, with the following errors as a result (the code works fine with the example dataset scientometrics):
> years=c(1980,2000)
> TE <- thematicEvolution(M,field="ID",years=years,n=100,minFreq=2)
Error in par(mfrow = c(1, (K - 1))) : 
  invalid value specified for graphical parameter "mfrow"
> years=c(1990)
> TE <- thematicEvolution(M,field="ID",years=years,n=100,minFreq=2)
Error in names(df) <- N : 
  'names' attribute [1] must be the same length as the vector [0]

My dataframe M is 2028 obs x 38 variables. I ran several other functions of your package. They all worked fine. I extracted the data from WoS (Full record and Cited references).

**Comment by yuyllove** [comment]
I also get some errors when using thematicEvolution()
`yearcut <- c(1979, 1989, 1999, 2009)
nexus <- thematicEvolution(M, 
                  field = "DE", 
                  years = yearcut,
                  n = 150 )`
Error in `V<-`(`*tmp*`, value = `*vtmp*`) : invalid indexing

**Comment by massimoaria** [comment]
Please, attach your data and code so I can try to identify the issue

**Comment by yuyllove** [comment]
Thanks. My data and  code were found in Open #79

**Comment by KVanMeerbeek** [comment]
Thanks. My data is attached
[Full.zip](https://github.com/massimoaria/bibliometrix/files/3850739/Full.zip)

**Comment by massimoaria** [comment]
> Thanks. My data is attached
> [Full.zip](https://github.com/massimoaria/bibliometrix/files/3850739/Full.zip)

Your file contains documents published form 2019 to 2020. It's obvious that themativEvolution does not work when you set years <- c(1980,2000) or years <- c(1990).

**Comment by massimoaria** [comment]
> I also get some errors when using thematicEvolution()
> `yearcut <- c(1979, 1989, 1999, 2009) nexus <- thematicEvolution(M, field = "DE", years = yearcut, n = 150 )`
> Error in `V<-`(`*tmp*`, value = `*vtmp*`) : invalid indexing

You are tried to perform a Thematic Evolution Analysis on authors' keywords dividing the timespan into 5 periods using 4 cutting points.
Looking at your collection, in the periods: 1971-1979 and 1980-1989 no document contains authors' keywords so the network matrices are empty and the function returns an error.
If you try to spit your collection in larger periods or o perform the analysis on a different content field (i.e. title or abstract) all works fine.

In any case, the period 1971-1979 contains only two documents and the period 1980-1989 only 7. It does not make sense to perform a network analysis in such a small sub-collection.

When you have to decide how to choose the cutting point, the first thing is to have a look at the document annual distribution
![image](https://user-images.githubusercontent.com/16023543/68937008-ea45f500-079b-11ea-8b29-d4da5d900be2.png)
