### ISSUE TITLE
Data loss in bibtex import to Bibliometrix (in ID tag)

### ISSUE THREAD

**Issue by mlcanales** [massimoaria/bibliometrix#80]
Hey, excellent work, really love Bibliometrix, definitely a fan !!

I downloaded the same keyword-search through both WOS and Scopus search engines as bib files. Uploaded both to R, merged them and removed duplicates. As far as I understand, the 'ID' column saves the "Indexed Keywords" from the Scopus database. For example, the second paper of my merged database "Agent-Based Modeling for Evaluation of Crop Pattern and Water Management Policies", has in R only 4 elements in the 'ID' column (FRAMEWORK; OPTIMIZATION; DEMAND; LAND; SYSTEMS). However, in Scopus it has many more (attached is an image from Scopus), which apparently were not imported. 

![imagen](https://user-images.githubusercontent.com/54724008/68189631-d7932980-ffff-11e9-885f-108ac9d02f20.png)

Below I leave the code I used, and then the 2 bib files:

CODE:
`WDB <- readFiles("wos_new.bib")`
`SDB <- readFiles("scopus_new2.bib")`
`WDB_DF <- convert2df(WDB, dbsource = "isi", format = "bibtex")`
`SDB_DF <- convert2df(SDB, dbsource = "scopus", format = "bibtex")`
`Merged <- mergeDbSources(WDB_DF, SDB_DF, remove.duplicated=TRUE)`
`New_Merged <- duplicatedMatching(Merged, Field = "DI", tol = 0.95)`

FILES:
[files.zip](https://github.com/massimoaria/bibliometrix/files/3807855/files.zip)

If there is anything else you need please let me know. 
Currently, I'm running everything in Jupyter Lab, and found this problem while cleaning the database (misspelling of elements) with Python there (my ultimate aim is to design a jupyter notebook of all the procedure (from database extraction all the way to final outputs).

**Comment by mlcanales** [comment]
I have managed to clean the database through python, but have not been able to re-upload the file back to bibliometrix for all the graphs. Specifically, I use convert2df to obtain a bibliometrix dataframe. Then with write.csv I get the excel file out to edition. However, when I re-upload it to bibliometrix with the same columns and data types initially exported, I lose the changes I made on the file.

Any way around this (i.e. getting a ".csv" with the same characteristics as the "bibliometrix dataframe" back inside of bibliometrix)?

I have been doing the following:
`write.csv(New_Merged,'Merged_Dataframe_2.csv')`
`M <- read.csv(file = "C:/Users/.../Merged_Dataframe_2.csv")`
` H <- convert2df(M, dbsource = "isi", format = "csv")`

I also tried to import directly the csv with:
`M <- read.csv(file = "C:/Users/.../Merged_Dataframe_2_checked.csv")`

But get "Error in strsplit(AFF, sep, fixed = TRUE): non-character argument" from any graph or analysis code: 
`results <- biblioAnalysis(M, sep = ";") `

**Comment by massimoaria** [comment]
ID column stores the indexed keywords both for WOS and Scopus DBs (ID is acronymous of Indexed Keywords). These keywords are automatically assigned to a document by a statistical algorithm based on the article reference list. This means that each DB could assign a different set of ID keywords to the same document. 
The function duplicatedMatching just identify two duplicated documents (using a target field, ie. the title) and remove one of the two records. This implies that you could lose the ID keywords of the deleted records.
The function should be changed to keep this information. I will put this task in my to-do list.
