### ISSUE TITLE
Typo in the tutorial maybe?

### ISSUE THREAD

**Issue by silviaegt** [massimoaria/bibliometrix#86]
Hi there, I am translating/adapting your intro to Bibliometrix into Spanish.
I am at this [point](https://github.com/cran/bibliometrix/blob/master/inst/doc/bibliometrix-vignette.Rmd#L365), but I feel like there's something wrong, I ran the summary() function, to this data frame:

```
archivo <- readFiles("datos/scopus.bib")
df <- convert2df(archivo, dbsource = "scopus", format = "bibtex")
analisis <- biblioAnalysis(df, sep = ";")
puntosclave <- summary(object = analisis, k = 10, pause = FALSE)
```

And got these numbers from "puntosclave" (the variable with the summary results):

```
Authors per Document                  2.24 
Co-Authors per Documents              3.02 
```

In your introduction you say that 
>  *Authors per Article index ≥ Co-authors per Article index*

But as you can see I got the exact opposite.

The bib file I used is [here](https://redescolmex-my.sharepoint.com/:u:/g/personal/segutierrez_colmex_mx/Edbf38NiBMhIh6T-SEGbLIEB8ck9OS8Q3XhbQn8GLnbKbg?e=YARfIa).

Thank you so much for this amazing package!

**Comment by massimoaria** [comment]
Yes it is a typo. 
The correct sentence is:
Authors per Article index ≤ Co-authors per Article index.

I have just corrected the sentence.
