### ISSUE TITLE
Problem convert2df: Error in "PY" %in% names(M) : object 'M' not found

### ISSUE THREAD

**Issue by acgalina** [massimoaria/bibliometrix#87]
My _web of science_ file have this structure: 
AU | AF | TI | SO | LA | DT | DE | ID | AB | C1 | RP | RI | OI | FU | FX | CR | PU | PI | PA | SN | EI | BN | J9 | JI | PD | PY | VL | IS | PN | SU | SI | MA | BP | EP | AR | DI | D2 | EA | PG | WC | SC | GA | UT | PM | OA | HC | HP | DA

> D <- readFiles ("web-nov2.csv");
Converting your wos collection into a bibliographic dataframe
> M <- convert2df(D, dbsource = "wos", format = "csv") 
Error in "PY" %in% names(M) : object 'M' not found

I read that the problem could it be the AU_UN, however, I do not have this field in the sample.
How to proceed?

Thank you very much.

**Comment by massimoaria** [comment]
convert2df supports the following formats:
- For Web of Science, Plaintext or Bibtex
- For Scopus, Bibtex
- For Dimensions, csv or Excel

Then your issue is due to trying to import an unsupported format.

**Comment by acgalina** [comment]
What would it be for dimensions?
When I analyze a technology, I directly import the database.
But when I study a university (or institution), I need to clean up the database, because I always have a false positive, so I need to edit the data (usually Excel).
Is there any other way to import this data using convert2df, after correction through (keeping the same structure)?

**Comment by blackkq** [comment]
hello massimoaria,
I think your answer is unsufficient becuase AndreiaGalina said that it was an excel format and is supported by convert2df.

Also, I am getting the same problem.

**Comment by massimoaria** [comment]
My answer is not insufficient but only old (more than a year ago).
During 2020, we introduced many new features including support for excel and CSV files exported from Dimensions.
Then, it is correct that (now) convert2df supports excel files from dimensions (NB. these excel files do not include all metadata!!).
Unfortunately, I am not yet able to predict the future when I answer. So, generally, my answers regard the features bibliometrix include till then.

**Comment by blackkq** [comment]
> My answer is not insufficient but only old (more than a year ago).
> During 2020, we introduced many new features including support for excel and CSV files exported from Dimensions.
> Then, it is correct that (now) convert2df supports excel files from dimensions (NB. these excel files do not include all metadata!!).
> Unfortunately, I am not yet able to predict the future when I answer. So, generally, my answers regard the features bibliometrix include till then.

ahh thanks very much massimoaria, I handled it by downloading .bib file,

it is an useful package thanks again!!

**Comment by jesusgodoy007** [comment]
I solved it adding dbsource = "scopus" and format = "bibtex".  I should note that I had update R to the last version R4.2.3.
