### ISSUE TITLE
LCS / GCS -- localCitations

### ISSUE THREAD

**Issue by silviaegt** [massimoaria/bibliometrix#88]
Hi @massimoaria, the localCitations() function creates a table with two columns named LCS and GCS, I am guessing they mean Local Citations Score and Global Citations Score but I could not find any documentation on this, would you confirm please if this is the case and how the GCS is calculated?

**Comment by massimoaria** [comment]
LCS is the Local Citation Score. LCS measures the number of citations that an article received from the other articles of the analyzed collection.
GCS is the Global Citation Score (or Total Citations). GCS is the number of citations collected in the whole bibliographic database. It is just equal to the value stored in the column "TC".
