### ISSUE TITLE
histNetwork() on scopus data fails to match citations with special characters in title

### ISSUE THREAD

**Issue by joachim-gassen** [massimoaria/bibliometrix#89]
Hi there:

Thank you very much for this wonderful package. It is extremely useful. When implementing a local citation analysis I noticed that histNetwork() seems to fail on finding references in `CR` fields when the `TI` field contains a question mark.

Looking into the code of `histNetwork()` it seems as if the problem is in the matching of the title string as it is using regex matching and the question mark gets treated as a special character.

I do not understand why the matching is being done on a regex (the `TI` field contains no regex) and thus change the `grep()` calls to use fixed patterns instead. 

This works for my use case but I am unsure whether it silently breaks in other settings. If it does I would appreciate a quick heads up. I will issue a PR in a minute. Feel free to ignore if my diagnosis is off.

Cheers!

Joachim

**Comment by massimoaria** [comment]
Dear Joachim

I have checked your commits and all seems work fine.
So, I have merged your contributions.

Thanks
Massimo
