### ISSUE TITLE
Issues including bibliometrix in another package

### ISSUE THREAD

**Issue by zilch42** [massimoaria/bibliometrix#91]
I'm trying to make use of bibliometrix in a package (just of helper functions for my own use). But I'm having a weird dependency issue. 

The following lines are in a function in my package. 
` bibData <- bibliometrix::readFiles(filelist) %>%
    bibliometrix::convert2df(dbsource = "wos", format = "bibtex") %>%
    bibliometrix::biblioAnalysis()`

The convert2df step throws the following error unless I actually have bibliometrix loaded in my session. 

> Error in `[.data.frame`(bibtag, , "ISI") : undefined columns selected
> In addition: Warning message:
> In data("bibtag", envir = environment()) :

The function correctly imports the functions I'm calling:
`#' @importFrom bibliometrix readFiles convert2df biblioAnalysis`

My description file correctly imports bibliometrix

devtools::check() doesn't have any problems

does convert2df depend on something else i need to import?...

**Comment by massimoaria** [comment]
You need to import bibtag and countries datasets.

**Comment by zilch42** [comment]
Thanks @massimoaria. How do I do that? I tried adding them to the @ImportFrom bibliometrix line but got the following errors on devtools::check()

> Warning: object ‘bibtag’ is not exported by 'namespace:bibliometrix'
> Warning: object ‘countries’ is not exported by 'namespace:bibliometrix'

It looks like they're internal

**Comment by zilch42** [comment]
I've temporarily solved it by making my package "depend" on bibliometrix rather than "import" I don't believe thats the ideal solution
