### ISSUE TITLE
Launch biblioshiny with a fixed port

### ISSUE THREAD

**Issue by wuhanstudio** [massimoaria/bibliometrix#95]
Hi,

I'm a Ph.D. student in CS, and I find bibliometrix is really helpful with my research.

I notice that biblioshiny server is launched with a random port every time. Is there any way to pass a fixed port as a parameter into biblioshiny() so that it will launch on a desired port?

Thanks a lot for your help.
Han.

**Comment by massimoaria** [comment]
I have just included the argument port in biblioshiny().
Now, you can using biblioshiny specifying the local port:

biblioshiny(port=6000)

If port=NULL, the port will randomly selected.
